### ISSUE TITLE
using bear

### ISSUE THREAD

**Issue by pmokri** [rizsotto/Bear#100]
I am sorry I am new to this but it seams every time I use bear on any makefile it tries to overload LD_PRELOAD. 
I am on my school's network and I don't have root permission, I use redhat and this is the command I type in MyProject folder:
 tools/Bear/build/usr/local/bin/bear make -e /tools/Bear/build/libear/libear.so

and this is the error I get:
ERROR: ld.so: object '/usr/local/lib64/libear.so' from LD_PRELOAD cannot be preloaded: ignored.
make: Nothing to be done for `tools/Bear/build/libear/libear.so'.

Thank for your help in advance!

**Comment by rizsotto** [comment]
hi @pmokri , wish i can help but you need to tell me what do you want to do. :) Bear is using `LD_PRELOAD` to make its job. to do that you don't need to be root user on the machine... all you need to do compile and install Bear on the machine. you can install program into your home directory without root privileges. see [some](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html) cmake manual page.
