### ISSUE TITLE
How do I specify compiler name I'm using?

### ISSUE THREAD

**Issue by kota65535** [rizsotto/Bear#103]
I'm using the compilers named as `avr-gcc` and `avr-g++`.
I found that the compiler names in `compile_commands.json` are stripped as `cc` and `c++`...
According to #38, it seems to be already implemented that we can specify arbitrary compiler name by configuration file or environment variable, isn't it?
But I could not find any instructions to do so...

**Comment by rizsotto** [comment]
recent Bear (2.x) had a rewrite and works differently... to keep the compiler names were never a target. #38 was also not about what compiler will be showed up in the compilation database... can you explain what would you like to achieve? and how does the current output stops you doing that?

**Comment by kota65535** [comment]
I'm using vim and trying to do syntactic check by running the desired compiler.
For the project using cross compiler such as `avr-gcc`, I also want to use it for syntactic check, rather than `cc`.

But considering it , there is probably no difference to use `avr-gcc` or `cc` for the purpose of syntax check... 
Maybe this issue should be closed. Sorry for confusing you.

**Comment by rizsotto** [comment]
just to make clear, when you use some vim plugin to do the syntax check from a compilation database. it always ignores the compiler name and use `clang` in every cases. ;) if you want that to check architect specific things, (like you have macros for different architectures) you shall pass `-arch` to enable certain macro definitions.

**Comment by kota65535** [comment]
Thanks for your advise, but I have some trivial questions.

> you shall pass -arch to enable certain macro definitions in your build for Clang

Is this means that executing `clang -arch avr` is equal to `avr-gcc` for example?
I tried it, but clang tells me arch name is invalid...

And recently, I'm stuck in some new problem. The default search path is the compiler specific, isn't it?
`avr-gcc` on my machine with `-v` option says:

```
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/include
 /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/include-fixed
 /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/include
End of search list.
```

And clang is:

```
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

By this difference, I think I have to run `avr-gcc` for doing syntactic check. So it will be happy if the compiler name can be found in compiler_commands.json.

**Comment by rizsotto** [comment]
compilation database is an input for tools/plugins build on top of Clang tooling library. that library will always use Clang specific things (like search path, parser, etc...). if you wondering how to change search path, ask it on their mailing list or read the documentation/source code about it. (i don't know the answer.) but i am certainly sure just to replace the compiler name won't make any difference. (you can search-replace the compiler name in the compilation database file with your editor and see it.) also, i don't have experience on cross compilation. so, can't tell you what argument to pass for your target platform.

**Comment by kota65535** [comment]
Hmm, I had better using --disable-filter option and parse it by myself.
