### ISSUE TITLE
Doesn't work in my project

### ISSUE THREAD

**Issue by leopoldfreeman** [rizsotto/Bear#104]
I didn't use LD_PRELOAD or DYLD_INSERT_LIBRARIES. But bear failed to work.

To reproduce:
>git clone git@github.com:leopoldfreeman/parrot.git
>cd parrot
>bear make # Need linux & c++11
>cat compile_commands.json
[]

**Comment by jwintz** [comment]
What linux are you running ? Have SELinux enabled ? It might make code injection fail.

  - ju

**Comment by leopoldfreeman** [comment]
Yeah, it is SELinux. Thanks.

**Comment by jwintz** [comment]
You're welcome ;-)
