### ISSUE TITLE
ios 10.11 cannot get cmdlines

### ISSUE THREAD

**Issue by aamen110** [rizsotto/Bear#105]
I use Vmware 12   made a virtual machine ios 10.11.1  bear can not get cmdlines

And I test on10.8.5 real machine and it works fine

Is the  virtual machine problem or the bear not support os 10.11.1

**Comment by jwintz** [comment]
I do not quite understand your question but if you are referring to MacOSX, #102 will give you some hints.

**Comment by aamen110** [comment]
ok, I got it.
bear cannot work with SIP.

Is there any solution can solve this problem.
wrap CC and CXX environment variables have Limitations

thanks
