### ISSUE TITLE
Wrong compiler when the source file is compiled as C++ because of extension convention

### ISSUE THREAD

**Issue by hackaugusto** [rizsotto/Bear#109]
Here is what happened [version 2.1.2]:

- Bear uses the *executable path* to decide if the json key `command` will have the **cc** or **c++** compiler.
- I'm using the `compile_commands.json` file to configure the [you-complete-me](https://github.com/Valloric/YouCompleteMe) extension, because I don't want to have many files with flags to keep in sync.
- I'm writing a C++ extension for python, and it is being compiled from a `setup.py` file, that by default will use **gcc** as the compiler.
- I'm running `bear python setup.py build`, **gcc**  will [compile the extension as a **C++**](https://gcc.gnu.org/onlinedocs/gcc/Invoking-G_002b_002b.html) compiler because the file extension is **.cpp**, but Bear will report a **cc** compiler since the *executable path* lacks the `++` string.
- The purpose of using Bear is defeated since the tool *you-complete-me* will also use the compiler name from the `compile_commands.json` to decide if the source code is **C** or **C++**.

So, I'm not sure if this is a bear or you-complete-me problem, the flag `-std=c++11` is also ignored.

My current work around is quite simple, I just force the `setup.py` script to use g++ with `CC=g++ bear python setup.py build`

**Comment by rizsotto** [comment]
thanks for the report. i think your workaround is the right solution. would not modify Bear in order to work in this scenario. (i saw your pull request, nice work. yes, it is possible to make it work like that.) i think it is the build responsibility to call the right compiler. (you need to call the right one if it's linking too. see the example under.) Bear just simple copy it as it is. it replace it to 'cc' and 'c++' because OSX has compiler wrappers, and those would generate multiple entries for the same file.

```
$ gcc -c test.cpp
$ gcc test.cpp
/tmp/ccNjL3QX.o: In function `main':
test.cpp:(.text+0xa): undefined reference to `std::cout'
test.cpp:(.text+0xf): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&,
char const*)'
test.cpp:(.text+0x14): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
test.cpp:(.text+0x1c): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
/tmp/ccNjL3QX.o: In function `__static_initialization_and_destruction_0(int, int)':
test.cpp:(.text+0x4a): undefined reference to `std::ios_base::Init::Init()'
test.cpp:(.text+0x59): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
```
