### ISSUE TITLE
Please don't filter out -m options

### ISSUE THREAD

**Issue by joshtriplett** [rizsotto/Bear#115]
bear filters out all "optimization" options that start with `-m`.  However, removing options like -mssse3 or -msse4.2 can break the build.  For instance, the various vector intrinsic header files will generate an error if included without the corresponding instruction set turned on.  So, running checks based on a bear-generated compilation database will error out on files including those intrinsic headers.

**Comment by rizsotto** [comment]
thanks Josh, will fix it this week!
