### ISSUE TITLE
Bear does not capture compiler calls made with boost.build aka 'bjam' or 'b2'

### ISSUE THREAD

**Issue by mccann** [rizsotto/Bear#118]
Capturing of compiler calls does not occur because the bjam/b2 executable launches such calls via calls to a shell. 

I have made a pull request (https://github.com/rizsotto/Bear/pull/117) that identifies 'shell' calls, and performs the same matching logic on the first token in the shell request.

**Comment by rizsotto** [comment]
could you provide more info about your environment? (OS, distro, python version, compiler version, boost version)

**Comment by mccann** [comment]
OS:  OS X 10.11.3 (El Capitan)
Default Apple Python (Python 2.7.10)
Compiler: Apple LLVM version 7.0.2 (clang-700.1.81)
Boost.Build: Boost.Build 2015.07-git

**Comment by rizsotto** [comment]
thanks, please look at the readme file, known issues section.
