### ISSUE TITLE
Empty Compilation Database on Ubuntu 14.4

### ISSUE THREAD

**Issue by bernardnongpoh** [rizsotto/Bear#119]
I installed Bear successfully both from repository and also tried from source.
But when I run
$bear make // It run normally but generate a [ ] empty file
Is there any security issue as mention in the documentation for UBUNTU 14.4
Here is My Makefile

BINDIR = ../bin
OBJDIR = ../obj
SRCDIR = .

OBJECTS = $(OBJDIR)/asmg.o \
	$(OBJDIR)/32_hash.o \
	$(OBJDIR)/32_store.o \
	$(OBJDIR)/quad_store.o \
	$(OBJDIR)/align.o \
	$(OBJDIR)/checksum.o \
	$(OBJDIR)/comparisons.o \
	$(OBJDIR)/consensus.o \
	$(OBJDIR)/output.o \
	$(OBJDIR)/relink.o \
	$(OBJDIR)/rep_find.o \
	$(OBJDIR)/scoring.o \
	$(OBJDIR)/usage.o

SOURCES = $(SRCDIR)/asmg.c \
	$(SRCDIR)/32_hash.c \
	$(SRCDIR)/32_store.c \
	$(SRCDIR)/quad_store.c \
	$(SRCDIR)/align.c \
	$(SRCDIR)/comparisons.c \
	$(SRCDIR)/consensus.c \
	$(SRCDIR)/checksum.c \
	$(SRCDIR)/output.c \
	$(SRCDIR)/relink.c \
	$(SRCDIR)/rep_find.c \
	$(SRCDIR)/scoring.c \
	$(SRCDIR)/usage.c

CC	= gcc
CFLAGS	= -O4 
LIBS	= -static

all: $(BINDIR)/TIGR_Assembler

$(BINDIR)/TIGR_Assembler : ${OBJECTS}
	${CC} ${CFLAGS} -o $@ ${OBJECTS} ${LIBS}

$(OBJDIR)/asmg.o : matrices.h asmg_global.h typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/asmg.c -o $@

$(OBJDIR)/consensus.o : matrices.h typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/consensus.c -o $@

$(OBJDIR)/comparisons.o : typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/comparisons.c -o $@

$(OBJDIR)/output.o : matrices.h typedefs.h mat_output.h
	${CC} ${CFLAGS} -c ${SRCDIR}/output.c -o $@

$(OBJDIR)/32_hash.o : typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/32_hash.c -o $@

$(OBJDIR)/32_store.o : typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/32_store.c -o $@

$(OBJDIR)/quad_store.o : typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/quad_store.c -o $@

$(OBJDIR)/align.o : matrices.h typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/align.c -o $@

$(OBJDIR)/relink.o : matrices.h typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/relink.c -o $@

$(OBJDIR)/rep_find.o : matrices.h typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/rep_find.c -o $@

$(OBJDIR)/scoring.o : matrices.h typedefs.h
	${CC} ${CFLAGS} -c ${SRCDIR}/scoring.c -o $@

$(OBJDIR)/checksum.o :
	${CC} ${CFLAGS} -c ${SRCDIR}/checksum.c -o $@

$(OBJDIR)/usage.o :
	${CC} ${CFLAGS} -c ${SRCDIR}/usage.c -o $@

lint :
	lint ${SOURCES}

clean :
	rm  -f $(OBJDIR)/*.o $(BINDIR)/TIGR_Assembler

**Comment by rizsotto** [comment]
hi Bernard, is this issue still there? what's the reason you closed it?

**Comment by bernardnongpoh** [comment]
Hi Rizsotto, initially I installed from ubuntu repository i does not work .  Then I installed from source it work successfully. Maybe from repo there is some bug. 
when I check the version 
$ bear -vesion
bear<--- this is the output
from source
$bear --version
bear 2.1.5
It worked 

 Thanking you .

**Comment by rizsotto** [comment]
glad that you worked it out. ;)
thanks for the explanation!

**Comment by bernardnongpoh** [comment]
Most welcome , Thanks for the tool it save us a lot of time .
