### ISSUE TITLE
Flags for a kernel module

### ISSUE THREAD

**Issue by mexus** [rizsotto/Bear#120]
Hi!

I'm developing a linux kernel module, and use a `compile_commands.json` file to provide an autocomplition in vim.
I've tried to generate it with
```
bear make
```
But it has failed in a sense that the resulting `compile_commands.json` was empty.
Then i've tried to use it another way around:
```
make CC=gcc
```
And another way...
```
make CC=clang
```
... and surprisingly the correct json was generated.

IDK whether it's a bug, an issue, or does it work that way by design, or something else, but from my point of view the behavior is a little bit.. illogical. Or maybe i'm just using it the wrong way?

And thanks for this quit useful tool! It has saved me a lot of time and nerves already ;)

In case you would like to reproduce the.. case, here is a minimal example (copy-paste to your shell):
```bash
cat > Makefile << EOF
obj-m += test.o
all:
	make -C /lib/modules/\$(shell uname -r)/build M=\$(PWD) modules
EOF
touch test.c
bear make ....
```
Also you have to have kernel headers to compile a kernel module.

**Comment by rizsotto** [comment]
thanks for the report. will look into it next week!

**Comment by rizsotto** [comment]
try to reproduce this, with the latest version (2.1.5) on archlinux and it generated a non empty compilation database... anyway, i think the problem will be that it does not recognize your "default" compiler... can you figure out what is the compiler that `make` execute on your machine? (if you call `bear -n make` it will generate not a compilation database, but a list of the executed commands during the build process. from that list you can see what was it.)

**Comment by mexus** [comment]
Nah, my bad, sorry. Looks like my version was out of date -- 2.1.3. Installed a "bear-git" package from AUR and now it works like a charm just out of the box.

Also now I'm thinking that maybe i didn't run "make clean" before a "bear make", though yesterday i was sure i did it..

Nevertheless with the latest version I can't reproduce the "problem" either way, so sorry for a false report, at least i should have tried to test the latest version at the first place :-(

**Comment by rizsotto** [comment]
no worries, glad that you can make it. :)
