### ISSUE TITLE
Building a RPM

### ISSUE THREAD

**Issue by mheiskan** [rizsotto/Bear#121]
Perhaps you should add the following line to your CMakeLists.txt file:

`set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION /usr/share/man /usr/share/man/man1)`

If you wish to install the package to a "normal" system location instead of /usr/local, you'd use something like

`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr . && make all && cpack -G RPM`

but would get a conflict due to /usr/share/man and /usr/share/man1 being owned by the filesystem-package. cmake really should exclude all directories owned by the filesystem-package, but that is not the case at least in version 3.5.0.

**Comment by rizsotto** [comment]
thanks @mheiskan, as far as i know Bear has been packaged for debian, arch and brew. (don't know about rpm based distributions.) and not sure that these packages are based on cpack package creation... anyway, if you want this change, would be glad to have pull request for it... and would consider to use one of the cmake variable to use (like for `/usr/local/lib` it has `${CMAKE_INSTALL_LIBDIR}`. so maybe for `/usr/local/share` it also has something.)
