### ISSUE TITLE
adapt AIX

### ISSUE THREAD

**Issue by aamen110** [rizsotto/Bear#123]
I tried adapte bear on AIX6.1
add
LDR_PRELOAD
LDR_PRELOAD64
But it does not work.

Have anyone adapted AIX?

**Comment by rizsotto** [comment]
pull requests are welcome! :) i don't have access to such machine. but can guide you to make a port, if you like... and it [looks](https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000014142747), that AIX preload mechanism has security protection.

**Comment by rizsotto** [comment]
or you can try [scan-build](https://github.com/rizsotto/scan-build), that has another mechanism than preload a lib. (it wraps the compilers. so, if your build system respect `CC` and `CXX` environment, it can work for you.)

**Comment by aamen110** [comment]
It works in aix
 the .so should compile  with xlc and link with local ld

**Comment by rizsotto** [comment]
would you send a diff or create a pull request? i'm curious.

**Comment by aamen110** [comment]
32-bit processes LD_PRELOAD  ->LDR_PRELOAD 
64-bit processes LD_PRELOAD  ->LDR_PRELOAD64 
there is not a lot of work on source code.
but
should use IBM xlc to compile the source code and IBM ld link the .so
if use gcc and gnu ld  , will get errors like    "xx.so  Bad format"
