### ISSUE TITLE
Load Error when installed in non-default location

### ISSUE THREAD

**Issue by Keno** [rizsotto/Bear#129]
```
$ make DESTDIR=$HOME install
$ bear make
ERROR: ld.so: object '/usr/local/lib/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Comment by rizsotto** [comment]
thanks for the report, but CMake does not work like that. please check the CMake documentation for more, or look how [packagers](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bear) do.
