### ISSUE TITLE
Not support ccache

### ISSUE THREAD

**Issue by jeehou** [rizsotto/Bear#131]
My Makefile file looks like thie:
#ifndef _NOCACHE                        
#CC += ${NSS_SRC}/deps/ccache/bin/ccache
#endif                                  

The compile_commands.json file after "bear make -j4" almost not contains any commands.

**Comment by rizsotto** [comment]
thanks Jian for the report. i know about the problem (earlier it was even mentioned in the readme file.) will think about to fix it. as a workaround, run your build without ccache and you will have the compilation database.

**Comment by KholdStare** [comment]
I would like to cast a vote to support ccache too. Our build takes forever, and I switch between branches fairly frequently, so ccache is a must most of the time. Do you know what needs to be done support it? Any pointers if I were to try and help out?

**Comment by rizsotto** [comment]
you can try out [scan-build](https://github.com/rizsotto/scan-build) `devel` branch has this feature now. will try to backport it to Bear on the weekend.

**Comment by rizsotto** [comment]
this shall be working now on `devel` branch.

**Comment by naseer** [comment]
Old issue, but has this made it into a release version of bear?

**Comment by rizsotto** [comment]
Yes, it should work. Give a try and please report if you have problem with it.

**Comment by naseer** [comment]
Looks like it works fine, thanks!

**Comment by naseer** [comment]
Bear version is bear 2.3.13
