### ISSUE TITLE
Make Bear work with 32-bit and 64-bit toolchains

### ISSUE THREAD

**Issue by deb0ch** [rizsotto/Bear#134]
Is there a way to make Bear work with both 32bit and 64bit binaries ?

I am on a 64bit system and use both 32bit and 64bit binaries.

We do cross compilation where I work, and for some projects the toolchain is compiled in 32bits (meaning the gcc executable will be 32bit), and for other projects it is 64bit.

The problem is that when my toolchain is 32bit, and even if I recompile `libear.so` in 32bit my build output will be polluted by messages like

`ERROR: ld.so: object '/usr/local/lib/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

from `ls.so` for all of the other programs used in the scripts (`grep`, `cp`, etc...), and I'm not even 100% sure that all the build has been correctly recorded.

Would there possibly a way to solve this issue ?

Is there a more convenient way of obtaining a 32bit `libear.so` than manually editing the `CMakeLists.txt` ?

**Comment by rizsotto** [comment]
hey Thomas, thanks for the ticket. recently many people found this as an issue. will try to fix it. (currently i'm traveling and have little time to code.)

**Comment by andrey-desman** [comment]
Building 64 & 32bit libraries:
Just create 2 directories to build in at any path you like (see CMake out of tree build)

# build 32-bit version
cd build32
cmake -DCMAKE_C_COMPILER_ARG1="-m32" -DCMAKE_CXX_COMPILER_ARG1="-m32" path/to/bear/source
make

# build 64-bit version
cd build64
cmake path/to/bear/source
make

As for the issue, it depends on the system you're running. If using Ubuntu 14.04, copy 32-bit library to /usr/lib/i386-linux-gnu/ then copy 64-bit library to /usr/lib/x86_64-linux-gnu/.
Execute bear this way:
bear -l libear.so make_cmd

Without absolute path to libear.so ld.so will search the library in proper place depending on whether binary is 32-bit or 64-bit.

**Comment by deb0ch** [comment]
It makes a lot of sense, I didnt think of it. Thank you very much ! :smile: 

While we're at it, does such a mechanism that does not require system-wide installation exist ?

**Comment by rizsotto** [comment]
thanks Andrey for the commands. As Thomas mentioned, the challenge here is to teach CMake to do all of these by itself and install it... i need to read more CMake docs.

**Comment by deb0ch** [comment]
To compile in 32bit on a 64bit system you need either a cross-compilation toolchain or a multilib compiler.

So to make this work, it will be required that either either the user has to install a multilib compiler, or the 32bit binaries should be shipped pre-compiled in the repo.

**Comment by rizsotto** [comment]
Thanks Thomas, I think the pre-compiled binaries against my taste. And presume if the user has problem with multilib compilation, he already has the multilib compiler. Do you know, is there any way you can detect that the compiler has multilib support?

**Comment by deb0ch** [comment]
> And presume if the user has problem with multilib compilation, he already has the multilib compiler. 

It is not related. The problem occurs when the binary of your compiler is a ELF32 binary but the programs of your system (e.g. grep, find, make...) are ELF64 binaries, independently of what the user is trying to compile. For instance, when I got the problem I was not compiling for x86 or x86_64 but for arm.

The origin of the problem is that a 64bit program cannot load 32bit dynamic libraries and a 32bit program cannot load a 64bit library.

AFAIK a multilib compiler is called this way because it embeds several libc (e.g. for x86 and x86_64) and hence supports multiple architectures.

The only way I know to detect that the compiler is multilib is to try to compile anything with `-m32` and see if it fails.

Multilib compilers for x86 and x86_64 can usually be found in package managers, like on ubuntu 16.04 64bit you can get it using `apt-get install gcc-multilib`. `update-alternatives` can be used to have several gcc versions cohabiting.

The only thing is, it can be tedious for the user especially without step-by-step instructions or for those who don't have access to the right compiler through their distribution, which is why I proposed pre-compiled binaries.

**Comment by nolange** [comment]
Hello,

I found another way to run bear with mixed binaries, without moving them into the system folder directly. If you preload '/usr/${LIB}/bear/libear.so', then ${LIB} will be replaced for each executeable by the relative library path to the architecture of the executable.
eg. lib/x86_64-linux-gnu or lib/i386-linux-gnu

The only issue is, that I am not sure if this functionality is relatively recent. I remember reading about those variables years ago, but always thought they were only valid in RPATH.

A simple test would be (will report if the library cant be found):
`LD_PRELOAD='/usr/${LIB}/bear/libear.so' /bin/true`

**Comment by nolange** [comment]
FYI, I patched the debian bear package to be able to handle "multiarch builds": https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856333

you can now install bear and additionally bear-lib:i386 on amd64, and everything just will work (other archs work in a similar fashion).

What would be nice to have upstream, is a CMake option to change the default PRELOAD path (I just made a quick patch). useful would be for example configuring it with
`cmake -DCMAKE_INSTALL_LIBDIR="lib/${DEB_HOST_MULTIARCH}/bear" -DBEAR_PRELOAD_LIBDIR="\${LIB}/bear" ...`

I am not fluent with CMake, so I dont know the nicest way =)

**Comment by rizsotto** [comment]
Thanks @nolange , will take a look at your fix. I would merge those parts which are not packaging related.

**Comment by nolange** [comment]
Hope you dont mind, I dint want to clone the repo for two lines:
[patch.txt](https://github.com/rizsotto/Bear/files/822686/patch.txt)

Feel free to change the variable name or the default.

**Comment by ruipires** [comment]
Any updates on this ?

I have the same issue. My machine is 64 bits, including some tools (make, for example), but I am using a 32-bit cross compiler.

I could not figure out a way to make it work, is there a known workaround?

I would be glad to help, if someone can give a few pointers on what to try.

**Comment by rizsotto** [comment]
Just made a new release yesterday. In the next one I'm targeting to fix #146 and this one.

Big help would be if someone describe me how to make a test environment for this. (I'm using Arch and Fedora distros, but can run docker for any other distro.) Would be really appreciate if someone can give me instruction how to set up multilib environment and provides an example open source project I can compile for testing.

What distro I need? A link to a page which has commands I can use to set up multilib things (libraies and compiler I guess)? A set of command I can verify that my setup compiles to 32bit? A set of command that compiles a relatively small open source project?

**Comment by nolange** [comment]
I can only describe how things (could) work in debian.
You have a package that contains bear and its library, this package has its depencies. Requiring to pull in 32bit libs on 64bit is usually a bad idea. So having a separate package for this would be ideal.

I made a patched debian package available here: https://github.com/nolange/bear-debpackage

means you "apt-get install dpkg-dev python debhelper" (and whatever else I missed), cd into the sources and run "dpkg-buildpackage -b".
You need to have separate environments for each architecture (I am using [sbuild chroots](https://wiki.debian.org/sbuild) for that), but it has the upside that this scheme would even work if you are on x86 and run an arm executable, aslong as the right bear-lib for arm is installed.

Troublesome is having to build for all these different archs, as soon as this change goes into debian, the build servers will take care of that.

These are the deb archives, compiled on debian stretch. Not sure if those work on older distributions.
[bear.zip](https://github.com/rizsotto/Bear/files/946813/bear.zip)

**Comment by rizsotto** [comment]
Thanks @nolange ! I will give another go to your patch on the weekend.

**Comment by rizsotto** [comment]
@nolange I'm trying to [reproduce](https://github.com/rizsotto/Bear/blob/multilib/.travis.yml) the trick you've done on travis-ci. Here is the [result](https://travis-ci.org/rizsotto/Bear/builds/224908813). Does not look good to me.

**Comment by nolange** [comment]
@rizsotto I know not a single thing about travis, but I am pretty sure you will need to use ${LIB} and  not $LIB.
eg. I am using
`
        default="/usr/${LIB}/bear/libear.so",
`
which expands to '/usr/lib/x86_64-linux-gnu/bear/libear.so' for example.

**Comment by rizsotto** [comment]
The [man page](http://manpages.ubuntu.com/manpages/xenial/man8/ld.so.8.html) says, `$LIB` and `${LIB}` is equal. And it expand well in case of `x86_64-linux-gnu`. (Travis-CI runs ubuntu 12.04 and 14.04.)

**Comment by rizsotto** [comment]
Thanks @deb0ch, @andrey-desman, @nolange! Now it works on my machine! ;) Could not make Travis-CI test pass with it. Updated the README file issues section how to.

**Comment by ashwina** [comment]
> path/to/bear/source


What is the meaning of " path/to/bear/source" ?

**Comment by rizsotto** [comment]
@ashwina good question. I was presume that the build directory and the source directory are not the same. That case the working directory is the build directory. And the commands need to know where are the sources. The "path/to/bear/source" refers the source directory

**Comment by ashwina** [comment]
@rizsotto  Thanks I got the point .

**Comment by fbs2016** [comment]
I also meet the err on Ubuntu 14.04 64bit, and try to build twice then copy 32-bit library to /usr/lib/i386-linux-gnu/ then copy 64-bit library to /usr/lib/x86_64-linux-gnu/ manually, is there any easy way to solve the problem?

**Comment by rizsotto** [comment]
@fbs2016 can you give more context? What is the problem?
This ticket (originally) was about how to build/use bear in a multilib environment. The `README.md` file contains a section which explain the build process. The ticket was spotting that debian (and derivatives like ubuntu) have different value for the `$LIB` value. Your case the `-DDEFAULT_PRELOAD_FILE='/usr/$LIB/libear.so'` seems to be a good choice.

**Comment by fbs2016** [comment]
@rizsotto  Thanks. I build the 2 librarys(32bit and 64 bit) and put them to the 2 folders, it works. But  the way "-DDEFAULT_PRELOAD_FILE=xxx" can't work. 
Another question, does it support Windows host?

**Comment by rizsotto** [comment]
No Windows support yet.
Can you explain what do you mean by the "`-DDEFAULT_PRELOAD_FILE=xxx` can't work"?
