### ISSUE TITLE
Add hook for custom compilation command

### ISSUE THREAD

**Issue by JakeFederico** [rizsotto/Bear#142]
I am using bear with an embedded system that has a custom compiler. The command line interface is compatible with gcc, but the executable has a different name. I've got it working by manually adding my compiler to the regex list in the main.py. I wondered if it would make sense to add a command line option to bear to provide a custom regex for identifying compilation commands?

**Comment by rizsotto** [comment]
thanks Jake for the report. sure we can add a command line argument for compiler names. i'm wondering does it have to be a regex or it could be a compiler name? also, if you use CC or CXX in your build, Bear could considered the values as compiler name. would that fit into your case?

**Comment by JakeFederico** [comment]
We use a pretty complex build system that invokes a few different compilers, so we don't use CC or CXX. Either a compiler name or a regex would work, but I thought a regex might work better as it would allow for more flexibility.

**Comment by rizsotto** [comment]
hi Jake, a late update on this. in my other project `scan-build` implemented this. in case if you want to try that out. will be port that solution to Bear in the new year.

**Comment by rizsotto** [comment]
This gonna be fixed in 2.3.0
