### ISSUE TITLE
inaccurate wording on SIP in readme

### ISSUE THREAD

**Issue by introom** [rizsotto/Bear#143]
In readme, it's said that scan-build will bypass the problem of SIP.

However, I tested, under el capitan, scan-build also need SIP turned off, otherwise the compile_flags.json would be empty.

**Comment by rizsotto** [comment]
thanks for the report. if you have problem with scan-build please report the bug in that issue tracker. and please read the scan-build readme file, what are the constraints of that tool. there are tests which checks compilation database generation and those also pass when SIP is enabled. (see logs like [this](https://travis-ci.org/rizsotto/scan-build/jobs/171601480#L35).) to my best knowledge the wording in the readme file is precise enough. (i'm not saying that the tool is perfect and it could not happen what you described. please open a ticket on scan-build, put details of your usage and i might be able to help.)
