### ISSUE TITLE
bear causes C stdlib headers to not be found

### ISSUE THREAD

**Issue by dgel** [rizsotto/Bear#144]
when running bear on a scons build that normally works fine, I get a fatal compilation error instead when also using bear. It seems that bear changed the include directories or system root somehow:

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:10: fatal error: 'wchar.h' file not found
    #include <wchar.h>  // for mbstate_t

Note that this also happens for C files when compiled with clang (and not clang++)

This can be replicated on my machine by compiling the following program:

```
#include <stdio.h>

int main() {
  puts("Hello world\n");
}
```

with `clang -o test test.c`, which works, and `bear clang -o test test.c` which fails with the fatal error:

```
test.c:2:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
```

**Comment by dgel** [comment]
closed as I found out running `xcode-select --install` fixes the issue.

**Comment by NikosEfthias** [comment]
@dgel `xcode-select --install` does not fix the problem unfortunately
<img width="620" alt="image" src="https://user-images.githubusercontent.com/9097437/49700898-6f28a600-fbfe-11e8-8e8a-fc054108559f.png">

**Comment by AtibaBryan** [comment]
I am currently experiencing this issue as well.

**Comment by rizsotto** [comment]
#215 looks similar to this problem.

**Comment by AtibaBryan** [comment]
https://github.com/rizsotto/Bear/issues/215#issuecomment-452481381
