### ISSUE TITLE
Bear fails when previous make process was interrupted

### ISSUE THREAD

**Issue by amosbird** [rizsotto/Bear#148]
```
make[1]: Nothing to be done for `clean'.
make[1]: Leaving directory `/home/amos/softwares/postgres/config'
rm -rf tmp_install/
bear: Internal error.
Traceback (most recent call last):
  File "/home/amos/bin/bear", line 123, in main
    return capture(args)
  File "/home/amos/bin/bear", line 195, in capture
    entries = post_processing(exec_traces)
  File "/home/amos/bin/bear", line 166, in post_processing
    previous = iter(json.load(handle))
  File "/home/amos/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/amos/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/amos/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/amos/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
bear: Please run this command again and turn on verbose mode (add '-vvvv' as argument).
```

This happens when building after a `ctrl-c` interrupted previous building process. Removing `compile_command.json` makes it work.

**Comment by rizsotto** [comment]
Thanks for the report. Could you provide the command you have been canceled and the one which you run afterwards? And please re-run it with `-vvvv` arguments to see more logs. Also, please mention what OS, which version do you use. Thanks!

**Comment by amosbird** [comment]
Hmm, this is not easy to reproduce. I'll post the full log when next time this error pops out. Thank you :smile:

**Comment by rizsotto** [comment]
From the stack trace it looks to me you were using `--append` or `-a` and that file was not a JSON file... Anyway, if it pops up again, please reopen this ticket.

**Comment by amosbird** [comment]
@rizsotto yeah, I suppose so. Maybe interrupting a building process sometimes leads to a broken JSON.
