### ISSUE TITLE
bear broken from last commit

### ISSUE THREAD

**Issue by rianquinn** [rizsotto/Bear#149]
This commit broke bear:
https://github.com/rizsotto/Bear/commit/5aba709f15fcef8bda3c4db3b4751c0076a274e6

I am getting this on all builds, including on Travis CI:
```
ERROR: ld.so: object '/usr/local//libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

The install location is:
```
/usr/local/lib/libear.so
```

Clearly it's missing 'lib'.

**Comment by rizsotto** [comment]
Thank you, will try to fix it soon.
