### ISSUE TITLE
Empty compilation database when compiling with JHBuild

### ISSUE THREAD

**Issue by mattiasb** [rizsotto/Bear#150]
Hi!

I'm a gnome developer and we usually build our stuff with a helper called [JHBuild](http://git.gnome.org/browse/jhbuild). I changed the make command in my `jhbuildrc` to `bear make` from just plain `make` and try to build some modules. All modules end up with empty compile_commands.json though (or specifically just an empty list `[]`).

When I add the `-n` flag to bear I get the following [compile_commands.json](https://gist.github.com/mattiasb/3d556900f73e74da2ab1d7cb2a5edfd2).

Any ideas?

**Comment by rizsotto** [comment]
Hi Mattias, thanks for the report. Bear intercepts process creation system calls. And from them it filters out those which are actual compilations. (When the compiler makes from source file to object file.) In the output you've provided there were no compilation. (Found one linking, but no compilation.) Therefore the empty list is the desired output.

**Comment by mattiasb** [comment]
Hm, yeah. I definitely see compilation output in the terminal, but I'm guessing my "bear make" thing doesn't propagate down in case of recursive make. Very likely an error on my end.

Thanks for your help!

**Comment by rizsotto** [comment]
bear shall intercept things even if that a recursive make call. It shall work even if one of the middle process reset the environment. (Scons does that.) Can you point me which project do you trying to build? And what would be the workflow to compile it (what dependencies it requires, any special thing to make JHBuild run, etc...)
