### ISSUE TITLE
Workaround for 'Empty compilation database on OS X Captain'

### ISSUE THREAD

**Issue by isotes** [rizsotto/Bear#152]
I've just ran into this issue (on macOS Sierra) and found - after some searching - that simply copying the `make` executable to a different (non-protected) directory works for me, i.e.,

```bash
cp `which make` .
bear ./make
```

From what I understand, the System Integrity Protection only applies to files in certain directories, e.g., `/usr`.

I think it would be helpful to add this to the README.

**Comment by rizsotto** [comment]
Wow, that's a great news! Thanks for the report. Can you give me some links that you found?

**Comment by isotes** [comment]
Well, I've stumbled around a lot ;) but the most relevant post I found was this:
https://apple.stackexchange.com/questions/215030/el-capitan-make-check-dyld-library-path/216815#216815

With the benefit of hindsight, both the Apple support page https://support.apple.com/en-us/HT204899 and the 'Functions' section of the wikipedia page https://en.wikipedia.org/wiki/System_Integrity_Protection point in this direction

Note: first I had tried to install and use the `make` homebrew package and that works as well (`bear gmake`)

**Comment by rizsotto** [comment]
Thank you! I've updated the readme with the Apple support link.

**Comment by xaviergmail** [comment]
Installing make through homebrew and running `bear gmake` worked wonders for me and is IMO cleaner than manually copying the make executable somewhere else. This also goes for any other build system. 
Thank you!
