### ISSUE TITLE
compiler option 'sysroot' incompatibility

### ISSUE THREAD

**Issue by niuys** [rizsotto/Bear#156]
Thanks for the good tool. 
We are working on a cross-compile project, and we use '--sysroot' option to assign sysroot dir for gcc, but clang use '-isysroot' instead.So I've to replace the option name in the result file every time.Is it better to do the replacement in bear, or in the Ycm?

**Comment by rizsotto** [comment]
Interesting problem you have. I don't think it's either Bear or Ycm shall do it. You can write a python script which does the replacement. Or could change the build script to use Clang with the right flags, therefore the output will be suitable for Ycm.

**Comment by niuys** [comment]
ok.Thanks
