### ISSUE TITLE
CMake Error at libear/CMakeLists.txt:35 (install):

### ISSUE THREAD

**Issue by Dimenus** [rizsotto/Bear#157]
Getting the following on both MSYS2 / Win32 CMAKE

> CMake Error at libear/CMakeLists.txt:35 (install):
  install Library TARGETS given no DESTINATION!

**Comment by rizsotto** [comment]
Hi, this program not supposed to run on Windows. Try my scan-build repo, that also has the functionality, but tested on Windows too.
