### ISSUE TITLE
empty compilation database with compiler in /usr/local

### ISSUE THREAD

**Issue by fcelda** [rizsotto/Bear#158]
I'm investigating why bear generates an empty compilation database on my macOS for a simple C program. SIP is enabled but the compiler resides in /usr/local where SIP shouldn't be in effect. I've read the README and I still don't understand why it doesn't work with plain compiler but works with compiler wrappers. I wonder if this could be an actual bug in Bear.

Check out this example:

```console
$ bear --version
bear 2.3.4
$ echo 'int main() { return 0; }' > main.c
$ which bear clang python zsh sh
/usr/local/bin/bear
/usr/local/opt/llvm/bin/clang
/usr/local/bin/python
/usr/local/bin/zsh
/bin/sh
$ bear -o plain.json clang -std=c11 ./main.c -o main
$ bear -o python.json python -c 'import sys; import os; os.execvp("clang", ["clang"] + sys.argv[1:])' -std=c11 ./main.c -o main
$ bear -o zsh.json zsh -c 'clang -std=c11 ./main.c -o main'
$ bear -o sh.json sh -c 'clang -std=c11 ./main.c -o main'
$ wc -c *.json
  2 plain.json
247 python.json
  2 sh.json
247 zsh.json
498 total
```

The compilation database is empty when invoking clang via /bin/sh (expected due to SIP) but also when invoking clang directly (unexpected). Any idea why this happens?

If this has reasonable explanation and it's not a bug, then it might be a nice feature to wrap the compiler invocation with something as simple as the python code above to workaround this problem.

**Comment by rizsotto** [comment]
Hi Jan, thanks for the report! Your investigation actually proofs that SIP does block selectively dynamic linker preloads as the documentation mentions. :) `/bin/sh` makes empty because of SIP. And calling the compiler directly is a not supported usage... There might be ways to fix that, but I am hesitant to put effort into it. Since writing a compilation database for a single compilation might be the same effort than calling with the tool. Not sure about the benefits are overweight the complexity of the solution. (Might change that in the future.)

**Comment by fcelda** [comment]
Oh, so you cannot run `bear cc` directly? That is what confused me.

Do you think it would be difficult to add support for that? I agree that it's not super useful. But it's quite handy for instance if I just want to try some code in a single .c file. Code completion in Vim is nice to have even for that. I usually spend more time finding out what is the format of compilation database than with coding.

If you think it makes sense, I will try to find some spare time and send you a PR.

**Comment by rizsotto** [comment]
I might need to document this in the man page or readme file. You are not the first confused user, sorry.

For one liner compilation like `bear cc test.c` your can write a shell script which execute the given command and you just echo the `pwd` and the argument into a JSON file. It would not require such complex things like dynamic linker preload functionality and SIP. It's really just a 10 line shell script and it works no matter what platform, SIP enabled or not... Bear is intended to cover more complex scenarios.

**Comment by fcelda** [comment]
Fair enough. Thank you!
