### ISSUE TITLE
output absolute rather than relative paths?

### ISSUE THREAD

**Issue by TTimo** [rizsotto/Bear#159]
Is there an easy way to make bear write out absolute directory and file paths rather than relative?

**Comment by rizsotto** [comment]
Yes, that was the default behavior in the previous releases. Did changed that, because newer Clang can recognize relative paths too. The intent was to make the generated output more portable... What is the problem you've found that caused by relative paths?

**Comment by TTimo** [comment]
Sourcetrail 0.12 is choking on the relative paths unfortunately. Although I agree that relative paths by default is generally better :)

**Comment by rizsotto** [comment]
Shall we open a ticket on Sourcetrail then? :) Might put back this functionality to bear with a switch. Although there should be one format for compilation database IMO.

**Comment by TTimo** [comment]
They will fix it in the next release (see https://github.com/CoatiSoftware/SourcetrailBugTracker/issues/388). In the meantime I can reprocess the JSON, but I thought it could be nice to have a switch in bear in the first place.

**Comment by rizsotto** [comment]
I would suggest to use a bit older version of Bear (2.2.1) which was producing files with absolute path. Hope you don't need to use it for long. :)

**Comment by TTimo** [comment]
Fair enough, thank you.

**Comment by FuexFollets** [comment]
What if there was an option to choose whether or not you wanted relative or absolute paths?
