### ISSUE TITLE
`bear_encode_json_string` chokes on zero-length strings

### ISSUE THREAD

**Issue by jaelsasser** [rizsotto/Bear#160]
I hit a weird bug while trying to get `bear` and `rtags` to play nicely with the linux kernel. The issue lies in `bear_encode_json_string` -- with a zero-length argument, the function incorrectly signals an error and results in the following message:

```
$ bear ./wrapper.sh "" hello_world.c
bear: writing json problem: Success
```

See below for the files necessary to reproduce.

---

**wrapper.sh**
```sh
#!/usr/bin/env sh
shift
gcc $@
```

**hello_world.c**
```c
#include<stdio.h>

int main(int argc, char *argv) {
    printf("Hello World\n");
}
```

**Comment by rizsotto** [comment]
Thanks Josh for the report. Will look at it next week.

**Comment by rizsotto** [comment]
Your test script is more elegant than mine! I've just re-read it now. :) Anyway, please reopen this issue if you still have the problem. And thanks for bring it up and suggest solution for it!
