### ISSUE TITLE
Fakeroot in makefile does not work

### ISSUE THREAD

**Issue by 99andreas** [rizsotto/Bear#162]
$ bear fakeroot  whoami
returns my user id and not 'root' as expected thus all fakeroot commands in my makefile will fail when running bear :-(

**Comment by rizsotto** [comment]
Thanks for the report. The `fakeroot` command uses the dynamic linker preload functionality -the same what Bear does- and that causes the problem. As in the README file I mentioned, Bear currently does not support such build tools.
I don't think it's a good idea to compile source codes as root user. The `fakeroot` call is usually happens when your script install the artifacts, so I guess it won't affect your compilation database content.
Might fix this later, but currently short of free time.

**Comment by YorkZ** [comment]
Supporting `fakeroot` is definitely useful while building an Ubuntu custom Linux kernel, where the following commands are used:
```
fakeroot debian/rules clean
fakeroot debian/rules binary-headers binary-generic binary-perarch
```
In this case, we need to be able to do:
```
fakeroot bear debian/rules clean
fakeroot bear debian/rules binary-headers binary-generic binary-perarch
```
or
```
bear fakeroot debian/rules clean
bear fakeroot debian/rules binary-headers binary-generic binary-perarch
```

**Comment by rizsotto** [comment]
There is a release candidate on master branch now, which suppose to fix this issue. Could you give it a try for that?

I'm closing this ticket now, but will re-open if the bug still there.

**Comment by YorkZ** [comment]
Glad to know this, thanks a lot @rizsotto, and I'll test it as soon as I got a chance. So should I do `bear fakeroot ...` or `fakeroot bear ...`?

**Comment by wberrier** [comment]
I went to go test this, but it failed to build on ubuntu 18.04:

```
-- Looking for _CS_GNU_LIBPTHREAD_VERSION - found
CMake Error at citnames/CMakeLists.txt:7 (target_link_libraries):                                      
  Object library target "citnames_json_a" may not link to anything.
                                                     
                                                     
-- Configuring incomplete, errors occurred!
See also "/tmp/tools/Bear/build/subprojects/Build/BearSource/CMakeFiles/CMakeOutput.log".                                                                                                                            
See also "/tmp/tools/Bear/build/subprojects/Build/BearSource/CMakeFiles/CMakeError.log".
CMakeFiles/BearSource.dir/build.make:112: recipe for target 'subprojects/Stamp/BearSource/BearSource-configure' failed
make[2]: *** [subprojects/Stamp/BearSource/BearSource-configure] Error 1
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/BearSource.dir/all' failed
make[1]: *** [CMakeFiles/BearSource.dir/all] Error 2
Makefile:151: recipe for target 'all' failed                                                                                                                                                                         
make: *** [all] Error 2                       
```

**Comment by rizsotto** [comment]
@YorkZ I think both tests are valid and shall return the same.
@wberrier let's track the build failure on a separate ticket.

**Comment by YorkZ** [comment]
@rizsotto I just tested with Bear 3.0.13 to build the Ubuntu 18.04 kernel 5.4.0 with the following command:
```
bear -- fakeroot debian/rules binary-headers binary-generic binary-perarch
```
the result is wonderful, a 152 M compile_commands.json was successfully produced. Thank you very much!
