### ISSUE TITLE
ERROR: ld.so: object [...] from LD_PRELOAD cannot be preloaded: ignored.

### ISSUE THREAD

**Issue by jayPare** [rizsotto/Bear#166]
I'm having issue getting Bear to work. First of all, I'm not root on the system I'm using, therefore, I used the `DESTDIR` flag when doing make install. It installed the `libear.so` at the specified space.

I also added the path to libear (`~/work/.local/usr/local/lib64/`) to `LD_LIBRARY_PATH` and set `LD_PRELOAD` to `~/work/.local/usr/local/lib64/libear.so`. I also added the `~/work/.local/usr/bin` to `PATH `to be able to see bear command everywhere.

But when I do my bear make, I'm getting this everywhere and my json fil is empty:

> ERROR: ld.so: object /usr/local/lib64/libear.so from LD_PRELOAD cannot be preloaded: ignored.

I tried to put the directory instead of the file itself in `LD_PRELOAD` ( `~/work/.local/usr/local/lib64/`), but when I do so, I also get those errors at the beginning on top of the preceding ones:

> ERROR: ld.so: object ~/work/.local/usr/local/lib64/libear.so from LD_PRELOAD cannot be preloaded: ignored.

I'm using SLES11 and like I said, I don't have root access.

**Comment by rizsotto** [comment]
Closing the issue, resolved on gitter.... For the record, the solution is to recompile/reinstall Bear. And pass `-DCMAKE_INSTALL_PREFIX=path-you-like` to `cmake`.

**Comment by jayPare** [comment]
I reinstalled Bear, but it still wasn't working. The only way I manage to get it work is to pass the path to libear.so to bear when using it. I do it like that:

> `bear -l <patch to libear.so including libear.so> make`

**Comment by rizsotto** [comment]
In order to help you I need more information. How did you installed Bear? (What were the commands you give?) And because it's a CMake project, you can help yourself with reading some of their docs too. ;)

Just test it on my machine, and it works without any problem.

```
# presume you are in the source dir
$ mkdir $HOME/tools
$ mkdir build; cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/tools
$ make install
$ export PATH=$PATH:$HOME/tools/bin
$ bear -h # check where it would search for the libear (-l switch)
```
