### ISSUE TITLE
Duplicate Entries in JSON

### ISSUE THREAD

**Issue by Macroft** [rizsotto/Bear#167]
Duplicate entries exist in my compile_commands.json. This is a problem because the clang-tidy will 'fix' things twice.

my guess is that this is happening because BEAR doesn't know how to handle libtool compiling everything twice (one for static and one for shared)

**Comment by rizsotto** [comment]
Thanks for the report! Can you hint me which project you are working on, what bear version you use, what OS, etc...

**Comment by yut23** [comment]
I have this issue on Arch Linux. In my case, it is caused by the "hardening-wrapper" package, which is now deprecated and can be safely removed. This fixes the duplicate entries. See https://lists.archlinux.org/pipermail/arch-commits/2017-July/411356.html.

**Comment by rizsotto** [comment]
Thanks Eric, glad that you don't have this problem anymore... Reading a bit of [libtool](https://www.gnu.org/software/libtool/manual/html_node/Creating-object-files.html#Creating-object-files) manual, to fix this issue will require more work.

**Comment by rizsotto** [comment]
Sorry for the late response... The recently released 2.4.3 version have a duplicate entry improvement.
I'm wondering if that fix this issue?

Will reopen if this is still happens.

**Comment by Macroft** [comment]
I can't remember which project I was working with when I found this, so I will not be able to confirm for you. Thank you for your work on a tool that is useful to a great many people.
