### ISSUE TITLE
Xubuntu mulitlib LD_PRELOAD Error

### ISSUE THREAD

**Issue by hofab** [rizsotto/Bear#169]
I am trying to get bear working in the multilib configuration, but I am still getting an error. I followed the README.
That is the information I got by reading [78](https://github.com/rizsotto/Bear/issues/78), [134](https://github.com/rizsotto/Bear/issues/134), and [130](https://github.com/rizsotto/Bear/issues/130).

```
sudo install -m 0644 libear.so /usr/lib/i386-linux-gnu/libear.so
sudo install -m 0644 libear.so /usr/lib/x86_64-linux-gnu/libear.so
sudo install -m 0555 ~/bear/build64/bear/bear /usr/local/bin/
```
```
ldd /usr/lib/i386-linux-gnu/libear.so  
linux-gate.so.1 =>  (0xf7764000)
libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf772f000)
libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7712000)
libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf755b000)
/lib/ld-linux.so.2 (0x56591000)

ldd /usr/lib/x86_64-linux-gnu/libear.so 
linux-vdso.so.1 =>  (0x00007fff6f29f000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f754ffd6000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f754fdb9000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f754f9ee000)
/lib64/ld-linux-x86-64.so.2 (0x000055c6f9a8a000)
```
```
bear -h                      Mon 26 Jun 2017 11:17:14 AM EDT
usage: bear [-h] [--version] [--verbose] [--cdb <file>] [--use-cc <path>]
            [--use-c++ <path>] [--append] [--libear LIBEAR]
            ...

positional arguments:
  build                 Command to run.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --verbose, -v         Enable verbose output from 'bear'. A second, third and
                        fourth flags increases verbosity. (default: 0)
  --cdb <file>, -o <file>
                        The JSON compilation database. (default:
                        compile_commands.json)
  --use-cc <path>       Hint 'bear' to classify the given program name as C
                        compiler. (default: cc)
  --use-c++ <path>      Hint 'bear' to classify the given program name as C++
                        compiler. (default: c++)

advanced options:
  --append, -a          Extend existing compilation database with new entries.
                        Duplicate entries are detected and not present in the
                        final output. The output is not continuously updated,
                        it's done when the build command finished. (default:
                        False)
  --libear LIBEAR, -l LIBEAR
                        specify libear file location. (default:
                        /usr/lib/$LIB/libear.so)
```

```
bear make                    Mon 26 Jun 2017 07:40:38 AM EDT
ERROR: ld.so: object '/usr/lib/$LIB/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

I appreciate every hint into the right direction.

**Comment by rizsotto** [comment]
Thanks for the report. The `libear.so` install looks good, but `bear` should print `/usr/$LIB/libear.so`.

**Comment by hofab** [comment]
I was under the assumption, that bear should use the string defined with 
`cmake .. -DCMAKE_C_COMPILER_ARG1="-m64" -DDEFAULT_PRELOAD_FILE='/usr/lib/$LIB/libear.so'`
So I would expect /usr/lib/$LIB/libear.so
On a site note, the following command seems not to overwrite the default.
`bear -l/usr/$LIB/libear.so make
ERROR: ld.so: object '/usr/lib/$LIB/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
I am going to try this command just in case.
`cmake .. -DCMAKE_C_COMPILER_ARG1="-m64" -DDEFAULT_PRELOAD_FILE='/usr/lib/$LIB/libear.so'`

**Comment by hofab** [comment]
`cmake .. -DCMAKE_C_COMPILER_ARG1="-m64" -DDEFAULT_PRELOAD_FILE='/usr/$LIB/libear.so'

Solved the issue, must have misunderstood the library finding path behavior. Works great now, fantastic job.

**Comment by qi77wang** [comment]
hello, i meet similar question, could you give me some suggestions?
  i want make linux code.
  like this:
    source build/envsetup.sh
    lunch xxx
    bear make

error:
    ERROR: ld.so: object '/opt/bear/$LIB/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by qi77wang** [comment]
I have tried like this, but It doesn't seem to work.

(cd ~/build32; cmake "$BEAR_SOURCE_DIR" -DCMAKE_C_COMPILER_ARG1="-m32"; VERBOSE=1 make all;)
(cd ~/build64; cmake "$BEAR_SOURCE_DIR" -DCMAKE_C_COMPILER_ARG1="-m64" -DDEFAULT_PRELOAD_FILE='/opt/bear/$LIB/libear.so'; VERBOSE=1 make all;)
sudo install -m 0644 ~/build32/libear/libear.so /opt/bear/lib/libear.so
sudo install -m 0644 ~/build64/libear/libear.so /opt/bear/lib64/libear.so
sudo install -m 0555 ~/build64/bear/bear" /opt/bear/bin/bear
