### ISSUE TITLE
Unable to build bear with glibc 2.26+

### ISSUE THREAD

**Issue by ffuugoo** [rizsotto/Bear#176]
I'm using Arch Linux and I'm unable to build bear, ATM, due to xlocale.h (used in libear/ear.c) being removed in recent glibc update (2.26 to be exact).

Quoting from [glibc 2.26 release notes](https://sourceware.org/ml/libc-alpha/2017-08/msg00010.html):

> The nonstandard header <xlocale.h> has been removed.  Most programs should
  use <locale.h> instead.  If you have a specific need for the definition of
  locale_t with no other declarations, please contact
  libc-alpha@sourceware.org and explain.

**Comment by ffuugoo** [comment]
I've checked that bear builds correctly without inclusion of xlocale.h (it may not be ultimately true, though; I believe you've added this include _for reasons_) and [opened a pull-request removing it from ear.c](https://github.com/rizsotto/Bear/pull/177).

**Comment by rizsotto** [comment]
Thanks for the report. I made a fix on the branch `ear`. Will release it next week just waiting some more feedback about other bug fixes.
