### ISSUE TITLE
Execution trace file parsing problem shall not cause lost of full execution history

### ISSUE THREAD

**Issue by rizsotto** [rizsotto/Bear#181]
From Tim:
> I've had a lot of misfires losing the command log directory because a handful of logs failed to parse or some other problem. Particularly annoying when a full run with 4k files takes ~45 minutes and it's entirely lost..

**Comment by rizsotto** [comment]
Hey @TTimo, could you comment on this issue? How did Bear lost the execution history?

Bear currently supports compilation database extension via `--append` flag. So if you run your build and it fails, you can append to the existing compilation database if you were able to fix the build. Is this not covering the scenario what you've experienced?

**Comment by TTimo** [comment]
If bear fails to produce a compilation database, the binary was still fully compiled and linked.

Executing again will not capture any new compile commands, or at best it will capture some remaining compile commands but it will be incomplete. The only option is to 'make clean' or the equivalent and start again waiting 45 minutes.

So this is why I made agressive changes to my tree to make sure a set of captured compiled commands is never lost when errors happen.

**Comment by rizsotto** [comment]
Thanks for the explanation! Although I have concerns about this. The case you describe is a bug in Bear, and I think we shall rise that issue and fix it. Would not make change that prepares for programming erros. And also not sure how leaving the execution traces persist in some directory would help. (Would there also be a separate step when you can build the compilation database from the traces?) It might be problematic that the tool leaves not expected files behind.
