### ISSUE TITLE
bear crash with xmake

### ISSUE THREAD

**Issue by 101Leon** [rizsotto/Bear#184]
bear -vvvv xmake -j 4 CONFIG=xxx
bear: DEBUG: parse_args_for_intercept_build: Raw arguments ['/usr/local/bin/bear', '-vvvv', 'xmake', '-j', '4', 'CONFIG=1t1s8ch_1l1s8ch_TDM_DSP4']
bear: DEBUG: parse_args_for_intercept_build: Parsed arguments: Namespace(append=False, build=['xmake', '-j', '4', 'CONFIG=xxx'], cc='cc', cdb='compile_commands.json', cxx='c++', libear='/usr/local/lib/x86_64-linux-gnu/libear.so', verbose=4)
bear: DEBUG: run_build: run build ['xmake', '-j', '4', 'CONFIG=1t1s8ch_1l1s8ch_TDM_DSP4'], in environment: {'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/leon', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'INTERCEPT_BUILD_TARGET_DIR': '/tmp/intercept-LHXmtJ', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'XDG_VTNR': '7', 'DISPLAY': ':0.0', 'LANG': 'en_ZA.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'LANGUAGE': 'en_ZA:en', 'SHLVL': '1', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'CLUTTER_IM_MODULE': 'xim', 'TEXTDOMAIN': 'im-config', 'JOB': 'dbus', 'WINDOWID': '62959694', 'SESSIONTYPE': 'gnome-session', 'XMODIFIERS': '@im=none', 'QT4_IM_MODULE': 'xim', 'SELINUX_INIT': 'YES', 'XDG_RUNTIME_DIR': '/run/user/1000', 'GTK_IM_MODULE': 'xim', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'COMPIZ_BIN_PATH': '/usr/bin/', 'VTE_VERSION': '3409', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'TEXTDOMAINDIR': '/usr/share/locale/', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'XDG_CURRENT_DESKTOP': 'Unity', 'XDG_SESSION_ID': 'c1',  '_': '/usr/local/bin/bear', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'LD_PRELOAD': '/usr/local/lib/x86_64-linux-gnu/libear.so', 'SESSION': 'ubuntu', 'DESKTOP_SESSION': 'ubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/2342', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'GNOME_KEYRING_PID': '2674', 'GDM_LANG': 'en_US', 'GTK_MODULES': 'overlay-scrollbar:unity-gtk-module', 'INSTANCE': '', 'XDG_SEAT': 'seat0'}
bear: ERROR: wrapper: Internal error.
Traceback (most recent call last):
  File "/usr/local/bin/bear", line 134, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/bin/bear", line 182, in intercept_build
    exit_code, current = capture(args)
  File "/usr/local/bin/bear", line 205, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/local/bin/bear", line 592, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
bear: ERROR: wrapper: Please report this bug and attach the output to the bug report

This was encountered when using bear on an xmos project. You can find the project and tools here:
https://www.xmos.com/published/an01032-100mbit-ethernet-avb-endpoint-example-using-i2s-master-sw?version=latest
https://www.xmos.com/support/tools
Some identifying info was removed from the environment variables.

**Comment by rizsotto** [comment]
Thanks for the report. I have not tried to run Bear against this project, but have seen similar stack traces. It usually happens if the command after Bear is wrong. (The python call is cimplaining that there is no such file or directory.) Is the command `xmake -j 4 CONFIG=1t1s8ch_1l1s8ch_TDM_DSP4` works without Bear?

**Comment by 101Leon** [comment]
Thanks for the feedback. I realised I forgot to set the environment correctly so the command wasn't available. I set the environment correctly and then it ran without crashing. Perhaps the error message can be improved slightly for this case.

After running bear xmake... with the correct environment the compilation database consists of just '[]'. I performed a make clean before this. This is a non-standard build system, but it would be useful to obtain the compilation database. Please let me know if you decide to look into this.

**Comment by rizsotto** [comment]
Thanks to come back. I'm happy that at least the crash is not an issue. ;) About the empty result, I myself would not invest time into this toolset. But happy to help if you want to dig down and fix it. (As a start of that could be to send the output of `bear -vvvv ...` command. But instead of copy-paste it, you can attach file to the report.) If you think we can fix this together, please reopen the ticket.
