### ISSUE TITLE
Compiler calls cc1plus

### ISSUE THREAD

**Issue by CogPy** [rizsotto/Bear#186]
The compiler we're using for a ESP32 project, somehow calls the `cc1plus` directly as shown (content truncated because reasons)

```
bear: DEBUG: input was: ['(...) /xtensa-esp32-elf-new/bin/../libexec/gcc/xtensa-esp32-elf/5.2.0/cc1plus', '-quiet', '-I', 'inc', '-I', (...) 
```

The simple solution is to add a cc1plus compiler regexp at around line 100. Does that have any side-effects? It works great as a work-around/hack.

```python
 # Known C++ compiler executable name patterns
 COMPILER_PATTERNS_CXX = frozenset([
     re.compile(r'^(c\+\+|cxx|CC)$'),
     re.compile(r'^([^-]*-)*[mg]\+\+(-\d+(\.\d+){0,2})?$'),
     re.compile(r'^([^-]*-)*clang\+\+(-\d+(\.\d+){0,2})?$'),
     re.compile(r'^(icpc|mpiCC|mpicxx|mpic\+\+)$'),
     re.compile(r'^(cc1plus)$'),
     re.compile(r'^(g|)xl(C|c\+\+)$'),
 ])
```

**Comment by rizsotto** [comment]
Sure, you can put the `cc1plus` into the recognised compiler list or just pass `--use-cc cc1plus` flag to Bear. Although the `cc1plus` is not real compiler in a sense that the compiler flags are usually not the same as the compiler you call from the build system. Creating compilation database from those calls might not be good for Clang tools. (Don't have expeience, never tried that, but looks suspicios.)
