### ISSUE TITLE
newlocale: No such file or directory (Re-open Issue#182?)

### ISSUE THREAD

**Issue by timblaktu** [rizsotto/Bear#190]
I'm still having problems with issue#182 which was closed as fixed. I'm on Debian Jessie 8.7(using en_US.UTF-8), GNU Make 4.0, running Bear built from the 2.3.9 tag. Since this tag/release was 15 days ago and that issue was fixed on same day, I originally ASSumed the fix was included in that release.

To verify, I then checked out, built and installed _master_, and re-built my source code (with make, which I've simply aliased in .profile to _bear make_.. let me know if there's a better best practice for this), and...

I am still getting the same newlocale error:

`libear: (/usr/local/src/Bear/libear/ear.c:200) newlocale: No such file or directory`

 These are my locale settings:

```
/usr/local/src/Bear > locale -a                                                         master
C
C.UTF-8
en_US.utf8
POSIX
/usr/local/src/Bear > locale                                                            master
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I tried to change my locale to C.UTF-8 (as @sebastinas suggests), just locally in my shell before invoking make, like so:

`export LANG=C.UTF-8; export LC_CTYPE=C.UTF-8; make mytarget`

and I'm still getting the same error, even though in the same shell I see:

```
/home/tblack/SourceRAM/la > export LANG=C.UTF-8; export LC_CTYPE=C.UTF-8
/home/tblack/SourceRAM/la > locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE=C.UTF-8
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

I just wanted to let you know that I was still encountering this issue, and also to seek help for getting past it. Thank you.

**Comment by rizsotto** [comment]
Thank @timblaktu for the report. I can confirm that the 2.3.9 version shall have the fix for #182 .

To fix the problem I might need more help from you. I need to reproduce the issue locally. (Created functional tests against this, which pass on fedora, arch and on travis-ci too.) Is the project is open source you try to build?

**Comment by timblaktu** [comment]
@rizsotto Unfortunately my project is not open, but in time I can try to create a sharable sub-project that exhibits this problem. Until then, here is I think a good clue: 

The problem appears to be happening during the earlier stages of our build, where make is being used to run omniidl (with python backend) to generate .cpp/.h/.py outputs from .idl inputs. Can you think of any assumptions in Bear that would break down when gnu make is invoked in this way (i.e. when make is NOT starting gcc processes but instead is starting omniidl processes (which in turn spawn backend python processes))? So, I suspect there's something unexpected in the locale of either the source files being generated by make, or perhaps the .py backends that are being executed. 

One thing I thought of is... we are not specifying an encoding in any of our python source code, neither the manually written ones nor the generated ones, as [described in PEP-263](https://www.python.org/dev/peps/pep-0263/). Perhaps we should? Before I do anything though, I'd like to get an understanding of exactly what is going wrong from the Bear perspective. So far, all I know is that libear is failing to create a new locale in mt_safe_on_load() (/usr/local/src/Bear/libear/ear.c#198), but I don't yet know what this means.

Eventually though today, I was patient enough to ignore all the locale errors, long enough to let our "build everything" make target finish building. Despite the locale errors the build was successful, and I noticed that it created an 85MB compile_commands.json file at project root. So I will move forward with trying to use this. The reason I'm even here is that I'm testing the feasibility of using Bear to generate compilation database to inform Vim's You Complete Me plugin for IDE purposes. Thank you.

**Comment by rizsotto** [comment]
Thanks for explaining. Then I think this is similar to #185 , where the encoding of the process (which calls an exec) is not match with what the locale is shows. (Described better in the bug report.) I have not figured out a good solution for that.

**Comment by 3v1n0** [comment]
I'm also getting this when trying to run a script from a vscode which launches a script inside an ubuntu schroot (so with minimal installation).

The locale in the integrated shell is set as

```bash
LANG=en_US.UTF-8
LANGUAGE=it_IT
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

While in the schroot the situation is
```bash
locale -a
C
C.UTF-8
it_IT.utf8
POSIX
```

So setting `LC_ALL=C.UTF-8` in my script fixed it or, otherwise in vscode settings

```json
"terminal.integrated.env.linux": {
        "LC_ALL": "C.UTF-8"
    },
```

**Comment by rizsotto** [comment]
Thanks for the report. I'm re-working Bear to fix multiple issues (this one is included). It will take some longer time... I'm happy that you could have worked around and published your fix here.

**Comment by caohaiming** [comment]
Hi @rizsotto ,  i see the error can also be reported when compile a cross compile projec, then i write a pretty simple C file, when type "bear make" command to compile it using GCC, its OK, when set the compiler to arm-linux-gcc, then the error listed can also be reported.

**Comment by rizsotto** [comment]
Thanks @caohaiming , noted your finding. Will try to add test on the new version with this scenario.

**Comment by rbresalier** [comment]
I also encountered this issue and was able to get around it by changing the call to newlocale() to use "C" as middle parameter:

```
utf_locale = newlocale(LC_CTYPE_MASK, "C", (locale_t)0);
```

Perhaps it would be useful to add an option to bear to indicate to use "C" instead of "" ? Then if "C" locale is acceptable to users it can be a way to work-around the issue.

**Comment by rizsotto** [comment]
@rbresalier did try this idea on a branch, but that breaks existing test cases.

**Comment by rbresalier** [comment]
It probably broke cases with international characters - I think I saw Hebrew in your failed test case?

In my situation I don't have any special characters. This is probably true for most users.

That is why I'm thinking you could add this as a non-default option? Then users can use it at their own risk. Maybe it could also be checked which test cases it failed and make sure it is only the ones with international characters.

**Comment by rizsotto** [comment]
Sounds good to make this one as default. But I'm still hesitate to change code and (conditionally) disable a test, without adding a new test to it... And I'm not sure how easy is to test this problem. If we could come up with a test idea I'm in to any solution. :)

**Comment by rbresalier** [comment]
If you make "C" the default and a new command line option for "", then maybe you can run the tests that fail with "C" with the new option to run with "" instead? So that one chooses the new option with "" if they really need international characters. Then most test cases run with "C" and the ones that fail with "C" you run with "" instead?

**Comment by rbresalier** [comment]
Then again, a drawback to making "C" the default is that it could break folks who are using the tool now with international characters. Maybe "C" is better as not default? But don't know how many users really have unicode characters in their compilation command lines.

**Comment by rizsotto** [comment]
As I said earlier, I think it's a good idea to make the `"C"` be the default. My problem is how to validate that it works correctly? If you have an idea how to make a test case which breaks the existing version and see the change in the code fix the test that would be a big help for me.

**Comment by rbresalier** [comment]
Perhaps if you set the LC_ALL or LANG environment variables to an invalid value it can break your existing test cases? Then you can get similar error messages that are seen in the report of this issue.

**Comment by rizsotto** [comment]
Latest master might have a fix for this. (version 2.4.0)

The libray is no longer try to encode the strings into JSON, so the `newlocale` call is no longer there. It handled by the Python executable instead, which has less constraints on memory allocation or error handling... It's a first rought implementation, so might not cover all cases. Happy to hear some feedback how this working for you guys.

**Comment by rbresalier** [comment]
Thanks! I'm testing it out now, our build process is very very long, so it is ongoing. I'll let you know.

I ran main.py.in through pylint on Python 2.7 and am getting new warning for this line:

```
def parse_length(handler, type):
```

Warning says: 
```
[W0622(redefined-builtin), parse_exec_trace.parse_length] Redefining built-in 'type'
```

So maybe want to choose a different name than 'type'?

Also get many pylint warnings for things like:

```
class Category:
```

that state:

```
[C1001(old-style-class), Category] Old-style class defined.
```
which I get rid of by doing:

```
class Category(object):
```

I think using (object) is still valid in Python 3.

May want to do a round of cleaning up of some main pylint warnings. I'm experimenting with using a fifo/pipe instead of temp files and I like to run through pylint to catch my typos.

Perhaps we should open a different issue for Pylint warnings?

**Comment by rbresalier** [comment]
My tests of version 2.4.0 of Bear look very good, I'm no longer getting the error "newlocale: No such file or directory" with the compiler that caused it before. The compile_commands.json also look good visually. Well done @rizsotto !

**Comment by rizsotto** [comment]
Thanks @rbresalier for the review. Will apply these changes shortly.
