### ISSUE TITLE
Resolvin MPI compiler wrappers still broken

### ISSUE THREAD

**Issue by JoZie** [rizsotto/Bear#195]
Resolving the flags for the MPI compiler wrappers is still an issue on the master branch and for the latest releases. I know that the issue is already fixed in the charsetfix branch but it would be nice to have a fixed version.
Thank you!

**Comment by rizsotto** [comment]
Thanks @JoZie . Will merge it this week. (Just for curiosity: did you run the `charsetfix` branch and the fix was working for you?)

**Comment by JoZie** [comment]
@rizsotto Yes, I'm running the `charsetfix` branch and it's working for me. However the MPI problem was the only one I had with Bear so far. Keep up the great work!  :thumbsup:

**Comment by rizsotto** [comment]
Thanks @JoZie , now it's merged to master.
