### ISSUE TITLE
downstream package naming

### ISSUE THREAD

**Issue by morxa** [rizsotto/Bear#198]
I'm currently preparing Bear as a Fedora package. Unfortunately, the name bear is already taken in Fedora. I'm not sure which alternative is the best. My suggestions:
* clang-bear
* build-ear
* libear

What do you think would be the best package name?

Thanks for your suggestion.

**Comment by rizsotto** [comment]
Good question. I would not put Clang into the name, because it's not part of any LLVM projects. BuildEAR could be a good one I think. (But originally wanted to avoid names which contains the functionality of it.) And libear is just an implementation detail and not the project itself... So those were my two cents.

**Comment by rizsotto** [comment]
Hey @morxa , for curiosity what name you've choose? Also a question can we close this ticket?

**Comment by morxa** [comment]
Hey, I will ask for a renaming of the current bear in Fedora, so we can actually have bear as the Fedora name for this package. I just haven't had the time to get this started. I'll keep you updated.

**Comment by morxa** [comment]
FYI: I filed https://bugzilla.redhat.com/show_bug.cgi?id=1539207

**Comment by rizsotto** [comment]
Thanks @morxa

**Comment by D4N** [comment]
@rizsotto I have packaged Bear for Fedora and it is currently in review (see: https://bugzilla.redhat.com/show_bug.cgi?id=1565848). The name clash with the bear game engine is currently blocking it.

Would it be ok with you if I name your package `build-ear`?

**Comment by rizsotto** [comment]
Thanks to come back with this. I am absolutely fine with the name `build-ear`.
