### ISSUE TITLE
No headers files in compile_commands.json

### ISSUE THREAD

**Issue by LKlemens** [rizsotto/Bear#204]
Hi All,
Is there some way to generate compile_commands.json with header files? 
I have cpp project based on makefiles. (I cannot change it ;/)

**Comment by rizsotto** [comment]
Hey @LKlemens , sure it would not be a big change to support header files too. But I would like to understand the problem first. Originally the compilation database was contains only compiler calls which compiles (not linking, not preprocessing). Over time this changed in Clang, but would like to see a use case where header files are desired in the output. Is the project you working on is open source? Or could you give details about the problem?

**Comment by LKlemens** [comment]
Hi @rizsotto,
I use vim for programming and plugins like [Ale](https://github.com/w0rp/ale#faq-c-configuration), [RTags](https://github.com/Andersbakken/rtags). These plugins use compile_commands.json file to do their job (find references, virtual fun, definitions, renaming, code completion, code checking etc.), and it works well in cpp files, but in hpp stops working due to lack of instruction how to compile that header files ;/
That's why I am asking for headers file in compile_commands.json :P 
Thanks in advance!

**Comment by rizsotto** [comment]
Thanks to come back with the answer. I don't use these tools myself, and I can't do the the experiment by myself. Could you add those header files yourself and see that the tools are working well? Just a quick test to confirm that this is really desirable... The other question would be, what do you think how Bear can put the header files into the compilation database? If there is a compiler call where the header file is present as a source file, that could be easy. But if the header file was included via cpp file, that's not what Bear can detect.

**Comment by Sarcasm** [comment]
Just for a shamelsss plug (again), this is the main and only feature of [compdb](https://github.com/Sarcasm/compdb) today:

- https://github.com/Sarcasm/compdb#generate-a-compilation-database-with-header-files

However, RTags is supposed to have even better knowledge of this, as it really index the code, so I'm not sure RTags needs this.

**Comment by rizsotto** [comment]
Thanks Guillaume! Is that working for you @LKlemens ?

**Comment by LKlemens** [comment]
@Sarcasm Thanks for compdb! 
ALE started to work with hpp instructions. 
Indeed RTags indexing works well, but code completion in hpp files doesn't want to, even with hpp instructions;/ I've asked on RTags repo, maybe someone had similar problem. 
@rizsotto Sorry for bothering you, and thank you for your involvement!

**Comment by real-or-random** [comment]
I use YouCompleteMe on vim, and also there header files will be very useful. I can of course use bear and then compdb but I still think that header files are a useful thing to have in bear (without the need for comdb).

**Comment by realnc** [comment]
Would it be possible to add header files in the json output directly in bear? compdb doesn't work, unfortunately, since it generates wrong compiler flags. It takes this:

```none
"-DGIT_VERSION=\"9c90bc5c\"",
```

and transforms it into this:

```none
-DGIT_VERSION=\\\"9c90bc5c\\\"
```

which just breaks stuff.

**Comment by rizsotto** [comment]
@realnc this is an interesting use case... Bear currently does not do this. I would need to know more about how to generate the entries for the header files.

@Sarcasm is there something I can help with the Sarcasm/compdb#19 to be fixed?

**Comment by Sarcasm** [comment]
I don't think `compdb` is incorrect, it could just be an issue with incorrect shell command parsing from the tool @realnc uses.
The escaping performed by compdb is on purpose, because JSON compilation database `command`  is a shell command in a JSON string.
`compdb` outputs entries with the `command` key, not `arguments`, so it's normal that there is a difference in escaping between `compdb` and `bear`.
If the tool correctly parses `command` using something like Python `shlex.split()` it should be ok.

Confusingly, I think the official JSON Compilation Database documentation example is wrong:

> Example:
> ```
> [
>  { "directory": "/home/user/llvm/build",
>    "command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
>    "file": "file.cc" },
>  ...
> ]
> ```
> -- https://clang.llvm.org/docs/JSONCompilationDatabase.html

But from what I remember, tools producing `command` where mostly correct, and libclang JSON parsing was too.

```
/usr/bin/clang++ -Irelative -DSOMEDEF="With spaces, quotes and \-es." -c -o file.o file.cc
```

@realnc: Is it possible to have the full JSON entry for the main source file from `bear`, and the corresponding JSON entry file for the header file from `compdb`?

Example of parsing your 2 GIT_VERSION examples:

```
$ tail -n +1 /tmp/print_args.py /tmp/command.json 
==> /tmp/print_args.py <==
#!/usr/bin/env python
import json
import shlex
import sys

with open(sys.argv[1]) as fp:
    data = json.load(fp)

for i, entry in enumerate(data):
    if i != 0:
        print("")
    arguments = shlex.split(entry["command"], posix=True)
    for argument in arguments:
        print(argument)

==> /tmp/command.json <==
[
 { "directory": "/home/user/llvm/build",
   "command": "clang++ -DGIT_VERSION=\"9c90bc5c\"",
   "file": "foo.cc"
 },
 { "directory": "/home/user/llvm/build",
   "command": "clang++ -DGIT_VERSION=\\\"9c90bc5c\\\"",
   "file": "bar.cc"
 }
]
$ python /tmp/print_args.py /tmp/command.json
clang++
-DGIT_VERSION=9c90bc5c

clang++
-DGIT_VERSION="9c90bc5c"
```

**Comment by rizsotto** [comment]
Thanks @Sarcasm for your response. I think you are right about the `command` field content. It has to be a shell escaped string. And because it's in a JSON string, it will need another escaping... Therefore the `$ cc ... -DGIT_VERSION="9c90bc5c" ...` command will end up `"cc ... -DGIT_VERSION=\\\"9c90bc5c\\\" ..."` in the `command` field.

When Bear's default output was the `command` field, every second month a new issue was opened on this project. As you pointed out the JSON compilation database definition has broken example. And maybe because of that, or maybe the wrong wording of that definition, but tools are interpret that field differently. So, users are opening issues on each tools because things does not work for them.

I highly recommend to use the `arguments` filed in the output JSON file. The `arguments` field is there for many years now. (I did check it a while ago and concluded that it's safe to presume that tools today will understand that format.)

**Comment by Sarcasm** [comment]
Agreed, compdb should use `arguments` now.

**Comment by realnc** [comment]
> @realnc: Is it possible to have the full JSON entry for the main source file from `bear`, and the corresponding JSON entry file for the header file from `compdb`?

@Sarcasm 
Sure, here they are.

### Bear

```json
  {
    "arguments": [
      "/usr/bin/c++",
      "-std=gnu++17",
      "-Wno-register",
      "-DFMT_HEADER_ONLY",
      "-D__LIBRETRO__",
      "-fPIC",
      "-I../src",
      "-I../libretro",
      "-I../libretro/virtual_keyboard",
      "-I../libretro/deps/common/include",
      "-I../include",
      "-I../libretro/munt_build/include",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/munt_build/include",
      "-Ideps/fmt/include",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/libinstpatch-2",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/glib-2.0",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/lib/glib-2.0/include",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/opus",
      "-DGIT_VERSION=\"deece494\"",
      "-DSVN_VERSION=\"r4465\"",
      "-DHAVE_ALSA",
      "-DC_HAVE_MPROTECT=1",
      "-DUNIX_PORTABLE",
      "-O0",
      "-g",
      "-I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/SDL",
      "-D_GNU_SOURCE=1",
      "-D_REENTRANT",
      "-DC_IPX",
      "-DWITH_VOODOO=1",
      "-DWITH_FLUIDSYNTH",
      "-DC_DYNAMIC_X86=1",
      "-DC_TARGETCPU=X86_64",
      "-DWITH_BASSMIDI=1",
      "-c",
      "-o",
      "../libretro/libretro.o",
      "../libretro/libretro.cpp"
    ],
    "directory": "/mnt/Data/projects/dosbox-core/libretro",
    "file": "/mnt/Data/projects/dosbox-core/libretro/../libretro/libretro.cpp",
    "output": "/mnt/Data/projects/dosbox-core/libretro/../libretro/libretro.o"
  }
```

### compdb
```json
{
  "directory": "/mnt/Data/projects/dosbox-core/libretro",
  "command": "/usr/bin/c++ -std=gnu++17 -Wno-register -DFMT_HEADER_ONLY -D__LIBRETRO__ -fPIC -I../src -I../libretro -I../libretro/virtual_keyboard -I../libretro/deps/common/include -I../include -I../libretro/munt_build/include -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/munt_build/include -Ideps/fmt/include -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/libinstpatch-2 -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/glib-2.0 -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/lib/glib-2.0/include -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/opus -DGIT_VERSION=\\\"deece494\\\" -DSVN_VERSION=\\\"r4465\\\" -DHAVE_ALSA -DC_HAVE_MPROTECT=1 -DUNIX_PORTABLE -O0 -g -I/mnt/Data/projects/dosbox-core/libretro/deps_bin/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DC_IPX -DWITH_VOODOO=1 -DWITH_FLUIDSYNTH -DC_DYNAMIC_X86=1 -DC_TARGETCPU=X86_64 -DWITH_BASSMIDI=1 -c /mnt/Data/projects/dosbox-core/libretro/deps/common/include/libretro.h",
  "file": "/mnt/Data/projects/dosbox-core/libretro/deps/common/include/libretro.h"
}
```
