### ISSUE TITLE
Possible to capture linker commands (CCLD)?

### ISSUE THREAD

**Issue by greencat3** [rizsotto/Bear#205]
I was trying to build a project and make bear capture the linker commands as well. I commented out the ignored Linker options but looks like my project is using CCLD invocations to invoke linker. Is there any easy way I can modify bear to capture CCLD invocations also?

**Comment by rizsotto** [comment]
Thanks for the report. Could you give me more context? What exactly is the command you would like to see in the output and how?

**Comment by greencat3** [comment]
I'm trying to build GNU coreutils(specificially, the copy utility 'cp'): https://github.com/coreutils/coreutils.git using Clang and run some special analysis using Clang flags while building the 'cp' binary.
Since coreutils uses autotools to build the whole project (which includes all the coreutils binaries), I decided to use bear to build a compilation database to capture the exact build commands being used to build the 'cp' binary.

Here's what I did to build the compilation database (build commands taken from coreutils README: https://github.com/coreutils/coreutils/blob/master/README-hacking):

`cd coreutils`
`./bootstrap`
`git submodule foreach git pull origin master`
`git commit -m 'build: update gnulib submodule to latest' gnulib`
`./configure`
`bear make`

Here are the commands from 'cp' that compile_commands.json contains:

    {
        "arguments": [
            "cc", 
            "-c", 
            "-I.", 
            "-I./lib", 
            "-Ilib", 
            "-I./lib", 
            "-Isrc", 
            "-I./src", 
            "-g", 
            "-O2", 
            "-MT", 
            "src/cp.o", 
            "-MD", 
            "-MP", 
            "-MF", 
            "src/.deps/cp.Tpo", 
            "-o", 
            "src/cp.o", 
            "src/cp.c"
        ], 
        "directory": "/home/myhome/coreutils", 
        "file": "src/cp.c"
    }, 

        {
        "arguments": [
            "cc", 
            "-c", 
            "-I.", 
            "-I./lib", 
            "-Ilib", 
            "-I./lib", 
            "-Isrc", 
            "-I./src", 
            "-g", 
            "-O2", 
            "-MT", 
            "src/cp-hash.o", 
            "-MD", 
            "-MP", 
            "-MF", 
            "src/.deps/cp-hash.Tpo", 
            "-o", 
            "src/cp-hash.o", 
            "src/cp-hash.c"
        ], 
        "directory": "/home/myhome/coreutils", 
        "file": "src/cp-hash.c"
    },
    etc.


As you can see, there appear to be no linker arguments in the commands, whereas the linker arguments are needed to be known to build the final binary. So I went ahead and commented out the linker options in the IGNORED_FLAGS in bear python script. Here's the change I made:

`diff --git a/bear/main.py.in b/bear/main.py.in`
`index 4190fde..5c3f1ba 100644`
`--- a/bear/main.py.in`
`+++ b/bear/main.py.in`
`@@ -73,21 +73,21 @@ IGNORED_FLAGS = {`
`     # compilation commands only. so, the compiler would ignore these flags`
`     # anyway. the benefit to get rid of them is to make the output more`
`     # readable.`
`-    '-static': 0,`
`-    '-shared': 0,`
`-    '-s': 0,`
`-    '-rdynamic': 0,`
`-    '-l': 1,`
`-    '-L': 1,`
`-    '-u': 1,`
`-    '-z': 1,`
`-    '-T': 1,`
`-    '-Xlinker': 1,`
`+#    '-static': 0,`
`+#    '-shared': 0,`
`+#    '-s': 0,`
`+#    '-rdynamic': 0,`
`+#    '-l': 1,`
`+#    '-L': 1,`
`+#    '-u': 1,`
`+#    '-z': 1,`
`+#    '-T': 1,`
`+#    '-Xlinker': 1,`
`     # clang-cl / msvc cl specific flags`
`     # consider moving visual studio specific warning flags also`
`-    '-nologo': 0,`
`-    '-EHsc': 0,`
`-    '-EHa': 0`
`+ #   '-nologo': 0,`
`+ #   '-EHsc': 0,`
`+ #   '-EHa': 0`
 
` }  # type: Dict[str, int]`


Having done that, the linker flags are still not there in the compile_commands.json. That's when I realized that autotools is separately invoking the linker and not implicitly through CC. While building with autotools, I see CC fileFoo.o and then CCLD fileFoo. So in case of 'cp' binary, this is what I see:

`CC       src/cp.o`
`CC       src/copy.o`
`CC       src/cp-hash.o`
`CC       src/extent-scan.o`
`CC       src/force-link.o`
`CC       src/selinux.o`
`CCLD     src/cp`

Hence my requirement for bear to capture CCLD invocations as well. That way I will have both the compiler as well as linker commands to build the 'cp' binary.

**Comment by rizsotto** [comment]
In case if you just want to see what was the linker command, then I recommend to run `bear -vvvv make`. That makes a very verbose output and you can see the link command. (You won't find that in the output, since it is using the object files as inputs and Bear does not recognise that as a compilation.)

**Comment by greencat3** [comment]
So if I did want bear to capture it and present it in the output.json, is it not as simple as simply adding another pattern like 'CCLD' in addition to existing patterns like 'CC' and 'CXX'?

In the meantime I'll go ahead and try the -vvv argument to bear as well.

**Comment by rizsotto** [comment]
Yes, it requires to add objects extension to the source file extensions. (But that probably has a not desired side effects on other items in the output.)

Try the verbose trick as a workaround.

**Comment by greencat3** [comment]
So tried the verbose trick, it does display a lot more of that info that I was looking for, thanks!
Another question I had was, is the sequential order of compile commands in compile_commands.json reflective of how they were executed?

So say, object #4 in json file was executed before object #5?

**Comment by rizsotto** [comment]
The current version of Bear does not guarantees that compilation database entries are in the order of the execution. (Actually, the definition of the compilation database does not specify it either.) So, it's a "no" answer.

But the change I'm planing to make for the next version will expose more from the command executions. (Like time stamps of the start of the process, and the termination time stamp with exit code.) But it's not ready yet.

**Comment by greencat3** [comment]
Even if not "guaranteed", in general is it ok to assume that the entries in the json file are roughly in order? I understand no guarantee, but is it completely random like a hash table?

**Comment by rizsotto** [comment]
The current behaviour is: executions are written in a JSON file in a directory. Then it's loaded into memory (without paying attention of the file time stamp). And then they shuffled into a python `Set`, to filter out duplicates... You might think about it is a completely random order.

**Comment by rizsotto** [comment]
tracking this issue in #276
