### ISSUE TITLE
Build commands needs updating

### ISSUE THREAD

**Issue by tksuoran** [rizsotto/Bear#206]
Build commands tell to use make. But there is no makefile. I can mkdir build && cd build && cmake .. && make - but that is not what the build commands say.

**Comment by rizsotto** [comment]
I think (but not sure) you are referring the README file build instruction. Is that correct? That section does not exactly tells where to put the build directory. (That could be out of source tree, not necessarily created within the source tree.) The build instructions suggest to run `cmake $BEAR_SOURCE_DIR` which is good. (And in your case if you were doing `mkdir build && cd build` before, the `$BEAR_SOURCE_DIR` will be `..` as you wrote.)
About the "but there is no makefile" part of your comment: yes, there is no makefile. The CMake will create one. CMake can also create Ninja files, probably that is working too... Will fix the wording if that confusing.
