### ISSUE TITLE
"sudo apt install bear" Ubuntu 16.04

### ISSUE THREAD

**Issue by tksuoran** [rizsotto/Bear#207]
I wanted to try bear on Ubuntu 16.04. I can run bear, but it does not seem to work as I get tons of errors:

ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

uname says Linux 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tksuoran** [comment]
I tried manually building 32 and 64 bit version of the library with readme instructions. Now I get ERROR: 

ld.so: object '/opt/bear/$LIB/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

instead.

**Comment by tksuoran** [comment]
I got the manual build working by paying attention to the "Debian derivatives are using lib/i386-linux-gnu and lib/x86_64-linux-gnu" part. Nevertheless it seems that the package for 16.04 has not been prepared for multiarch, so that should be fixed.

**Comment by rizsotto** [comment]
Thanks for the report. I'm not familiar how packaging is done on Ubuntu. Although bear has support for multi arch, but it's more like only a recipe in the readme file. Not sure if any package is doing that.
