### ISSUE TITLE
Usage note

### ISSUE THREAD

**Issue by matanster** [rizsotto/Bear#208]
I think it could be made explicit in the Usage clause of the readme, even if implied in the background, that bear relies on `make` performing a full build, for producing the full database. So oftentimes, one would want to run `make clean` before running `bear make`. (I would guess).

Or something more accurate along these lines....

Anyway thanks for maintaining this awesome project!

**Comment by rizsotto** [comment]
Thanks @matanster to raise this issue, it's a valid point. Will try to address this problem in the future... Or if you feel, pull-requests are always welcome. :)

**Comment by matanster** [comment]
Thank you actually. I always found one-liner readme PR's awkward though, but if I have more comments later, I would. Again, thanks for commenting.

**Comment by rizsotto** [comment]
Fixed. Will be released under version 2.3.12.
