### ISSUE TITLE
Add "How to" documentation

### ISSUE THREAD

**Issue by antmak** [rizsotto/Bear#210]
Could you write a small doc about using `compile_commands.json` in the famous IDEs: Eclipse, Kdevelop, Emacs, VIM, QtCreator?

Thanks!

**Comment by rizsotto** [comment]
Sorry, I don't have the knowledge to write that page. But... if you've already gained some knowledge that you could share, please submit a pull-request. (You don't need to write the full page by yourself, others can extend it later.) What do you think?

**Comment by antmak** [comment]
Maybe I'll try to write something. Well it seems that neither Eclipse nor QtCreator doesn't have support of the compile_commands.json . Kdevelop works magically

**Comment by rizsotto** [comment]
Yes, my understanding was that the compilation databases are used by Clang based tools. Those are command line tools (like clang-tidy, clang-format, etc...) and vim, emacs plugins. Big IDE tools are implemented their own formats... But I might be totally wrong. :)

**Comment by rizsotto** [comment]
Found this very [good summary](https://sarcasm.github.io/notes/dev/compilation-database.html) of tools and usages.
