### ISSUE TITLE
Bear interprets params passed to make as it's own

### ISSUE THREAD

**Issue by jclosure** [rizsotto/Bear#213]
Bear interprets params passed to make as it's own.  Are make args supported or am I doing it wrong?

### Expected Behavior
When I run `bear make -C "..."`, it should work. 

### Actual Behavior
```bash
$ ~/repo$ bear make -C repo -f main.mk -j32
bear: invalid option -- 'C'
Usage: bear [options] -- <build command>

options:
   -c config   config file (default: /etc/bear.conf)
   -o output   output file (default: compile_commands.json)
   -l libear   library location (default: /usr/lib/x86_64-linux-gnu/bear/libear.so)
   -s socket   multiplexing socket (default: randomly generated)
   -n          disable filter, unformated output. (default: filtering)
   -x          verbose filter dump at the end (default: disabled)
   -v          prints Bear version and exit
   -h          this message

exit status: EXIT_FAILURE on any internal problem, otherwise same as the build command exit status.
```
### Environment

- OS name & version:
Ubuntu 14.04
- Bear version:
bear 1.4
- Any information about the compiler that this project is using:
GNU Make 3.81

**Comment by rizsotto** [comment]
Thanks for the report. Could you try some more recent version of the tool? (1.4 is more than 4 years old.) Newer version does not suffer this problem... You can also try `bear -- make -C ...` to separate the command parameters. (Not tested it, so I'm just guessing about this.)

**Comment by jclosure** [comment]
You're right.  I installed latest bear.  Works just fine.  Thanks for the help.
