### ISSUE TITLE
ERROR: ld.so: object '/opt/bear/$LIB/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by qi77wang** [rizsotto/Bear#214]
hello, i meet similar question, like: https://github.com/rizsotto/Bear/issues/169
could you give me some suggestions?

i want make linux code. like this:
source build/envsetup.sh
lunch xxx
bear make

### Actual Behavior
error:
ERROR: ld.so: object '/opt/bear/$LIB/libear.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### Environment

- OS name & version:ubuntu 14.04
- Bear version:bear 2.3.11
- Any reference to the project that you running against:
- Any information about the compiler that this project is using:

**Comment by qi77wang** [comment]
I have tried like this, but It doesn't seem to work.

(cd ~/build32; cmake "$BEAR_SOURCE_DIR" -DCMAKE_C_COMPILER_ARG1="-m32"; VERBOSE=1 make all;)
(cd ~/build64; cmake "$BEAR_SOURCE_DIR" -DCMAKE_C_COMPILER_ARG1="-m64" -DDEFAULT_PRELOAD_FILE='/opt/bear/$LIB/libear.so'; VERBOSE=1 make all;)
sudo install -m 0644 ~/build32/libear/libear.so /opt/bear/lib/libear.so
sudo install -m 0644 ~/build64/libear/libear.so /opt/bear/lib64/libear.so
sudo install -m 0555 ~/build64/bear/bear" /opt/bear/bin/bear

**Comment by rizsotto** [comment]
hey @qi77wang , please read the README file or the #169 ticket comments. Ubuntu is a debian derivative, the `$LIB` resolves as `lib/i386-linux-gnu` and `lib/x86_64-linux-gnu`. So, `/opt/bear/$LIB/libear.so` resolves to `/opt/bear/lib/i386-linux-gnu/libear.so` which you probably don't have.
