### ISSUE TITLE
centos6 /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found 

### ISSUE THREAD

**Issue by ahnetya** [rizsotto/Bear#217]
centos6 
ERROR: ld.so: object '/lib/libstdc++.so' from LD_PRELOAD cannot be preloaded: ig                                                                                        nored.
minergate-cli: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ                                                                                        ired by minergate-cli)
minergate-cli: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re                                                                                        quired by minergate-cli)
minergate-cli: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (re                                                                                        quired by minergate-cli)
minergate-cli: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by min                                                                                        ergate-cli)
minergate-cli: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /op                                                                                        t/minergate-cli/lib/libQt5Network.so.5)
minergate-cli: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /op                                                                                        t/minergate-cli/lib/libQt5Network.so.5)
minergate-cli: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ                                                                                        ired by /opt/minergate-cli/lib/libQt5Network.so.5)
minergate-cli: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ                                                                                        ired by /opt/minergate-cli/lib/libQt5Core.so.5)
minergate-cli: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (requ                                                                                        ired by /opt/minergate-cli/lib/libQt5Core.so.5)
minergate-cli: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /op                                                                                        t/minergate-cli/lib/libQt5Core.so.5)
minergate-cli: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /op                                                                                        t/minergate-cli/lib/libQt5Core.so.5)

**Comment by rizsotto** [comment]
Hi, how can I help you?
