### ISSUE TITLE
compilation_database.json includes extra compilations

### ISSUE THREAD

**Issue by jkbbwr** [rizsotto/Bear#218]
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

bear --use-cc gcc --use-c++ g++ make test

### Expected Behavior
Creates a compilation_database.json with ONLY files compiled using gcc.

### Actual Behavior
Includes files compiled by either compiler. Should only include files compiled by the given cc and c++ compiler

### Environment

- OS name & version:
- Bear version: bear 2.3.11
- Any reference to the project that you running against: 
- Any information about the compiler that this project is using: Two compilers. gcc-arm and gcc

**Comment by rizsotto** [comment]
Thanks Jakob for the report... The `--use-cc` and `--use-c++` flags were created to help Bear to recognized compilers which are not wired in the codebase. So, it is there for to extend the recognized compiler list, and not to expect only those compilers... I'm open to implement such feature as you expected, but that needs to be designed parallel to this. (I don't want to break other people experience who is using these flags as it is today.)
Please help me to understand your usage scenario. (Just describe a bit more high level what you are doing.) Thanks in advance for it.

**Comment by jkbbwr** [comment]
So in my situation, we have two or three different compilers that are listed in our makefile, one of them is an arm toolchain. In the compilation_database.json I simply don't care about anything thats not the compiled for the host. Currently when I try to process the file in say CLion it expoldes because some of the flags don't exist on the C compiler Clion knows about.

**Comment by rizsotto** [comment]
Thanks for the explanation. Will think how to make such functionality.

**Comment by jkbbwr** [comment]
One solution would be a flag saying, don't trace any compiler thats not this compiler. then provide a path to the compiler that I want to trace.

**Comment by rizsotto** [comment]
This is fixed in 2.3.12. `--use-only` force to report only the `--use-cc` or `--use-c++` given compilers. (You can specify multiple of `--use-cc` and `--use-c++` flags.)
