### ISSUE TITLE
Bear -- using make -Bn flag to collect dry-run output

### ISSUE THREAD

**Issue by Piping** [rizsotto/Bear#219]
Hi,

Is it possible to collect the complication flags from dry-run output?

I had a really big project and a full build will be time consuming and not every make command I can prefix it with bear.

Thanks

**Comment by rizsotto** [comment]
Thanks for the good question. I'm afraid it's not comes out of the box with Bear. It works as it intercept the executed compiler calls. If there were no compiler executed it can't intercept it.
One idea to speed up the compilation database creation, you can write fake compiler and linker (which create empty outputs, while not reading its inputs). Then hook those into your build system, and intercept the build with Bear.

**Comment by Piping** [comment]
@rizsotto That is definitely a good workaround!

**Comment by rizsotto** [comment]
@Piping - thanks for the suggestion;

On the `4.2.0-rc` branch there's a new `bear parse-sh` subcommand:

```sh
make -Bn | bear parse-sh | bear semantic --input -
```

- `make -Bn` prints every compile command without running the build;
- `bear parse-sh` turns each line into an execution event;
- `bear semantic --input -` reads the events and writes `compile_commands.json`.

It's best-effort - only as good as what the dry run prints - so interception
stays the recommended path when the build can be run. It isn't released yet;
if you can build the `4.2.0-rc` branch and try it, I'd appreciate hearing how
it goes.
