### ISSUE TITLE
Crash: Index out of bounds

### ISSUE THREAD

**Issue by markuspohjoismaki** [rizsotto/Bear#221]
Index out of bounds possible in _split_command function.

Patched my version with following:
    

> @classmethod
>     def _split_command(cls, command, category):
>         ...
>         result = CompilationCommand(compiler=compiler_and_arguments[0],
>                                     language=compiler_and_arguments[1],
>                                     phase=[],
>                                     flags=[],
>                                     files=[],
>                                     output=[])
> 
>         # HERE IS PATCH. verify that we shall not read past the compiler_and_arguments
>         if(len(compiler_and_arguments) < 3):
>             return None

### Expected Behavior
No crash during compilation.

### Actual Behavior
Crash during compilation. 

### Environment

- OS name & version: Ubuntu 16.4
- Bear version: 2.3.12
- Any reference to the project that you running against: None
- Any information about the compiler that this project is using: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by rizsotto** [comment]
Pushed a fix onto master (without version bump yet). Could you confirm that it works for you? I think you were using `ccache`, could it be?

**Comment by rizsotto** [comment]
Thanks to confirm it! Will make a new release soon.
