### ISSUE TITLE
JSONDecodeError on Fedora 28 with bear 2.3.13

### ISSUE THREAD

**Issue by morxa** [rizsotto/Bear#226]
I occasionally get a JSONDecodeError, and now I finally captured one properly.

I'm sure I've seen an issue about this already, but I couldn't find it anymore.

### Expected Behavior
Create the compilation database.

### Actual Behavior
```
Traceback (most recent call last):
  File "/usr/bin/bear", line 739, in <module>
    sys.exit(intercept_build())
  File "/usr/bin/bear", line 265, in wrapper
    return function(*args, **kwargs)
  File "/usr/bin/bear", line 297, in intercept_build
    entries = iter(set(itertools.chain(previous, current)))
  File "/usr/bin/bear", line 672, in load
    for entry in json.load(handle):
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The resulting `compile_commands.json` is empty.

Exact steps:
1. `git clone https://github.com/simbody/simbody.git`
1. `mkdir -p build && cd build && cmake ..`
1. `touch ../compile_commands.json`
1. `bear -vvvv -a -o ../compile_commands.json make -j8 -l8 2>&1 | tee ../build.log`

[build.log](https://github.com/rizsotto/Bear/files/2611252/build.log)

### Environment

- OS name & version: Fedora 28
- Bear version: 2.3.13
- Any reference to the project that you running against: [simbody/simbody](https://github.com/simbody/simbody)
- Any information about the compiler that this project is using: g++ 8.2.1 (with ccache)

**Comment by rizsotto** [comment]
Thanks @morxa for the report. I think I know why it happens. :) With `touch ../compile_command.json` you create an empty file. And with the `-a` flag, you ask to concatanate the result to that file. Which Bear will try to open and parse it as JSON and it fails at that point (because empty input is not a valid JSON content).

Solutions could be:
* Create the empty file as `echo "[]" > ../compile_commands.json`.
* Or `rm -f ../compile_commands.json` to completely eliminate the read.
