### ISSUE TITLE
standalone appimage release/build

### ISSUE THREAD

**Issue by Piping** [rizsotto/Bear#233]
Hi, I have a legacy system that has build environment.

Most prerequisite is hard to achieve. 

Is that possible to provide a bear app image that I can drop into directory and work for me?

Thanks!!

**Comment by Piping** [comment]
Yeah..single app docker would be great! However, I am not sure if that applicable to bear since it need to use LD_PRELOAD.so.

My target OS is CentOS Linux 7.5.1804. Many commands are just outdated or old in the default system.

**Comment by rizsotto** [comment]
Thanks to come back. Yes, docker might be problematic... But I'm curious which dependency is hard for CentOS? (`python` 2.7 is good enough, `cmake` 2.8 is good enough, `gcc` 4.8 does C99, and default `make` will work with `cmake`.)

**Comment by Piping** [comment]
yeah. I thought cmake needs higher version. Thanks! It works great for now!
