### ISSUE TITLE
Library cannot be loaded

### ISSUE THREAD

**Issue by xolom** [rizsotto/Bear#234]
Hi.

I am running SuSE11 and `uname-a` gives me following output:
`Linux lzsxc022 3.0.101-108.13.1.14249.0.PTF-default #1 SMP Thu Nov 30 18:45:29 UTC 2017 (ae6bb13) x86_64 x86_64 x86_64 GNU/Linux`

Doing `ldd `on the compiled .so library gives me:
```
inux-vdso.so.1 =>  (0x00002aaaaaaab000)
libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaacd3000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaaaed8000)
libc.so.6 => /lib64/libc.so.6 (0x00002aaaab0f5000)
/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
```

I installed the .so file to a custom path because i have no root rights and passed `--libear` with the correct path to `bear`

If i try to run `readelf -h` on the library file, i get following output:
```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0xeb0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          20616 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         30
  Section header string table index: 27
```

Anyway I get the following error message when trying to use bear:
`ERROR: ld.so: object '/nfs/site/home/aschrede/build/Bear-master/libear/libear.so' from LD_PRELOAD cannot be preloaded: ignored.`

I am out of ideas....

**Comment by schreda** [comment]
Some additional info i found:

We use the xtensa compiler `xt-xcc`
trying to set LD_PRELOAD manually and executing the compilers binary shows the same error.
If i try to run `gcc`, no error appears

**Comment by schreda** [comment]
Can be closed!
This was an Architecture issue. The compiler runs on 32 bit
