### ISSUE TITLE
ERROR: ld.so: object '/lib/x86_64-linux-gnu/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

### ISSUE THREAD

**Issue by srikanth007m** [rizsotto/Bear#236]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
Bear version: bear 2.3.13

I've followed the steps from the [README ](https://github.com/rizsotto/Bear/blob/master/README.md)to setup the bear on Ubuntu and also few reported issues https://github.com/rizsotto/Bear/issues/134. I am getting these messages, While i am compiling the kernel with following commands.

`make V=1 O=out ARCH=arm64 CROSS_COMPILE=/linaro-toolchain/.4.9-2014.06-02_linux-x86/bin/aarch64-linux-gnu- C=0 REAL_CC=llvm/release/arm/6.0/bin/clang`

ERROR: ld.so: object '/lib/x86_64-linux-gnu/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/lib/x86_64-linux-gnu/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/lib/x86_64-linux-gnu/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by srikanth007m** [comment]
Issue got resolved.

**Comment by gpenghe** [comment]
@srikanth007m May I ask how you get this resolved? I am having the similar issue when doing `bear make` using an ARM cross compiler.

**Comment by galberding** [comment]
I had the same problem with the [4.8-2014-q1-update](https://launchpad.net/gcc-arm-embedded/+milestone/4.8-2014-q1-update) cross compiler. I also tried the release before ([4.8-2013-q4-major](https://launchpad.net/gcc-arm-embedded/4.8/4.8-2013-q4-major)) which led to a similar problem like above:
```
$ bear make
make -C DiWheelDrive
make[1]: Entering directory '/media/store/schorschi/Projects/amiro/amiro-os/devices/DiWheelDrive'
Compiler Options
arm-none-eabi-gcc -c -mcpu=cortex-m3 -O1 -fomit-frame-pointer -falign-functions=16 -DCHPRINTF_USE_FLOAT=1 -fstack-usage -DSERIAL_BUFFERS_SIZE=64 -ffunction-sections -fdata-sections -fno-common -Wall -Wextra -Wstrict-prototypes -Wa,-alms=build/lst/ -DCORTEX_USE_FPU=FALSE -DTHUMB_PRESENT -mno-thumb-interwork -DTHUMB_NO_INTERWORKING -MD -MP -MF .dep/build.d -I. -I../../../ChibiOS/os/ports/common/ARMCMx/CMSIS/include -I../../../ChibiOS/os/ports/common/ARMCMx -I../../../ChibiOS/os/ports/GCC/ARMCMx -I../../../ChibiOS/os/ports/GCC/ARMCMx/STM32F1xx -I../../../ChibiOS/os/kernel/include -I../../../ChibiOS/os/hal/include -I../../hal/include -I../../../ChibiOS/os/hal/platforms/STM32F1xx -I../../../ChibiOS/os/hal/platforms/STM32 -I../../../ChibiOS/os/hal/platforms/STM32/GPIOv1 -I../../../ChibiOS/os/hal/platforms/STM32/I2Cv1 -I../../../ChibiOS/os/hal/platforms/STM32/RTCv1 -I../../../ChibiOS/os/hal/platforms/STM32/SPIv1 -I../../../ChibiOS/os/hal/platforms/STM32/TIMv1 -I../../../ChibiOS/os/hal/platforms/STM32/USARTv1 -I../../../ChibiOS/os/hal/platforms/STM32/USBv1 -I../../hal/platforms/STM32 -I../../boards/DiWheelDrive -I../../../ChibiOS/os/various/cpp_wrappers -I../../../ChibiOS/os/various -I../.. -I../../include main.c -o main.o

mkdir -p build/obj
mkdir -p build/lst
Compiling crt0.c
ERROR: ld.so: object '/home/schorschi/Projects/ks-env/Bear/install/lib/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/schorschi/Projects/ks-env/Bear/install/lib/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
../../../ChibiOS/os/ports/GCC/ARMCMx/crt0.c: In function '_default_exit':
../../../ChibiOS/os/ports/GCC/ARMCMx/crt0.c:260:1: warning: stack usage computation not supported for this target [enabled by default]
 }
 ^
ERROR: ld.so: object '/home/schorschi/Projects/ks-env/Bear/install/lib/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
[...]
```
Also tried the bear command with the ``` --use-*``` Flags, which does not make any difference. 


My System:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
bear: 2.4.3 

The funny thing is that all compilers (I tested: 4_8-2014q2,  8-2018-q4-major) after the ```4.8-2014-q1-update``` seem work fine with bear. 
**Possible Solution:** So if you can, try to switch to a more current compiler version. 
The problem for me is that I am stuck with that compiler but it is back from 2014 so its questionable if its worth to investigate more.

**Comment by galberding** [comment]
@MrPointer then it may be worth reopening this issue. In my case the error remains but I noticed that bear still generates the `compile_commands.json` which also seems to be quite complete such that clang could use it. 
Is bear able to generate that `compile_commands.json` in your case?

**Comment by MrPointer** [comment]
@galberding Yes it does, so I don't know if these errors should be so disturbing...

I just thought it may imply a bigger problem, hidden deeply underneath

**Comment by rizsotto** [comment]
Please help me to help you. :)

I have no experience in cross compiling issues. I would need an example project and short description what would you like to achieve with the generated output. (Basically tell me how to validate if I could reproduce.)

**Comment by galberding** [comment]
@rizsotto Thank you for helping :)
I tried to create a minimal example https://github.com/galberding/sample where you should be able to recreate the error. This was the cross compiler I used: https://launchpad.net/gcc-arm-embedded/+milestone/4.8-2014-q1-update

**Comment by rizsotto** [comment]
Thanks @galberding , will try these on the weekend and come back to you.

**Comment by Piraty** [comment]
The toolchain's binaries are 32bit executables
```
$ file gcc-arm-none-eabi-4_8-2014q1/bin/arm-none-eabi-gcc
bin/arm-none-eabi-gcc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.8, stripped
```

**Comment by rizsotto** [comment]
Notes to myself...
```
podman run --net=host -ti ubuntu:14.04.5
```
inside the container
```
apt-get update
# enable cross compiler ppa
apt-get install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
add-apt-repository ppa:team-gcc-arm-embedded/ppa
apt-get update
# install dev tools
apt-get install gcc-arm-embedded
apt-get install git cmake python clang
# get projects
git clone https://github.com/rizsotto/Bear.git
git clone https://github.com/galberding/sample.git
```

- [x] compile and install bear (`DESTDIR=/opt/Bear make install`)
- [x] compile sample project (`make`)
- [x] compile sample project with bear (`/opt/Bear/usr/local/bin/bear -l /opt/Bear/usr/local/lib/x86_64-linux-gnu/bear/libear.so make`)
- [x] compile sample project with cross compiler (`CC=arm-none-eabi-g++ make`)
- [x] compile sample project with bear and cross compiler (`CC=arm-none-eabi-g++ /opt/Bear/usr/local/bin/bear -l /opt/Bear/usr/local/lib/x86_64-linux-gnu/bear/libear.so make`)

@galberding are you using 32 bit toolchain?

```shell
$ file `which arm-none-eabi-g++`
/usr/bin/arm-none-eabi-g++: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=295dbacda338fe3c8aa35596313d69bac0f43d55, stripped
$ 
```

**Comment by galberding** [comment]
@rizsotto indeed the specific toolchain I use is 32 bit.
```
file arm-none-eabi-g++
arm-none-eabi-g++: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.8, stripped
```
I also updated my last comment above, where I try to install the 32 bit version of Bear.
Is there some installation step that is also required in order to make it work properly?

**Comment by rizsotto** [comment]
@galberding thanks for the update. Will investigate further with the 32 bit compiler.

But I'm struggle on ubuntu/debian systems... Can you highlight what are commands (in a fresh docker image) that prepares the environment close to yours? That would be a big help for me.

For the 64 bit install (I've logged above) there were no special special install command. Only those which are in the `README.md` file.

**Comment by galberding** [comment]
@rizsotto Yes i will try that. Would it be sufficient to prepare a little script that would setup everything on an ordinary ubuntu machine (with some additional instruction)?
I am not that familiar with Docker.

**Comment by MrPointer** [comment]
@rizsotto Hi, I'd like to point out that I use a 64-bit cross-compiler for 32-bit ARM, similar to what you have set up in an earlier comment.
It doesn't happen only on 32-bit machines as @galberding point out!

**Comment by galberding** [comment]
@rizsotto I gave my best to automate my environment creation and described it briefly in the [README](https://github.com/galberding/sample/blob/master/README.md).
It may be buggy so please be patient :)
You may need to install curl and cmake for the build process.
It is supposed to work with Ubuntu 20.04.

**Comment by rizsotto** [comment]
Notes to myself...
```
podman run --net=host -ti ubuntu:20.04
```
inside the container
```
dpkg --add-architecture i386
apt-get -y update
apt-get -y install gcc-multilib git cmake python gcc curl
git clone https://github.com/galberding/sample.git
git clone https://github.com/rizsotto/Bear.git
./sample/setup.sh # install the cross compiler
```
Compile bear as it is written in the README. Install one of the build to `/opt/bear`. The `libear.so` is in a wrong directory. Put the 32 bit version into `lib32` and the 64 bit version into `lib64`. (The reason behind it is in the dynamic linker `RPATH` resolution convention. The [man](http://manpages.ubuntu.com/manpages/bionic/man8/ld.so.8.html) page "Rpath token expansion" section.) 
```
$ find /opt/bear/
/opt/bear/
/opt/bear/usr
/opt/bear/usr/local
/opt/bear/usr/local/bin
/opt/bear/usr/local/bin/bear
/opt/bear/usr/local/share
/opt/bear/usr/local/share/man
/opt/bear/usr/local/share/man/man1
/opt/bear/usr/local/share/man/man1/bear.1
/opt/bear/usr/local/share/doc
/opt/bear/usr/local/share/doc/bear
/opt/bear/usr/local/share/doc/bear/ChangeLog.md
/opt/bear/usr/local/share/doc/bear/README.md
/opt/bear/usr/local/share/doc/bear/COPYING
/opt/bear/usr/local/share/bash-completion
/opt/bear/usr/local/share/bash-completion/completions
/opt/bear/usr/local/share/bash-completion/completions/bear
/opt/bear/usr/local/lib64
/opt/bear/usr/local/lib64/libear.so
/opt/bear/usr/local/lib
/opt/bear/usr/local/lib/libear.so
$ file /opt/bear/usr/local/lib64/libear.so /opt/bear/usr/local/lib/libear.so
/opt/bear/usr/local/lib64/libear.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=846741432881d3930f671d6c3a626edb3712877f, not stripped
/opt/bear/usr/local/lib/libear.so:   ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=69b0bd708efe514a735fe00cb618cf2820a2bc1a, not stripped
```
verify if the dynamic linker finds the `libear.so` file.
```
LD_DEBUG=libs /opt/bear/usr/local/bin/bear -l '/opt/bear/usr/local/$LIB/libear.so' make
```
Found from the log, that the Python and the Make executable are 64 bit and the compiler is a 32 bit executable. So, looking into the successfully loaded libraries' path and the dynamic linker configuration files (`ls -l /etc/ld.so.conf.d/`) I've tried to rename the library directory names... This one works:
```
$ find /opt/bear/
/opt/bear/
/opt/bear/usr
/opt/bear/usr/local
/opt/bear/usr/local/bin
/opt/bear/usr/local/bin/bear
/opt/bear/usr/local/share
/opt/bear/usr/local/share/man
/opt/bear/usr/local/share/man/man1
/opt/bear/usr/local/share/man/man1/bear.1
/opt/bear/usr/local/share/doc
/opt/bear/usr/local/share/doc/bear
/opt/bear/usr/local/share/doc/bear/ChangeLog.md
/opt/bear/usr/local/share/doc/bear/README.md
/opt/bear/usr/local/share/doc/bear/COPYING
/opt/bear/usr/local/share/bash-completion
/opt/bear/usr/local/share/bash-completion/completions
/opt/bear/usr/local/share/bash-completion/completions/bear
/opt/bear/usr/local/lib
/opt/bear/usr/local/lib/x86_64-linux-gnu
/opt/bear/usr/local/lib/x86_64-linux-gnu/libear.so
/opt/bear/usr/local/lib32
/opt/bear/usr/local/lib32/libear.so
$ file /opt/bear/usr/local/lib/x86_64-linux-gnu/libear.so /opt/bear/usr/local/lib32/libear.so
/opt/bear/usr/local/lib/x86_64-linux-gnu/libear.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=846741432881d3930f671d6c3a626edb3712877f, not stripped
/opt/bear/usr/local/lib32/libear.so:                ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=69b0bd708efe514a735fe00cb618cf2820a2bc1a, not stripped
$ make clean
$ /opt/bear/usr/local/bin/bear -l '/opt/bear/usr/local/$LIB/libear.so' make
arm-none-eabi-g++ -c -Wall -g main.cpp -o main.o
arm-none-eabi-g++ --specs=nosys.specs  main.o -o odo
$ cat compile_commands.json 
[
    {
        "arguments": [
            "arm-none-eabi-g++", 
            "-c", 
            "-Wall", 
            "-g", 
            "-o", 
            "main.o", 
            "main.cpp"
        ], 
        "directory": "/root/sample/example", 
        "file": "main.cpp"
    }
]
```

**Comment by galberding** [comment]
@rizsotto  yes, your notes in combination with #214 resolves the error. 
Thank you :)

**Comment by Werner42** [comment]
hello，i have met same problem. I use cross compiler **arm-none-eabi-gcc(32bit)** to complie my code.
First, I installed **bear2.1.5** with apt-get on **ubuntu16 (x86_64)**. when use bear run my makefile , it display "libear.so' from LD_PRELOAD cannot be preloaded",but the "compile_commands.json" is generated and is not empty.
then i found this page, so i download and compile **bear 3.0.0** on **ubuntu20.04 (x86_64)**, but i could't find  the 32bit or 64 bit libear.so.
The file instead of the libear.so is **libexec.so** ,which is 64 bit version. so the error is still existed. and i try use  -DCMAKE_C_COMPILER_ARG1="-m32" , -DCMAKE_CXX_COMPILER_ARG1="-m32" to compile a 32 bit version libexec.so. But it faialed.( I am not familiar with CMake.)
Finally,I install bear2.1.5 with apt-get on ubuntu14(i386),and the error disappear.

**Comment by rizsotto** [comment]
@Werner42 thanks for the update.

The latest master (which has the 3.0.x) is not yet tested with multilib. Will create a ticket for it.

**Comment by Piraty** [comment]
for later referece: https://github.com/rizsotto/Bear/issues/324

**Comment by Mhosseinkhodakhah** [comment]
> @srikanth007m May I ask how you get this resolved? I am having the similar issue when doing `bear make` using an ARM cross compiler.

i have the same problem

**Comment by DavidEdell** [comment]
Same issue here when cross-compiling to a 32-bit (VxWorks) target.  

As a workaround, I ran bear on a native build instead.  Not ideal, but good enough for emacs/ide integration.
