### ISSUE TITLE
absolute path for bear output option ?

### ISSUE THREAD

**Issue by maindoor** [rizsotto/Bear#238]
The "command" output in compile_commands.json uses a relative path name like "g++" or "clang" etc.
In the case of a cross compile toolchain it uses something like "mips-openwrt-linux-uclibc-gcc".

Can we have a run time option to produce this output with an absolute pathname for gcc  ?
so something like "/path/to/users/private/build/path/to/mips-openwrt-linux-uclibc-gcc" 
instead of just "mips-openwrt-linux-uclibc-gcc" ?

**Comment by rizsotto** [comment]
Hey @maindoor , thanks for the report. Can I ask which version do you use?

**Comment by maindoor** [comment]
Hey @rizsotto, this is an old build machine, the version I have is 1.4.2.

**Comment by rizsotto** [comment]
Try to use the latest version from master. This issue has been fixed.
The current requirements to build it are very low. An old machine should do that too. :smile:

**Comment by maindoor** [comment]
Ok. I tried this again with version bear 2.3.13 (compiled from git) on an open source project (openwrt).
Please see an entry for a file txrx.c below. 
The compiler is still "mips-openwrt-linux-musl-gcc". Can we have
an option to output full (absolute path) instead of just the name of the end executable ?

{
        "arguments": [
            "mips-openwrt-linux-musl-gcc", 
            "-c", 
            "-Wp,-MD,/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/drivers/net/wireless/ath/ath10k/.txrx.o.d", 
            "-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/backport-include/", 
            "-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/backport-include/uapi", 
            "-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/include/", 
            "-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/include/uapi", 
            "-include", 
            "/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/backport-include/backport/backport.h", 
            "-Wno-unused-but-set-variable", 
            "-DCPTCFG_VERSION=\"v4.19.23-1-0-g480a925a\"", 
            "-DCPTCFG_KERNEL_VERSION=\"v4.19.23-0-g67d52fae61c1\"", 
            "-DCPTCFG_KERNEL_NAME=\"Linux\"", 
            "-I./arch/mips/include", 
            "-I./arch/mips/include/generated", 
            "-I./include", 
            "-I./arch/mips/include/uapi", 
            "-I./arch/mips/include/generated/uapi", 
            "-I./include/uapi", 
            "-I./include/generated/uapi", 
            "-include", 
            "./include/linux/kconfig.h", 
            "-D__KERNEL__", 
            "-DVMLINUX_LOAD_ADDRESS=0xffffffff80060000", 
            "-DDATAOFFSET=0", 
            "-Wall", 
            "-Wundef", 
            "-Wstrict-prototypes", 
            "-Wno-trigraphs", 
            "-fno-strict-aliasing", 
            "-fno-common", 
            "-fshort-wchar", 
            "-Werror-implicit-function-declaration", 
            "-Wno-format-security", 
            "-std=gnu89", 
            "-fno-PIE", 
            "-mno-check-zero-division", 
            "-mabi=32", 
            "-G", 
            "0", 
            "-mno-abicalls", 
            "-fno-pic", 
            "-pipe", 
            "-mno-branch-likely", 
            "-msoft-float", 
            "-DGAS_HAS_SET_HARDFLOAT", 
            "-Wa,-msoft-float", 
            "-ffreestanding", 
            "-fno-stack-check", 
            "-march=mips32r2", 
            "-mtune=34kc", 
            "-Wa,--trap", 
            "-DTOOLCHAIN_SUPPORTS_VIRT", 
            "-I./arch/mips/include/asm/mach-ath79", 
            "-I./arch/mips/include/asm/mach-generic", 
            "-fno-asynchronous-unwind-tables", 
            "-fno-delete-null-pointer-checks", 
            "-Wno-frame-address", 
            "-Wno-format-truncation", 
            "-Wno-format-overflow", 
            "-Wno-int-in-bool-context", 
            "-Os", 
            "-Wno-maybe-uninitialized", 
            "-fno-caller-saves", 
            "--param=allow-store-data-races=0", 
            "-DCC_HAVE_ASM_GOTO", 
            "-Wframe-larger-than=1024", 
            "-fstack-protector", 
            "-Wno-unused-but-set-variable", 
            "-Wno-unused-const-variable", 
            "-fomit-frame-pointer", 
            "-fno-var-tracking-assignments", 
            "-Wdeclaration-after-statement", 
            "-Wno-pointer-sign", 
            "-fno-strict-overflow", 
            "-fno-merge-all-constants", 
            "-fmerge-constants", 
            "-fno-stack-check", 
            "-fconserve-stack", 
            "-Werror=implicit-int", 
            "-Werror=strict-prototypes", 
            "-Werror=date-time", 
            "-Werror=incompatible-pointer-types", 
            "-Werror=designated-init", 
            "-fno-pie", 
            "-no-pie", 
            "-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/include", 
            "-iremap/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1:backports-4.19.23-1", 
            "-DMODULE", 
            "-mno-long-calls", 
            "-DKBUILD_BASENAME=\"txrx\"", 
            "-DKBUILD_MODNAME=\"ath10k_core\"", 
            "-o", 
            "/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/drivers/net/wireless/ath/ath10k/txrx.o", 
            "../backports-4.19.23-1/drivers/net/wireless/ath/ath10k/txrx.c"
        ], 
        "directory": "/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/linux-4.14.103", 
        "file": "../backports-4.19.23-1/drivers/net/wireless/ath/ath10k/txrx.c"
    }
