### ISSUE TITLE
Support Frotran compilers

### ISSUE THREAD

**Issue by chunhualiao** [rizsotto/Bear#241]
I know this was discussed previously https://github.com/rizsotto/Bear/issues/201 . But the issue was closed. 

May I request to add the new feature of capture Fortran compiler (such as ifort, gfortran, etc) command lines? 

Thanks!

**Comment by rizsotto** [comment]
Thanks for to bring up the issue. Will put it on the roadmap of the project to implement this feature.

**Comment by chunhualiao** [comment]
@rizsotto Thanks a lot for your quick response. Do you have an estimation about when this can be available?

**Comment by rizsotto** [comment]
@chunhualiao Can't do real estimate. I'm working on a refactor/rewrite. That's my highest priority. I hope will finish middle of this year.

**Comment by rizsotto** [comment]
@chunhualiao could you help me with this? To implement this, I need a small project to verify that the tool does well. I don't know much about fortran projects, (can learn, but too much on my plate now), so I need a little help or guidance to understand the problem.

- Need a small example project how a tipical fortran project looks like.
- Need some documentation which explains how to build that project.
   - What are the dependencies I need to install?
   - What are the tools I need to install?
   - It helps if you can name OS packages for certain distro.
- Need to know what is the expected output as a compilation database, for the given project.
   - Would be also useful a tool which works with the output.

**Comment by chunhualiao** [comment]
When do you need it? I can try to find one by then.  Thanks

**Comment by rizsotto** [comment]
No hurry! :smile:

**Comment by chunhualiao** [comment]
@rizsotto Here is a popular Fortran code, with wiki explaining how to build its serial version, dependencies, how to run it, and expected output: https://github.com/chunhualiao/NAS-Parallel-Benchmark/wiki  
Let me know if you have any issues of using it.  Thanks!

**Comment by rizsotto** [comment]
Thanks, will try to compile it on the weekend.

**Comment by rizsotto** [comment]
Planing to release this on the weekend (or next week). It's now on the `devel` branch. If you can test and give me some feedback, I would really appreciate it.
