### ISSUE TITLE
Feature Request: Allow to specify temp directory other than /tmp

### ISSUE THREAD

**Issue by rbresalier** [rizsotto/Bear#244]
In our project the /tmp space is smaller and less preferable to a different directory for temp files.

I made a local modification to Bear source code to use a different directory, as I prefer not changing the TMPDIR because that could impact other applications.

Would be nice if Bear offered a way to specify a different root for the temp files via either a command line argument or environment variable. Then I wouldn't need to use a locally patched version.

Thanks for this very great and amazing tool!

**Comment by rizsotto** [comment]
Thanks for this report. I'm always curious how people are using this tool. Could you give me some context why the `/tmp` is small for your project? Is the project has too many files? Or your distro is `tmpfs` which is limited by the memory? Or many users, processes are using it?

Anyway, I'm doing a bigger rewrite of this tool. That will not use temporary files as the current version. So, if you are happy with your patched version, I would not spend time on to introduce the flag for the current version. But feel free to raise a PR if you already have something.

**Comment by rbresalier** [comment]
I have many users, many processes running it on large build servers. Actually /tmp is probably not too small, but the place where I would rather put it is much bigger so I feel safer there. Also the space where I would rather have it eventually gets cleaned up by the user when they are no longer using it. So I do realize that Bear does clean it up unless there is a kill -9, but I still feel safer putting the files in the other place that I know gets cleaned up eventually. My patch checks an environment variable and uses it instead of a command line param for using a different dir than /tmp, probably not as clean as a "production" version, so you may not want the PR of my patch.

**Comment by rizsotto** [comment]
Hi @rbresalier , there is a release candidate on master branch now, which suppose to fix this issue. It uses gRPC to communicate between the process execution reporter and the report collector. So, no longer using the `/tmp` for this. It solves your problem I think. (Maybe it will cause new ones for others.)
