### ISSUE TITLE
Long Command/File Path Support

### ISSUE THREAD

**Issue by jmodares** [rizsotto/Bear#246]
Hi László,

Bear is not able to generate JSON command for files with long path/filename. I'm not sure if this is a limitation in Linux for passing limited characters as the arguments (call_posix_spawn for instance).

I hope that could be fix in next version.

Thanks,
Jalil

**Comment by rizsotto** [comment]
Hey Jalil, could you pass me an example of long files. (Is the `.c` file name is long? Or the nested path is long? How long is long?) I would like to reproduce the bug before I start fixing it. :)

**Comment by jmodares** [comment]
Dear László,

It is a big project, with many sub-directories and files (mostly .c, .cpp, and .h). I have tested the two cases:
1) /local/mnt/xxx/yyy/zzz/project
2) /local/mnt/xxx/project

In case one around 100 Faild
In case two around 13 Faild

That's why I came to the conclusion (although I could have added some debug message to the libbear for exact filenames).

Do we have 256 character limitation?

Thanks,
Jalil

**Comment by rizsotto** [comment]
Thanks Jalil, will look into it on the weekend. Can you also clarify the following:

- What OS? Which version?
- What version of Bear?
- How did you installed Bear? (from package or from source?)
- Any reference to the project you are running against? (If it's open source)
- What build tool this project is using?
- What compiler this project is using?

**Comment by rizsotto** [comment]
Did read through the code, no fix size allocation is used.
Did run a test with a path longer than 256, and it passed.

**Comment by jmodares** [comment]
Thank you for the information.

In the function "call_posix_spawn", why is "restrict" needed?

The platform I'm using Bear is:
Linux 4.15.0-43-generic #46~16.04.1-Ubuntu SMP x86_64

**Comment by rizsotto** [comment]
Hey @jmodares, I don't think that the `restrict` is needed. It was just a copy how the linux header defines it. Do you think it's related to your long path problem?

By the way, is there any new finding about the original problem?

**Comment by jmodares** [comment]
Dear László,

I was able to narrow down the issue, the long file paths and/or long commands cause some problems with (gcc) memory allocation. I proposed a fix to use malloc instead.

I hope that helps.

Thanks,
Jalil

**Comment by rizsotto** [comment]
Hey @jmodares , that's an interesting thing. Can you spot more on this? I still can't reproduce the bug.

I don't understand how `malloc` will fix this. My understanding on `fork` and `exec` that it should avoid to do allocation. I lean towards to not output a JSON file, and not do encode the strings, therefore not have the need to allocate.

**Comment by jmodares** [comment]
I put debug messages in "write_json_report", and it turned out that problem happens when buffer_size goes around 160000.
You can generate the issue with:
/long_path_to_tools/clang --long_list_of_params /long_path_to_source_file

**Comment by rizsotto** [comment]
Hey @jmodares , I rolled out a version which does not do the JSON strings inside the C library. So, probably this problem is gone too. (The solution introduce a limit on the string sizes: 2^32 byte is the longest string. And the longest command line is also has the limit of 2^32 of paramteres.)

Could you please test the current master branch, if it has the problem?

**Comment by jmodares** [comment]
Dear László,

With the new version I don't see the issue anymore.

Thanks,
Jalil

**Comment by rizsotto** [comment]
Thanks Jalil!
