### ISSUE TITLE
how to use long and complex build command

### ISSUE THREAD

**Issue by taiwuchiang** [rizsotto/Bear#247]
Hello:
I need to use a commands like the following to compile an Android library:

"ONE_SHOT_MAKEFILE=frameworks/av/media/libmedia/Android.mk make -C /home/local/code/nova -f build/core/main.mk all_modules"

When I run "bear the_command", I got the following errors:
bear -vvvv ONE_SHOT_MAKEFILE=frameworks/av/media/libmedia/Android.mk make -C /home/local/code/nova -f build/core/main.mk all_modules
bear: DEBUG: parse_args_for_intercept_build: Raw arguments ['/usr/local/bin/bear', '-vvvv', 'ONE_SHOT_MAKEFILE=frameworks/av/media/libmedia/Android.mk', 'make', '-C', '/home/local/MAGICLEAP/tchiang/code/nova', '-f', 'build/core/main.mk', 'all_modules']
bear: DEBUG: parse_args_for_intercept_build: Parsed arguments: Namespace(append=False, build=['ONE_SHOT_MAKEFILE=frameworks/av/media/libmedia/Android.mk', 'make', '-C', '/home/local/MAGICLEAP/tchiang/code/nova', '-f', 'build/core/main.mk', 'all_modules'], cdb='compile_commands.json', libear='/usr/local/lib/bear/libear.so', use_cc=['cc'], use_cxx=['c++'], use_only=False, verbose=4)
bear: DEBUG: run_build: run build ['ONE_SHOT_MAKEFILE=frameworks/av/media/libmedia/Android.mk', 'make', '-C', '/home/local/code/nova', '-f', 'build/core/main.mk', 'all_modules'], in environment: {removed}
bear: ERROR: wrapper: Internal error.
Traceback (most recent call last):
  File "/usr/local/bin/bear", line 265, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/bin/bear", line 291, in intercept_build
    exit_code, current = capture(args, category)
  File "/usr/local/bin/bear", line 315, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/local/bin/bear", line 189, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
bear: ERROR: wrapper: Please report this bug and attach the output to the bug report

**Comment by taiwuchiang** [comment]
### Environment

- OS name & version:
Ubuntu 14.04
- Bear version:
bear 2.3.13
- Any reference to the project that you running against:
This is a project based on Android Open Source Project (AOSP)
- Any information about the compiler that this project is using:
Python 2.7.6

**Comment by rizsotto** [comment]
Hey @taiwuchiang , thanks for the report.

`ONE_SHOT_MAKEFILE=frameworks/av/media/libmedia/Android.mk make -C /home/local/code/nova -f build/core/main.mk all_modules`

This line perfectly understood by the shell. It is like `ENV1=VALUE1 ENV2=VALUE2 ... COMMAND ARG1 ARG2 ...`. If you just give Bear this line, it won't understand, because Bear can accept the command only.

The form `ENV1=VALUE1 ENV2=VALUE2 ... bear COMMAND ARG1 ARG2 ...` should work.

**Comment by taiwuchiang** [comment]
Thanks so much, it works. Cool! I found combined using Sourcetrail and Bear make my job so easy. Nice tool!
