### ISSUE TITLE
`GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by xmuyong** [rizsotto/Bear#255]
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

### Expected Behavior
generate compile_commands.json

### Actual Behavior
#comand
~/.jumbo/bear/usr/local/bin/bear   --libear ~/.jumbo/bear/usr/local/lib64/bear/libear.so -vvvv make

#output
bear: DEBUG: parse_args_for_intercept_build: Raw arguments ['/home/users/xmuyong/.jumbo/bear/usr/local/bin/bear', '--libear', '/home/users/xmuyong/.jumbo/bear/usr/al/lib64/bear/libear.so', '-vvvv', 'make']
bear: DEBUG: parse_args_for_intercept_build: Parsed arguments: Namespace(append=False, build=['make'], cdb='compile_commands.json', libear='/home/users/xmuyong/.jumbo/b/usr/local/lib64/bear/libear.so', use_cc=['cc'], use_cxx=['c++'], use_only=False, verbose=4)
bear: DEBUG: run_build: run build ['make'], in environment: {'HOSTNAME': '*', 'BASH_FUNC_module%%': '() {  eval `/usr//modulecmd bash $*`\n}', 'LESSOPEN': '|/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '#', 'CVS_RSH': 'ssh', 'LOGNAME': '*', 'USER': '*', DIR': '/usr/lib64/qt-3.3', 'PATH': '/home/users/xmuyong/.BCloud/bin:/home/users/xmuyong/.jumbo/bin/core_perl:/home/users/xmuyong/.jumbo/bin:/opt/compiler/gcc-.2/bin/:/home/users/xmuyong/.jumbo/bin/core_perl:/home/users/xmuyong/.jumbo/bin:/opt/compiler/gcc-4.8.2/bin/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opin:/home/opt/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin:/home/opt/bin:/home/users/xmuyong/bin', 'LANG': 'en_US.UTF-8', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'TERM': 'xter 'SHELL': '/bin/bash', 'QTINC': '/usr/lib64/qt-3.3/include', 'JUMBO_ROOT': '/home/users/xmuyong/.jumbo', 'G_BROKEN_FILENAMES': '1', 'HISTSIZE': '1000', 'MANPATH': '/homsers/xmuyong/.jumbo/share/man:/home/users/xmuyong/.jumbo/share/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/share/man', 'HOME': '/home/rs/xmuyong', 'MODULESHOME': '/usr/share/Modules', '_': '/home/users/xmuyong/.jumbo/bear/usr/local/bin/bear', 'MODULEPATH': '/usr/share/Modules/modulefiles:/etc/modfiles', 'LD_PRELOAD': '/home/users/xmuyong/.jumbo/bear/usr/local/lib64/bear/libear.so', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;0d=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rp1;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:ga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*v=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'SSH_TTY': '/dev/pts/0', 'OWD': '/home/users/xmuyong/projectcode/appdemo/baidu/feed-q', 'LOADEDMODULES': '', 'HISTCONTROL': 'ignoredups', 'SHLVL': '2', 'PWD': '/home/users/xmuyong/projectcodppdemo/baidu/feed-q/appdemo', 'INTERCEPT_BUILD_TARGET_DIR': '/tmp/intercept-v7wl0p', 'MAIL': '/var/spool/mail/xmuyong', 'SSH_CONNECTION': ''}

make: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/compiler/gcc-4.8.2/lib/libpthread.so.0)
bear: DEBUG: run_build: build finished with exit code: 1

### Environment

- OS name & version:
-- lsb_relase -a
LSB Version:    :core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.3 (Final)
Release:        6.3
Codename:       Final

- Bear version:
--  ~/.jumbo/bear/usr/local/bin/bear --version
bear 2.4.0

- Any reference to the project that you running against:
-- strings /lib64/libc.so.6 |grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE

-- ldd  /opt/compiler/gcc-4.8.2/lib/libpthread.so.0
/opt/compiler/gcc-4.8.2/lib/libpthread.so.0: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/compiler/gcc-4.8.2/lib/libpthread.so.0)
        linux-vdso.so.1 =>  (0x00007fffda9a2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f23f47de000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f23f4b70000)

- Any information about the compiler that this project is using:
--  /usr/bin/g++ --version
g++ (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

--  g++ --version
g++ (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

-- type g++
g++ is hashed (/opt/compiler/gcc-4.8.2/bin/g++)

================================================
May be  "/opt/compiler/gcc-4.8.2/lib64/libc.so.6"  should be used ， but  I do not know how to fix it.

Thanks!

**Comment by rizsotto** [comment]
Hey @xmuyong , thanks for the report. In the output you've sent I saw:

```
PATH': '/home/users/xmuyong/.BCloud/bin:/home/users/xmuyong/.jumbo/bin/core_perl:/home/users/xmuyong/.jumbo/bin:/opt/compiler/gcc-.2/bin/:/home/users/xmuyong/.jumbo/bin/core_perl:/home/users/xmuyong/.jumbo/bin:/opt/compiler/gcc-4.8.2/bin/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opin:/home/opt/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin:/home/opt/bin:/home/users/xmuyong/bin'
```

As you can see, the `/opt/compiler/gcc-4.8.2/bin/` is before the `/usr/bin`, so I presume it executes that compiler and not the one you've hoped for.

Did you run the build command without Bear and it did succeeded? Bear does not change the `PATH` variable, so it should not cause this failure.

**Comment by xmuyong** [comment]
> Hey @xmuyong , thanks for the report. In the output you've sent I saw:
> 
> ```
> PATH': '/home/users/xmuyong/.BCloud/bin:/home/users/xmuyong/.jumbo/bin/core_perl:/home/users/xmuyong/.jumbo/bin:/opt/compiler/gcc-.2/bin/:/home/users/xmuyong/.jumbo/bin/core_perl:/home/users/xmuyong/.jumbo/bin:/opt/compiler/gcc-4.8.2/bin/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opin:/home/opt/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin:/home/opt/bin:/home/users/xmuyong/bin'
> ```
> 
> As you can see, the `/opt/compiler/gcc-4.8.2/bin/` is before the `/usr/bin`, so I presume it executes that compiler and not the one you've hoped for.
> 
> Did you run the build command without Bear and it did succeeded? Bear does not change the `PATH` variable, so it should not cause this failure.

Thanks for you help!

If I run the build command without Bear, it can succeed.  And I know the reason:

Bear requires :  /opt/compiler/gcc-4.8.2/lib/libpthread.so.0 and /opt/compiler/gcc-4.8.2/lib/libpthread.so.0 requires  /lib64/libc.so.6 . 

See the next command:


-- ldd /opt/compiler/gcc-4.8.2/lib/libpthread.so.0 
/opt/compiler/gcc-4.8.2/lib/libpthread.so.0: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/compiler/gcc-4.8.2/lib/libpthread.so.0)
        linux-vdso.so.1 =>  (0x00007ffc2513c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9d02c40000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9d02fd2000)

**Comment by rizsotto** [comment]
Which part of Bear is depend on that `libpthread.so`? The executable `bear` is a Python script, which might depend only if your Python is compiled against it. The library `libear.so` might depend on, but then you need to recompile it. (By the way, how did you install Bear on that machine?)

**Comment by rizsotto** [comment]
Seems to be an installation issue. I'm closing it. Please reopen/comment this issue if you still have problem with it.

**Comment by xmuyong** [comment]
> Which part of Bear is depend on that `libpthread.so`? The executable `bear` is a Python script, which might depend only if your Python is compiled against it. The library `libear.so` might depend on, but then you need to recompile it. (By the way, how did you install Bear on that machine?)

I install Bear using the following command:

-- cmake -DCMAKE_INSTALL_PREFIX=~/.jumbo/bear/
-- make all
-- make install

How can i recompile it without using 'libpthread.so' 

Thanks~

**Comment by rizsotto** [comment]
You can't do that. The `libear.so` is depending on the `libthread.so`. When you recompile, you should remove the `/opt/compiler/gcc-4.8.2/bin` from your `PATH`. So, it won't pick the wrong PThread library, but the one from the system.
