### ISSUE TITLE
Empty compile_commands.json on tinyssh

### ISSUE THREAD

**Issue by anne-pacalet** [rizsotto/Bear#257]
### Expected Behavior

Generate a non empty database on [tinyssh](https://github.com/janmojzis/tinyssh).

### Actual Behavior

Running this command gives an empty database:
```
$ git clone https://github.com/janmojzis/tinyssh
$ cd tinyssh
$ bear ./make-tinyssh.sh
```

I also tried : 
- `CC=clang bear ./make-tinyssh.sh`
- `CC=gcc bear ./make-tinyssh.sh`

When using the `-vvvv` option, I get many messages similar to : 
```
bear: parse exec trace file: /tmp/bear-u2avo_w8/3042.cmd
bear: parse exec trace file: /tmp/bear-u2avo_w8/3043.cmd
bear: parse exec trace file: /tmp/bear-u2avo_w8/3044.cmd
bear: format this command: ['gcc', '-pedantic', '-Wall', '-Wno-long-long', '-Wno-overlength-strings', '-Wno-unused-function', '-Wshadow', '-Wdeclaration-after-statement', '-Wwrite-strings', '-Wmissing-declarations', '-Wmissing-prototypes', '-Wstrict-prototypes', '-Wunused-value', '-Wunused-parameter', '-Wundef', '-fstack-protector-strong', '-fwrapv', '-fno-strict-overflow', '-Os', '-fomit-frame-pointer', '-funroll-loops', '-I/home/anne/GitTis/USE/tinyssh-tis-ci/tinyssh-sources/build/include', '-c', 'uint32_pack.c']
bear: formated as: ['cc', '-c', '-pedantic', '-Wall', '-Wno-long-long', '-Wno-overlength-strings', '-Wno-unused-function', '-Wshadow', '-Wdeclaration-after-statement', '-Wwrite-strings', '-Wmissing-declarations', '-Wmissing-prototypes', '-Wstrict-prototypes', '-Wunused-value', '-Wunused-parameter', '-Wundef', '-fstack-protector-strong', '-fwrapv', '-fno-strict-overflow', '-Os', '-fomit-frame-pointer', '-funroll-loops', '-I/home/anne/GitTis/USE/tinyssh-tis-ci/tinyssh-sources/build/include', '/home/anne/GitTis/USE/tinyssh-tis-ci/tinyssh-sources/build/work/uint32_pack.c']
bear: parse exec trace file: /tmp/bear-u2avo_w8/3045.cmd
bear: parse exec trace file: /tmp/bear-u2avo_w8/3046.cmd
bear: parse exec trace file: /tmp/bear-u2avo_w8/3047.cmd
```
so it seems that `bear` can catch some commands, but the generated JSON file is still empty.

### Environment

- OS name & version: Linux - Xubuntu 16.04
- Bear version: bear 2.1.5
- Any reference to the project that you running against: https://github.com/janmojzis/tinyssh
- Any information about the compiler that this project is using: the `make-tinyssh.sh` script configures, compiles and tests everything.

**Comment by rizsotto** [comment]
Hey Anne, thanks for the report. Could you check if the latest version of Bear suffers the same problem? (The 2.1.5 is more than 3 years old version.) The `README.md` file has instruction how to build and install from source. (But feel free to ask questions if you need.)

**Comment by anne-pacalet** [comment]
Thanks for your answer. Yes, I have an old Ubuntu ! I'll try to compile from the `master` branch then.

**Comment by anne-pacalet** [comment]
OK, now `bear --version` gives `2.4.0`.
When running `make check`, I got `No tests were found!!!`, but I think it is not a serious problem, is it?
With `-vvvv`, I now have outputs like:
```
bear: DEBUG: parse_exec_trace: parse exec trace file: /tmp/intercept-a2kEYb/execution.g1Amfo
bear: DEBUG: _split_command: input was: [u'gcc', u'-pedantic', u'-Wall', u'-Wno-long-long', u'-Wno-overlength-strings', u'-Wno-unused-function', u'-Wshadow', u'-Wdeclaration-after-statement', u'-Wwrite-strings', u'-Wmissing-declarations', u'-Wmissing-prototypes', u'-Wstrict-prototypes', u'-Wunused-value', u'-Wunused-parameter', u'-Wundef', u'-fstack-protector-strong', u'-fwrapv', u'-fno-strict-overflow', u'-Os', u'-fomit-frame-pointer', u'-funroll-loops', u'-DCOMPILER="gcc"', u'-DVERSION="noversion"', u'-I/home/anne/GitTis/USE/tinyssh-tis-ci/tinyssh-sources/build/include', u'-c', u'stringparser.c']
bear: DEBUG: _split_command: output is: CompilationCommand(compiler=u'gcc', language=0, phase=[u'-c'], flags=[u'-pedantic', u'-Wall', u'-Wno-long-long', u'-Wno-overlength-strings', u'-Wno-unused-function', u'-Wshadow', u'-Wdeclaration-after-statement', u'-Wwrite-strings', u'-Wmissing-declarations', u'-Wmissing-prototypes', u'-Wstrict-prototypes', u'-Wunused-value', u'-Wunused-parameter', u'-Wundef', u'-fstack-protector-strong', u'-fwrapv', u'-fno-strict-overflow', u'-Os', u'-fomit-frame-pointer', u'-funroll-loops', u'-DCOMPILER="gcc"', u'-DVERSION="noversion"', u'-I/home/anne/GitTis/USE/tinyssh-tis-ci/tinyssh-sources/build/include'], files=[u'stringparser.c'], output=[])
```
But the `compile_commands.json` is still empty (I mean, not really empty, but just `[]`).

**Comment by rizsotto** [comment]
Thanks to coming back Anne. (Yes, the `make check` failure is not important.) But the empty output is.

The logs looks promising. The compiler call was captured in a trace file. It was classified as a compilation... but it might be filtered out afterwards. One reason for that could be the source files is not found.

As a quick look it might be a bug. I will try to fix it today later.

As a workaround, you can remove the file check (line 578-578) and replace with a simple `yield result`.

**Comment by anne-pacalet** [comment]
Your workaround seems to work: at least the generated file is not empty anymore. Thanks!

**Comment by anne-pacalet** [comment]
Well, it seems that there is still a problem and that the source files are not in the given directory, so I cannot use the generated file.
I hope that you'll find the problem... Thanks.

**Comment by anne-pacalet** [comment]
I think that you can close this ticket, because it is not `bear`'s fault! It seems that the tinyssh script copies source files to compile them in a `work` directory, and that it erases the copies after compilation, that is why they are not found there at the end.
Sorry for the noise, and thank you for your answers anyway!

**Comment by rizsotto** [comment]
Glad that you've found it. It's very rare that build process does copy away files. (I only know about that `gcc` build does delete generated source files after the library is built.) Shall be a reason why developers did this. Unfortunately then Bear won't help you much here.

Thanks for sharing your findings.
