### ISSUE TITLE
Should we ignore the option look like "-Wp,-MD,/usr1/xxx.o.d" ?

### ISSUE THREAD

**Issue by zhangxiaobin2** [rizsotto/Bear#258]
Should we ignore the option look like "-Wp,-MD,/usr1/xxx.o.d" ?

I know that Bear has already ignore the option "-Wl,option" by regularexpression "^-(l|L|Wl,).+".
But recently in our project, we find the option  look like "-Wp,-MD,/usr1/xxx.o.d", I think it's not important for clang to do the compile and static analysis. 

Because gcc option explanation say:
`-Wp,option
You can use -Wp,option to bypass the compiler driver and pass option directly through to the preprocessor. If option contains commas, it is split into multiple options at the commas. However, many options are modified, translated or interpreted by the compiler driver before being passed to the preprocessor, and -Wp forcibly bypasses this phase. The preprocessor’s direct interface is undocumented and subject to change, so whenever possible you should avoid using -Wp and let the driver handle the options instead.`

I don't know if we could ignore all the options after “-Wp,****”?   I think it's not important for clang to do the compile and static analysis.  If could, we can use the regular expression "^-(Wp,).+" to ignore this option :)

**Comment by rizsotto** [comment]
Hey @zhangxiaobin2 , thanks for the report.

I'm wondering what would be the benefit to filter the `-Wp.*` flags? Would that be causing problems for project which was using it? (The `-MD` flag will not harm if we filter that out, but might be other important preprocessor flags which might break the build if it's missing.)

So, my first impression that I would not filter those flags out. But willing to change my mind if you come up with some good reason. What do you think?

**Comment by zhangxiaobin2** [comment]
Hi @rizsotto , thanks.

What I want to do is collect the compiler options for Clang to do the static analysis. I know that "-Wp,-MD,xxxxx.o.d" is not important for Clang to do it,  but I'm not very familiar with the gcc options "-Wp,****", maybe it would be very useful for the preprocesor . 

I will look up some more detal data for this option by myself :)
Thanks again for your reply :)
I will close this issue :)
