### ISSUE TITLE
Why does the libear capture posix_spawn/posix_spawnp?

### ISSUE THREAD

**Issue by Qchrlis** [rizsotto/Bear#259]
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

### Expected Behavior
`
       #include <spawn.h>
       #include <stdio.h>
       #include <unistd.h>
       #include <stdlib.h>
       #include <string.h>
       #include <wait.h>
       #include <errno.h>

       #define errExit(msg)    do { perror(msg); \
                                    exit(EXIT_FAILURE); } while (0)

       #define errExitEN(en, msg) \
                               do { errno = en; perror(msg); \
                                    exit(EXIT_FAILURE); } while (0)

       char **environ;

       int
       main(int argc, char *argv[])
       {
           pid_t child_pid;
           int s, opt, status;
           sigset_t mask;
           posix_spawnattr_t attr;
           posix_spawnattr_t *attrp;
           posix_spawn_file_actions_t file_actions;
           posix_spawn_file_actions_t *file_actionsp;

           /* Parse command-line options, which can be used to specify an
              attributes object and file actions object for the child. */

           attrp = NULL;
           file_actionsp = NULL;

           while ((opt = getopt(argc, argv, "sc")) != -1) {
               switch (opt) {
               case 'c':       /* -c: close standard output in child */

                   /* Create a file actions object and add a "close"
                      action to it */

                   s = posix_spawn_file_actions_init(&file_actions);
                   if (s != 0)
                       errExitEN(s, "posix_spawn_file_actions_init");

                   s = posix_spawn_file_actions_addclose(&file_actions,
                                                         STDOUT_FILENO);
                   if (s != 0)
                       errExitEN(s, "posix_spawn_file_actions_addclose");

                   file_actionsp = &file_actions;
                   break;

               case 's':       /* -s: block all signals in child */

                   /* Create an attributes object and add a "set signal mask"
                      action to it */

                   s = posix_spawnattr_init(&attr);
                   if (s != 0)
                       errExitEN(s, "posix_spawnattr_init");
                   s = posix_spawnattr_setflags(&attr, POSIX_SPAWN_SETSIGMASK);
                   if (s != 0)
                       errExitEN(s, "posix_spawnattr_setflags");

                   sigfillset(&mask);
                   s = posix_spawnattr_setsigmask(&attr, &mask);
                   if (s != 0)
                       errExitEN(s, "posix_spawnattr_setsigmask");

                   attrp = &attr;
                   break;
               }
           }

           /* Spawn the child. The name of the program to execute and the
              command-line arguments are taken from the command-line arguments
              of this program. The environment of the program execed in the
              child is made the same as the parent's environment. */

           s = posix_spawnp(&child_pid, argv[optind], file_actionsp, attrp,
                            &argv[optind], environ);
           if (s != 0)
               errExitEN(s, "posix_spawn");

           /* Destroy any objects that we created earlier */

           if (attrp != NULL) {
               s = posix_spawnattr_destroy(attrp);
               if (s != 0)
                   errExitEN(s, "posix_spawnattr_destroy");
           }

           if (file_actionsp != NULL) {
               s = posix_spawn_file_actions_destroy(file_actionsp);
               if (s != 0)
                   errExitEN(s, "posix_spawn_file_actions_destroy");
           }

           printf("PID of child: %ld\n", (long) child_pid);

           /* Monitor status of the child until it terminates */

           do {
               s = waitpid(child_pid, &status, WUNTRACED | WCONTINUED);
               if (s == -1)
                   errExit("waitpid");

               printf("Child status: ");
               if (WIFEXITED(status)) {
                   printf("exited, status=%d\n", WEXITSTATUS(status));
               } else if (WIFSIGNALED(status)) {
                   printf("killed by signal %d\n", WTERMSIG(status));
               } else if (WIFSTOPPED(status)) {
                   printf("stopped by signal %d\n", WSTOPSIG(status));
               } else if (WIFCONTINUED(status)) {
                   printf("continued\n");
               }
           } while (!WIFEXITED(status) && !WIFSIGNALED(status));

           exit(EXIT_SUCCESS);
       }
`
-> strace -f -v ./a.out -c /bin/ls

### Actual Behavior
http://man7.org/linux/man-pages/man3/posix_spawn.3.html
http://man7.org/linux/man-pages/man2/execve.2.html

I find that the ear has captured **posix_spawn/spawnp**, but the interface will call **execve** when run the real program

I think that the wrapper is not necessary, can you tell me the truth?

### Environment
unbuntu 16.04 64bit

- OS name & version: Linux 
- Bear version: newest
- Any reference to the project that you running against: no
- Any information about the compiler that this project is using: gcc

**Comment by rizsotto** [comment]
Hey @Qchrlis , good question. Sometimes theory does not match implementation. It was long before (even before version 1.0) when `qmake` project produced empty compilation databases. The `execve` was already implemented, but was not capture the `posix-spawn` process executions.

And what I have learned in the last few years (since this project is out there), that different platform implement `exec*` method differently. The wrapper function might not be needed on your version of ubuntu, but might needed on other platforms.

**Comment by Qchrlis** [comment]
I find the `posix_spawn` does not call `execve` on mac system, can we add a macro to close the wrapper on linux platform by __APPLE__ and __APPLE_CC__

**Comment by rizsotto** [comment]
I have concern about this solution. The `exec*` and the `posix_spawn` are implemented in the `libc.so`. You've checked that ubuntu's current glibc does behave this way. I had experienced that glibc did different thing in 2012. Alpine linux does use musl c library, which might do something else.

What would be the benefit to kill the `posix_spawn` wrapper function in `libear.so`?
