### ISSUE TITLE
Support ccache when ccache .. "caches"

### ISSUE THREAD

**Issue by TTimo** [rizsotto/Bear#263]
I think it would be great to support ccache even when it caches and bypasses the compiler execution. My use is as follows:

- I have my project built, and it uses ccache. The latest is built so everything is cached.
- I want to create or refresh my compilation database.
- If I make clean and make again, ccache intercepts everything, my compilation database is empty.
- I need to purge ccache or do a clean build without using it to get a compilation database.

I think we'd have to do that by parsing the rest of the command line and interpret it as if it was intercepted from one of the compiler commands being monitored.

**Comment by rizsotto** [comment]
Hey Tim, thanks to bring this up. I have thought that Bear deals with the compiler wrappers (like `ccache`or `distcc`) well. But has no test for it. :) Needs to fix it, I agree.

Can you help me and send the verbose output of Bear when the `ccache` has the cached files? Thanks in advance.

**Comment by TTimo** [comment]
I can't reproduce anymore .. it must have been a problem on my end.
