### ISSUE TITLE
Bear doesn't hook the compilers when used with wine on my system.

### ISSUE THREAD

**Issue by Guy1524** [rizsotto/Bear#267]
[Log](https://paste.ubuntu.com/p/DkTN3dj2MJ/)
(I terminated it manually to show the problem)

### Expected Behavior
Of course, bear should hook GCC and MINGW, but on my system, it hooks neither

### Actual Behavior
Bear does run, but compile_commands.json isn't even created.

### Environment

- OS name & version: Arch Linux
- Bear version: master as of posting this (c3c3537)
- Any reference to the project that you running against: wine
- Any information about the compiler that this project is using: This project uses both GCC and MINGW, neither of which Bear hooks.

**Comment by rizsotto** [comment]
Hey @Guy1524 , thanks for the report.

Bear has a test suite which covers basic functionalities. Your case must be somewhat special. Help me to find those... One example, could you check what are the type of binaries which involved in the build process. Use the `file` command against the `make`, `gcc` binaries. (I presume it's either statically linked, or is different architecture (32 bit vs 64 bit) than Bear's library. You can read about these cases in the README file "Known issues" section.)

**Comment by Guy1524** [comment]
Sorry for the late response.

`file /usr/local/lib/bear/libear.so 
/usr/local/lib/bear/libear.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=242031678406ae53da53b5a34de4e77aefeafc80, not stripped`

`file /usr/bin/make
/usr/bin/make: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=ee6ddb0bd234493b1d8459809cf8de25a86fa8c1, stripped`

`file /usr/bin/gcc
/usr/bin/gcc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=6c933191c2d69f05992206d54156de17c83a8249, for GNU/Linux 3.2.0, stripped`

One thing I noted is that when executing bear in a subdirectory, dlls/ntdll for example, bear would correctly generate the compile_commands.json file, but the compiler would also get executed, I'm not sure whether this is intended behavior.

**Comment by Guy1524** [comment]
Something else that may or may not be relevant is that when I launch make though `bear /bin/sh -c "make"`, an empty database is generated.

**Comment by Guy1524** [comment]
I've found the issue, bear only outputs the JSON once compilation is finished, while I was checking a lot sooner since compilation is very slow without -jN.  Sorry for the noise.
