### ISSUE TITLE
Add feature to suppress unsported compiler flags (clang<->gcc)

### ISSUE THREAD

**Issue by DeadRabbits307** [rizsotto/Bear#268]
Like shown [here](https://stackoverflow.com/questions/57082124/how-to-integrate-clang-tidy-to-cmake-and-gcc)  it would be great to have the possibility, to tell Bear suppressing unsupported compiler flags in the compile_commands.json.

**Comment by rizsotto** [comment]
The primary purpose of this tool is to create the compilation database, not to manipulate, not to formate.
But I'm not against the idea to extend the scope.

Your request is noted. Will work on it in the future. Thanks for the idea.

**Comment by DeadRabbits307** [comment]
Your welcome:)

**Comment by rizsotto** [comment]
This is implemented on the latest `devel` branch. Will be released as `3.0.13`.
