### ISSUE TITLE
Is there any tutorial to understand the bear?\

### ISSUE THREAD

**Issue by amithrc** [rizsotto/Bear#270]
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

### Expected Behavior
I am trying to build a large project to create a compile_database so I can use the clion to open it. It is a make project. I am not sure what command to use. I just used bear make . (It has many directories)

### Environment

- OS name & version:
- Bear version:
- Any reference to the project that you running against:
- Any information about the compiler that this project is using:

**Comment by rizsotto** [comment]
Bear has a `man` page and the `README.md` files tries to clarify the usage scenarios and describes the known limitation of the tool.

You need to install it, and then you can run it. `bear <build command>` shall do the work. (In your case it's `bear make`.) It will produce a `compile_commands.json` in the current directory.

Let me know if any of these were not described in the documentation.
