### ISSUE TITLE
 bear: DEBUG: run_build: build finished with exit code: -11 sdclang failed

### ISSUE THREAD

**Issue by easymaddy** [rizsotto/Bear#272]
Hi, I followed the steps for multilib support and built the bear from source and installed the libs

-----

$ file /usr/local/lib64/bear/libear.so
/usr/local/lib64/bear/libear.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f91417a6dbbecd89ad0e452743a0c66d75d0667e, not stripped
$ file /usr/local/lib/bear/libear.so
/usr/local/lib/bear/libear.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=4af2b86c639a8dd4587c2ec65e9a131fd9fc5799, not stripped
-----

However, while compiling my code using the below cmd I get the exit code -11
nice -$NICE_LEVEL /usr/local/bin/bear -vvvv -libear /usr/local/lib/bear/libear.so make $MAKE_ARGS release 2>&1

Errors: Dump of the environment followed by below error
bear: DEBUG: run_build: build finished with exit code: -11 sdclang failed

BTW: MY code is being compiled using the following compiler 
dmucs_gethost distcc /usr/wrs/WindRiver68a/gnu/4.1.2-vxworks-6.8/x86-linux2/bin/ccmips
However the libear.so was built using native RH gcc.
[bravva@acme201 bravva_ZEETEST]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16.0.3) (GCC)

Hope you could help.
Thanks in advance

**Comment by rizsotto** [comment]
Hi @easymaddy , thanks for the report.

Is there any reason why the libraries installed in `/usr/local/lib/bear` instead of  `/usr/local/lib`?
