### ISSUE TITLE
Empty compile_commands.json ([]) on OpenBSD

### ISSUE THREAD

**Issue by wataash** [rizsotto/Bear#283]
UPDATED: OpenBSD's `/bin/sh` is statically linked, so bear's interception of exec(3) and posix_spawn(3) is impossible.
A workaround is replacing `/bin/sh` with `/usr/pkg/bin/bash` installed via pkgsrc. (BE CAREFUL to do so!)

```sh
sudo cp -v /bin/sh /bin/sh.orig
sudo cp -v /usr/pkg/bin/bash
bear ...
# don't forget to restore
sudo cp -v /bin/sh.orig /bin/sh
```

# Original description

```hs
$ bear sh -c 'cc a.c'
$ cat compile_commands.json
[]
```

On OpenBSD, exec(3) seem to be impossible to be intercepted with `LD_PRELOAD` (it's not surprising because OpenBSD is a security-oriented OS) so some hack would be needed on OpenBSD's side.

Note: as discussed in https://github.com/rizsotto/Bear/issues/212#issuecomment-596212132 , `bear -vvvv` indicates that apparently exec(3) interception is succeeded, but what we actually saw was intercepting of posix_spawn(3). (I found it by debugging libear)

```hs
$ bear -vv sh -c 'cc a.c'
...
bear: DEBUG: build finished with exit code: 0
bear: DEBUG: parse exec trace file: /tmp/intercept-u8xpw8g_/execution.000009202.875205876.as1Kun
bear: DEBUG: input was: ['/usr/bin/cc', '-cc1', '-triple', 'amd64-unknown-openbsd6.6', '-emit-obj', '-mrelax-all', '-disable-free', '-disable-llvm-verifier', '-discard-value-names', '-main-file-name', 'a.c', '-mrelocation-model', 'pic', '-pic-level', '1', '-pic-is-pie', '-mthread-model', 'posix', '-mdisable-fp-elim', '-relaxed-aliasing', '-masm-verbose', '-mconstructor-aliases', '-munwind-tables', '-target-cpu', 'x86-64', '-target-feature', '+retpoline-indirect-calls', '-target-feature', '+retpoline-indirect-branches', '-dwarf-column-info', '-debugger-tuning=gdb', '-resource-dir', '/usr/lib/clang/8.0.1', '-fdebug-compilation-dir', '/root/Bear/build-debug/libear', '-ferror-limit', '19', '-fmessage-length', '106', '-fwrapv', '-D_RET_PROTECTOR', '-ret-protector', '-fobjc-runtime=gnustep', '-fdiagnostics-show-option', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-valloc', '-fno-builtin-free', '-fno-builtin-strdup', '-fno-builtin-strndup', '-o', '/tmp/a-1a392a.o', '-x', 'c', 'a.c', '-faddrsig']
...
```

I guess this call of posix_spawn(3) comes from `cc` (clang).
If we could intercept exec(3), we should see the invocation of `cc a.c` (as we can see on Linux):

```hs
$ bear -vv sh -c 'cc a.c'
...
bear: DEBUG: build finished with exit code: 0
bear: DEBUG: parse exec trace file: /tmp/intercept-qkS9eX/execution.000067376.401374226.wtgV9v
bear: DEBUG: input was: [u'cc', u'a.c']
bear: DEBUG: output is: CompilationCommand(compiler=u'cc', language=0, phase=[], flags=[], files=[u'a.c'], output=[])
...
```

And the Python implementation doesn't regard `['/usr/bin/cc', '-cc1', '-triple', ...]` as a compile command, resulting into an empty compilation database.

I'll investigate more on OpenBSD's LD_PRELOAD when I have time...

## Environment

```hs
$ uname -a
OpenBSD wshob.my.domain 6.6 GENERIC#353 amd64

$ cc --version
OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: amd64-unknown-openbsd6.6
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by rizsotto** [comment]
Thanks @wataash for this report. I am working with another interception method (using compiler wrapper), which might solve this issue. And the other option could be to not ignore the Clang internal `-cc1` and try to make an entry from that.

**Comment by acse-fk4517** [comment]
I am also having the same issue on Mac OS 10.15.6. When I run Bear Make I get an empty JSON array in my compile_commands.json file.

**Comment by wataash** [comment]
Thanks for info, but macOS's problem is another one, which is described in [README](https://github.com/rizsotto/Bear#empty-compilation-database-on-os-x--macos-or-fedora).

**Comment by wataash** [comment]
I found out OpenBSD's `/bin/sh` was statically linked.
I'm sorry for having ignored [your commoent](https://github.com/rizsotto/Bear/issues/212#issuecomment-596267739)...

> Is the `sh` dynamically liked?

I successfully generated a non-empty compdb by replacing `/bin/sh` with a dynamicall-linked shell (e.g. `/usr/pkg/bin/bash` installed via pkgsrc).
With OpenBSD's make we can't change the spawning shell because [`sh` is hard-coded](https://github.com/openbsd/src/blob/04a3844d92fbbfec14bca46cc2a9339711abceeb/usr.bin/make/cmd_exec.c#L57).

Replacing `/bin/sh` temporally for bear is tedious and dangerous, so changing it by bear's LD_PRELOAD hack would be nice:

```sh
bear --make-shell=/usr/pkg/bin/bash make
```

Or this should be done by another small program:

```sh
a-small-program-replacing-make-shell-by-LD_PRELOAD /usr/pkg/bin/bash bear make
```

**Comment by rizsotto** [comment]
The new version takes too long (or just having not much free time to work on it). But if the build system is supporting `CC` and `CXX` variables, static build tools like `make` or `sh` won't be an issue for compiler wrappers. Sorry about the long waiting, the new version (with the compiler wrappers) will come soon.

**Comment by rizsotto** [comment]
Hey @wataash , there is a release candidate on master branch now, which suppose to fix this issue. Could you give it a try for that?

I'm closing this ticket now, but will re-open if the bug still there.

**Comment by cpdean** [comment]
> Thanks for info, but macOS's problem is another one, which is described in [README](https://github.com/rizsotto/Bear#empty-compilation-database-on-os-x--macos-or-fedora).
> You have to disable SIP (System Integrity Protection).

For others trying to troubleshoot this on macOS, [this is what was removed from the readme](https://github.com/rizsotto/Bear/commit/748d310381974ccf7438237f545ee9d6dbe60d87#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L167-L185)

I wanted to use bear to build a `compile_commands.json` for clangd.  I was able to do this on macOS without disabling SIP by using `intercept-build` from https://github.com/rizsotto/scan-build
