### ISSUE TITLE
Feedback on packaging issues

### ISSUE THREAD

**Issue by rizsotto** [rizsotto/Bear#285]
I'm working on 3.0 release of Bear, which can be found on the `devel` branch. As a new thing, it has 3rd party libraries as dependencies. I'm looking for feedback related to the dependency handling of the project. What would be the acceptable or preferable to packaging point of view.

Thanks for any comments!

@sebastinas @mlq @neverpanic @babathriviere

**Comment by sebastinas** [comment]
After a first try, it seems that building with the system libraries does not work. Even if installed and requested to build with system library, `cmake` fails with
```
CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2962 (get_property):
  get_property could not find TARGET spdlog.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3239 (_ep_add_configure_command)
  CMakeLists.txt:103 (ExternalProject_Add)


CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2964 (get_property):
  get_property could not find TARGET spdlog.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3239 (_ep_add_configure_command)
  CMakeLists.txt:103 (ExternalProject_Add)


CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:1783 (get_property):
  get_property could not find TARGET spdlog.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2064 (ExternalProject_Get_Property)
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2966 (_ep_get_step_stampfile)
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3239 (_ep_add_configure_command)
  CMakeLists.txt:103 (ExternalProject_Add)


CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:1785 (message):
  External project "spdlog" has no stamp_dir
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2064 (ExternalProject_Get_Property)
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2966 (_ep_get_step_stampfile)
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3239 (_ep_add_configure_command)
  CMakeLists.txt:103 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!
See also "/home/sebastian/development/Bear/build/CMakeFiles/CMakeOutput.log".
```

This is not specific to spdlog. I had the same issue with the others as well. So far I cannot say more than using system libraries does not work.

**Comment by rizsotto** [comment]
Thanks @sebastinas , for your quick response. Can I ask how did you tried to compile it?

With CMake there are many way to deal with 3rd party dependencies. Some, might require to fetch binaries or source code during the build process. I wanted to avoid that. (But it's also an input that I am looking from you.)

Will tell how I imagined the packaging. (Not sure what are the right terms in debian or other distros, so please forgive me if I incorrectly using these terms.)

1. Include the 3rd parties in the source package. (Which means it needs to do a `git submodule init ...` and take all sources from it.)
2. Use this repo source files only, and use the `CMakeLists.txt` file from the root of the repository. Pass the `USE_SYSTEM_...` flags while building.
3. Use only this repo source files, and use the `CMakeLists.txt` file from the `source` directory. That will also require a few flags to pass (`-Dspdlog_DIR`, `-DgRPC_DIR`, etc... to fix CMake's `find_package(...)` calls.) And run the test separately from the package creation. (Maybe as an extra step after the package built and installed.)

The last two has the benefit to not include the dependencies in the source package, and shorter compilation times. While the first one can ensure that all dependency is compiled as it was planed. (Static library and `-fno-exception` and `-fno-rtti` flags might be those things which are relevant.)

I was testing the 1st and 3rd option, but not the 2nd. (Will look into it if you are saying that was not working for you.) I also did not find a way how to install the files with option 1 and 2. (Option 3 works without any change.)

**Comment by sebastinas** [comment]
I tried 2. with a combination various combinations of `USE_SYSTEM_ ...` flags. For the Debian package I will use 3., but not all dependencies are packaged at the moment. Once they are, I'll try 3. again.

**Comment by rizsotto** [comment]
Another topic I would like to hear your thoughts... Bear will have new executables. One of them is a wrapper program (compiler wrapper and linker wrapper) which requires special installation. Here is my proposed solution:

- The executable `wrapper` would installed as `/usr/libexec/bear/wrapper` by CMake.
- The package post-install script would create (soft) links to it as `/usr/libexec/bear/cc`. (And with many other names such `c++`, `as`, `ld`, `ar`, etc...)

Or we can separate the soft links more as install the `wrapper` as `/usr/libexec/bear/wrapper`, but create a `/usr/libexec/bear/bin/` directory for all the soft links. The idea is the same, have a directory that `bear` will use to insert into the front of `PATH` directory lists, so this programs will be executed instead of the real compilers.

I think the compiler wrapper creation should be done as a post install step. I think the package installation can make smarter decision about details (like shall it be a link or require a copy of the binary). But it needs to inject the the `bin` location to build time, so `bear` can set up the environment variables properly.

The other solution could be if `bear` creates a temporary directory and creates the links before run the build command. This solution would involve a lot more logic in the `bear` and because it might need to keep the created directory across runs (eg.: `./configure` and `make`) it might be tricky to do. I prefer the pre-created wrapper links.

Do you think the proposed solution would work? What's your opinion on it?

**Comment by sebastinas** [comment]
That essentially what `ccache` does. As post-installation step (and whenever a compiler gets installed or removed), it runs https://sources.debian.org/src/ccache/3.7.9-1/debian/update-ccache-symlinks.in/ to populate `/usr/lib/ccache` with symlinks.

We can implement that in the `bear` package too.

**Comment by rizsotto** [comment]
Hey guys, I've just created a release candidate for 3.0. It's on master now. I would like to hear some feedback from you before it gets released. (Was thinking to do that at the end of this month, depending how much trouble we will have.)

And would like to use this opportunity to thank you for your time and efforts to make package for this project!

**Comment by hexchain** [comment]
It seems that Arch and Debian do not have `/usr/libexec`, but currently there is no way to override that. Setting `CMAKE_INSTALL_LIBEXECDIR` does not have any effect as it is not passed down in the `ExternalProject` definition of bear.

**Comment by rizsotto** [comment]
Thanks @hexchain for your comment. Would it be enough to propagate the `CMAKE_INSTALL_LIBEXECDIR` to the `ExternalProject`? Or shall we choose another location to store those files?

My thoughts was not to put the `libexec.so` into the `/usr/lib` because I would like to avoid to link against it. And the `er` and the wrappers shall also not in the `PATH` so, those shall not go into `/usr/bin`.

**Comment by hexchain** [comment]
I've tried locally and I think it would be enough. On Arch, libexecdir usually should be `/usr/lib/bear`.

**Comment by sebastinas** [comment]
> Thanks @hexchain for your comment. Would it be enough to propagate the `CMAKE_INSTALL_LIBEXECDIR` to the `ExternalProject`? Or shall we choose another location to store those files?
> 
> My thoughts was not to put the `libexec.so` into the `/usr/lib` because I would like to avoid to link against it. And the `er` and the wrappers shall also not in the `PATH` so, those shall not go into `/usr/bin`.

FWIW, in Debian we install the helper libraries in `/usr/lib/$triplet/bear/`, i.e. `CMAKE_INSTALL_LIBDIR/bear`. Thereby the library is not available on the default linker path, but we can still support multi-arch scenarios (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856333).

**Comment by rizsotto** [comment]
@sebastinas , happy to hear that Debian is also happy with the `CMAKE_INSTALL_LIBEXECDIR` fix. Let me know if something else needs to be tuned.

ps.: I have not test the new release against multi-arch build... yet. :)

**Comment by rizsotto** [comment]
Closing this ticket and collecting packaging problem case-by-case.
