### ISSUE TITLE
Empty compile_commands.json for 8-bit compiler (microchip xc8 v2.10)

### ISSUE THREAD

**Issue by ErdlingProductions** [rizsotto/Bear#286]
Hello,

I am trying to generate a compile_commands.json for my MPLAB X 8-bit project for a microcontroller. I can compile using "make". When I run "bear make", I do not get errors and bear does at least something, however the compile_commands.json is empty. The compiler used is xc8 v2.10.

To test if bear works, I made a simple test project for gcc, and that works fine, the compile_commands.json contains data, so bear works.

I created an (almost) empty mplab 8-bit project for demonstration. I executed "bear -vvvv make", the result can be viewed in the attached file:
[log.txt](https://github.com/rizsotto/Bear/files/4574032/log.txt)

Can you explain why the compile_commands.json is empty?

**Environment:**
 - OS name: Linux
 - OS version: Lubuntu 18.4
 - OS architecture: x86_64
 - Bear version: 2.4.3
 - Bear install method: as shown in the manual

Thank you and best regards.

**Comment by rizsotto** [comment]
Hi @ErdlingProductions ,

it looks like that your project is using `xc8-cc` as a compiler, which Bear does not recognize. Try to pass `--use-cc=xc8-cc` flag to Bear.

Hope it helps.

**Comment by ErdlingProductions** [comment]
@rizsotto It worked! Thank you so much! So happy now :)

**Comment by rizsotto** [comment]
Hi @ErdlingProductions -- the upcoming Bear 4.1.6 recognizes the Microchip XC8 compilers `xc8-cc` and `xc8` automatically. No `--use-cc` flag and no config hint are needed anymore; `bear -- make` on an MPLAB X 8-bit project should now produce a populated `compile_commands.json`.

If you can, it would help a lot to test the release candidate before it ships. Check out the `4.1.6-rc` branch and install from source following [INSTALL.md](https://github.com/rizsotto/Bear/blob/4.1.6-rc/INSTALL.md), then run your usual build under it and let me know whether `compile_commands.json` now looks right.

XC8 is not gcc or clang, so its more exotic flags are parsed approximately, but sources, includes, and defines should come through fine for clang-tidy / clangd. If you spot a flag that trips it up, please attach the invocation.

**Comment by ErdlingProductions** [comment]
@rizsotto

Hey László, I compiled the 4.1.6 version from source and tested it against my current project using `bear -- make` inside of the `.X` project folder (small sidenote: `prjMakefilesGenerator.sh` has to be used before using bear). My compiler version is XC8 2.20.

The `compile_commands.json` was not created empty, it is very large, I assume all files are listed. I checked one entry more closely:
- `file` entry is correct
- **`arguments` is not quite correct, I am not sure if that falls under your exotic flags: `-Wl,--data-init` is missing**; all other flags are correctly listed
- `directory` is correct
- `output` is correct, it matches the compiler flag

I am currently not using bear, I encountered to many pitfalls when trying to use the other tool for which I needed the compile commands, however I am inclined to look back into it, if the time allows.

Very cool for you to reach out after all those years!

Best regards :)

**Comment by rizsotto** [comment]
Thanks @ErdlingProductions for your quick feedback!

This is great news! The missing `-Wl,--data-init` is a flag that is passed to the linker, and that's why it is intentionally filtered out. Most of the tools which reads the compilation database are not using linker flags. Is your use case require those?

**Comment by ErdlingProductions** [comment]
@rizsotto 
Hey :) As I mentioned I currently am not in need of `compile_commands.json`, so I have no way to verify. I only checked what I could without directly using it. I can't promise, but I'll try to give an update once I use it again, however that could take some time. Hope it helped a little though :)
