### ISSUE TITLE
how to install bear in cygwin and msys2?

### ISSUE THREAD

**Issue by anlexN** [rizsotto/Bear#294]
i find no package there.

**Comment by rizsotto** [comment]
I'm not familiar with this cygwin. What package management is available on this platform? Maybe it's better to open a ticket in the packagers repository. This project is not providing package for any distribution.

Try to install it from source. (Which I did not tried on that platform.)

**Comment by anlexN** [comment]
can you release pre-build package in your repo?

**Comment by rizsotto** [comment]
if you help me to build it, we can release pre-build package.

(I don't know how to package for cygwin.)

**Comment by anlexN** [comment]
![image](https://user-images.githubusercontent.com/8686739/93288544-a2a25680-f80e-11ea-85a5-96b4b5da9cfa.png)
msys2 have no grpc_cpp_plugin, i can not build.

**Comment by rizsotto** [comment]
If you can't install gRPC from package, the build tries to build it from source.

**Comment by rizsotto** [comment]
In the screenshot, is the same `pacman` as in arch linux? In case of yes, look at `INSTALL.md` which has instruction for arch linux packages.

**Comment by anlexN** [comment]
you can look at [msys2](https://www.msys2.org/), there pacman is based on arch linux. but there are no package in msys2.
![image](https://user-images.githubusercontent.com/8686739/93304034-f886f680-f82e-11ea-8b34-2d844313955e.png)

**Comment by rizsotto** [comment]
Can't read the command output on that screenshot. :smile: you probably using non english local.

These are the packages I've found on that link...

https://packages.msys2.org/package/mingw-w64-x86_64-grpc?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-spdlog?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-fmt?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-nlohmann-json?repo=mingw64

**Comment by anlexN** [comment]
i install package for your link successfully, but still fail.
![image](https://user-images.githubusercontent.com/8686739/93314657-a8169580-f83c-11ea-84ce-4941aa863574.png)
teacher, my final problem is: i can not correctly open [nodejs source code](https://github.com/nodejs/node) with [jetbrains clion](https://www.jetbrains.com/clion) in windows10! can you help me? [someone teach me with WSL](https://youtrack.jetbrains.com/issue/CPP-22079?clearDraft=true&description=%0A%0ACL-202.6948.80,%20JRE%2011.0.8%2B10-b944.31x64%20JetBrains%20s.r.o.,%20OS%20Windows%2010(amd64)%20v10.0%20,%20screens%201536x864), but i don't like WSL

**Comment by rizsotto** [comment]
I think it fails because CMake wants to run `git clone` and you don't have `git` installed.

https://packages.msys2.org/package/git?repo=msys&variant=x86_64

And it looks like the installed libraries are not found (that's why it will build it from sources)

**Comment by anlexN** [comment]
oh my god, still fail. i git clone grpc_dependency and so on very slowly or say can not git clone those. because i am in some place. teacher, my final problem is: i can not correctly open [nodejs source code](https://github.com/nodejs/node) with [jetbrains clion](https://www.jetbrains.com/clion) in windows10! can you help me? [someone teach me with WSL](https://youtrack.jetbrains.com/issue/CPP-22079?clearDraft=true&description=%0A%0ACL-202.6948.80,%20JRE%2011.0.8%2B10-b944.31x64%20JetBrains%20s.r.o.,%20OS%20Windows%2010(amd64)%20v10.0%20,%20screens%201536x864), but i don't like WSL
