### ISSUE TITLE
bear nodejs cost me 1 hour, oh my god.

### ISSUE THREAD

**Issue by anlexN** [rizsotto/Bear#298]
Ubuntu 20.04.1 LTS, windows 10 WSL, bear 2.4.3
@rizsotto , can you do focused improvement for [ndoejs](https://github.com/nodejs/node), i need compile_command.json very much.
by the way, can you release windows 10 Bear? now your Bear is only for linux environment, oh my god.

**Comment by rizsotto** [comment]
Hello again @anlexN ,
Sorry to hear that you still have issue to generate the compilation database. Have you tried another tools? (Bear is not the only tool which can do that, and others might do better job on Windows.) Are you saying that build nodejs with and without Bear the time difference is 1 hour?
Anyway, I'm the only person who is working on this project right now. I don't have windows machine to port Bear onto it. And I'm focusing to release the new version I was working in the last 9 months. Have very limited bandwidth to do something else, but happy to help if you are trying to do it yourself.

**Comment by anlexN** [comment]
1. i have tried compiledb, but have issues [FileNotFoundError](https://github.com/nickdiego/compiledb/issues/105), can you anwser?
2. what another tool do you suggest?
3. can you use windows 10 virtual machine to develop?
4. build nodejs with Bear, costs me 1 hour. can you try by yourself?
5, i am learning C++, maybe in the future, i can help you.
6. if you write modern, standard C++, you can have very big portable, directly compile bear for windows 10. microsoft official document tell me.

**Comment by rizsotto** [comment]
```
make -j8  6516.34s user 320.90s system 776% cpu 14:41.03 total
bear make -j8  6757.70s user 339.10s system 770% cpu 15:20.55 total
```
Was building node without and with Bear. This does not show significant slowdown. That project is big, and that's why it took so long to compile.

If this is an issue for you, use tools which can create compilation database from make file without running the build. (There is one or two out there which can do it, but forgot their name. Google will find it for you.)

**Comment by anlexN** [comment]
1. what bear version do you use?
2. please tell me two tool you say
3. please help to answer compiledb [FileNotFoundErrorv](https://github.com/nickdiego/compiledb/issues/105)

**Comment by rizsotto** [comment]
1. it was the latest release `2.4.4`
2. there is a list (of tools) in this article https://sarcasm.github.io/notes/dev/compilation-database.html
3. looks like the `compiledb` is trying to execute `make`, but it can't find it. Maybe `make` is not in the `PATH`? The `compiledb` is running the system Python interpreter, but `make` is not visible from it? (I really have no experience with Windows, so I'm just guessing.)

Bonus question, did you managed to compile the `nodejs` project without Bear or compiledb? (Just `./configure && make -j4`)

**Comment by anlexN** [comment]
1. oh my god. `./configure && make -j4` costs me 1.5 hours,  `./configure && make` costs me 1 hour, i am very angry. how to decrease build time? 
2. have you try to compile nodejs?
3. why use RUST language in 3.x Bear?
