### ISSUE TITLE
File compile_commands.commands.json ?

### ISSUE THREAD

**Issue by simark** [rizsotto/Bear#302]
I just built the latest Bear (bdaac0cc5769d9376e61d33a70e52850aa335057) and tried it.  It is now creating a file called `compile_commands.commands.json`, in addition to the expected `compile_commands.json`.  What is this file?  Is it expected that Bear leaves it there?

It seems to contain details about all executed commands, but in a very verbose way (containing the full environment for all commands).

**Comment by rizsotto** [comment]
Hey @simark , yes the new Bear is running two commands one after the other. The first one (`intercept`) tries to intercept all executed commands, and the second one (`citnames`) creates the final compilation database from it. (The file itself can be useful to profile the build process or help to migrate from one build tool to another.)

But I can make Bear to delete the file after finishing those commands. I have not thought about this might be confusing. Thanks for the feedback!

**Comment by simark** [comment]
Bear is advertised as a tool that creates `compile_commands.json`, so I was surprised that it created another file.

Personally, I don't care for that other file, I see it as an internal artifact of Bear that it leaves hanging around.  I'd suggest not leaving it there by default, and maybe adding an option for keeping it (which could be useful for debugging the build or Bear itself I suppose).  A bit like the `-save-temps` option of gcc.
