### ISSUE TITLE
port Bear to windows

### ISSUE THREAD

**Issue by anlexN** [rizsotto/Bear#303]
everytime, i can not clone grpc dependency so that i can not build Bear.
if you can , i can directly install pre-built binary package in my system.

**Comment by rizsotto** [comment]
Hi @anlexN , I've thought we discuss it earlier why there is no windows port for the project: because nobody did that work.

I renamed this ticket and will keep it open for a while, so this could be a place to discuss work related to the issue.

**Comment by anlexN** [comment]
but can you give deb package to me?

**Comment by rizsotto** [comment]
This is a source repository, not a package repo. There is a link in the readme file for packages. Or search with the package manager.

**Comment by anlexN** [comment]
where is your say readme link?

**Comment by rizsotto** [comment]
https://repology.org/project/bear/versions

**Comment by rizsotto** [comment]
@anlexN I temporarily banned you to contribute to this repo. The reason is that you pushing your interest above others. It would be acceptable to seek help in a ticket. But I feel that you are pushing me to solve your exact problem. And you can't accept no for an answer if I can't help. Please consider that I am doing this project in my free time, and providing help as much as I can, but the tone of your messages are more like if you were already paying for this.

**Comment by huqifj** [comment]
Hello, Can the compile_commands.json file generated on Ubuntu be used on windows? I use nvim on both Ubuntu and windows 10. LSP works well on Ubuntu, but not on windows. They use the same project. I don't know which part is wrong

**Comment by rizsotto** [comment]
@huqifj don't know the answer... there is multiple thing which might break it. The path of the source files shall match. (In the `file`, `arguments` and `direcotry` fields.) Then both the linux and windows compiler shall take the same compiler flags. The include directory paths shall match. And the path to the compiler shall match too... It's not impossible that the file generated on Linux will work on Windows, but less likely.

**Comment by efikarl** [comment]
how's going? here's expectation in windows version...

**Comment by rizsotto** [comment]
Let me be clear on the expectations. I have zero experience to develop software on Windows. (And have little interest to learn it.) This project will only have windows version, if somebody does some work. :construction: I am happy to help to that person, but won't do it myself.
