### ISSUE TITLE
Bear errors

### ISSUE THREAD

**Issue by VictorTennekes** [rizsotto/Bear#304]
**Describe the bug**
When trying to create a `compile_commands.json` with bear using `make clean; bear -- make` it provides me with the following error:

```
bear: ERROR: wrapper: Internal error.
Traceback (most recent call last):
  File "/usr/local/bin/bear", line 289, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/bin/bear", line 316, in intercept_build
    exit_code, current = capture(args, tools)
  File "/usr/local/bin/bear", line 340, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/local/bin/bear", line 213, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--'
bear: ERROR: wrapper: Please report this bug and attach the output to the bug report
```

When running it as follows: `make clean; bear make` i get a file with `[]` in it.

**Environment:**
 - OS name: Darwin
 - OS version: Catalina 10.15.7
 - OS architecture: x86_64
 - Bear version: 2.4.4
 - Bear install method: `brew install bear`

**Additional context**
The project i try running it on: https://www.github.com/abeaugustijn/minishell

**Comment by rizsotto** [comment]
@VictorTennekes thanks for the report.

The `2.4.x` release would require `bear make` without the dashes. #215 is the reason for getting empty output. That ticket has a few workarounds. (The most favoured is to use GNU make to build the project.)

**Comment by VictorTennekes** [comment]
Thank you very much I'll check it out :)

**Comment by bjodah** [comment]
Thank you @rizsotto , is an update to the README in order? To me it reads like we need the `--` as a separator between bear's flags and flags passed to the build system?

**Comment by rizsotto** [comment]
@bjodah I think the README file is correct. The root of the misunderstanding is that I've changed the flags (and the separator) between 2.4.x and 3.0.x versions. The README file is telling how to use the current version. But if you come to GitHub to read the README, it will show the latest... In this case it was that Victor was using the separator which is needed for the latest version, while using the older version.

To avoid this issue, always consult the local copy of the README file. The build system installs it. And most of the packages are installing it too.

Do you have an idea how to communicate this change better?

**Comment by bjodah** [comment]
My bad. I simply got confused :). (And it makes sense you're introducing `--` to separate the flags).

**Comment by ZuseZ4** [comment]
@rizsotto  (sorry for the ping, not sure if github will send you a note on closed issues otherwise).
Apparently a few package manager still ship the old 2.4 release - I just ran into this issue under Ubuntu.
I understand that maintaining all the different package manager isn't easy, but as long as major distributions still ship the old version it might be worth to add a small note? 
A single sentence mentioning to not use `--` if you are on the old version would have saved me (and apparently others too) some time. Would you accept a change similar to

> Please be aware that some package manager still ship our old 2.4.x release. In that case please use bear `<build-command> `instead of `bear -- <build-command>`.
