### ISSUE TITLE
Build failure on x86

### ISSUE THREAD

**Issue by nmeum** [rizsotto/Bear#308]
**Describe the bug**

On [Alpine Linux](https://alpinelinux.org/) Edge, which uses [musl libc](https://musl.libc.org), Bear fails to build on x86 with the following error:

```
/builds/nmeum/aports/testing/bear/src/Bear-3.0.0/source/citnames/source/Configuration.cc: In member function 'virtual rust::Result<unsigned int> cs::ConfigurationSerializer::to_json(std::ostream&, const cs::Configuration&) const':
/builds/nmeum/aports/testing/bear/src/Bear-3.0.0/source/citnames/source/Configuration.cc:210:28: error: could not convert 'rust::Ok<long unsigned int>(1)' from 'rust::types::Ok<long unsigned int>' to 'rust::Result<unsigned int>'
  210 |             return rust::Ok(1ul);
      |                    ~~~~~~~~^~~~~
      |                            |
      |                            rust::types::Ok<long unsigned int>

```

This is probably caused by the fact that `size_t` is not necessarily defined as `long unsigned int`. Adding an explicit cast to `size_t` fixes the problem for me:

```patch
diff -upr Bear-3.0.0.orig/source/citnames/source/Configuration.cc Bear-3.0.0/source/citnames/source/Configuration.cc
--- Bear-3.0.0.orig/source/citnames/source/Configuration.cc	2020-10-08 14:18:32.551685952 +0200
+++ Bear-3.0.0/source/citnames/source/Configuration.cc	2020-10-08 14:18:51.952022987 +0200
@@ -207,7 +207,7 @@ namespace cs {
             nlohmann::json out = rhs;
             os << std::setw(4) << out << std::endl;
 
-            return rust::Ok(1ul);
+            return rust::Ok((size_t)1ul);
         } catch (const std::exception &error) {
             return rust::Err(std::runtime_error(error.what()));
         }

```

**To Reproduce**

Setting up an Alpine x86 VM and attempting to build Bear from source should suffice.

**Environment:**
 - OS name: Linux-lts
 - OS version: Alpine Linux edge
 - OS architecture: x86
 - Bear version: 3.0.0
 - Bear install method: source

**Additional context**

Log file from our CI builder:  [alpine-linux-edge-x86-bear.txt](https://github.com/rizsotto/Bear/files/5347777/alpine-linux-edge-x86-bear.txt)

**Comment by rizsotto** [comment]
should be fixed by #312
