### ISSUE TITLE
Error in macOS compiler(10.15)

### ISSUE THREAD

**Issue by Yihen** [rizsotto/Bear#313]
**Describe the bug**
 dynamic was miss, when run "make all"

**To Reproduce**
1. cmake -DENABLE_UNIT_TESTS=OFF -DENABLE_FUNC_TESTS=OFF $BEAR_SOURCE_DIR
2. make all

**Expected behavior**
NO ERROR 

**Environment:**
 - OS name: macOS
 - OS version: 10.15 
 - Bear version: 3.0.0
 - Bear install method: from open source

**Additional context**
$ make all
[  0%] Built target grpc_dependency
[  0%] Built target googletest_dependency
[  0%] Built target nlohmann_json_dependency
[  0%] Built target fmt_dependency
[  0%] Built target spdlog_dependency
[ 11%] Performing build step for 'BearSource'
[ 15%] Built target sys_a
[ 18%] Built target flags_a
[ 23%] Built target bear
[ 26%] Built target report_a
[ 28%] Built target shell_a
[ 34%] Built target citnames_json_a
[ 57%] Built target citnames_a
[ 63%] Built target citnames
[ 73%] Built target rpc_a
[ 86%] Built target intercept_a
[ 89%] Linking CXX executable intercept
ld: library not found for -labsl_dynamic_annotations
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [intercept/CMakeFiles/intercept.dir/build.make:211: intercept/intercept] Error 1
make[4]: *** [CMakeFiles/Makefile2:567: intercept/CMakeFiles/intercept.dir/all] Error 2
make[3]: *** [Makefile:149: all] Error 2
make[2]: *** [CMakeFiles/BearSource.dir/build.make:133: subprojects/Stamp/BearSource/BearSource-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:201: CMakeFiles/BearSource.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by rizsotto** [comment]
This is a Homebrew problem, which I reported already to them.

https://github.com/Homebrew/homebrew-core/issues/62589
