### ISSUE TITLE
Excessive "Received start event could not be merged into execution report. Ignored." messages

### ISSUE THREAD

**Issue by smhc** [rizsotto/Bear#316]
**Describe the bug**
Performing a build outputs excessive "Received start event could not be merged into execution report. Ignored." messages, presumably coming from: https://github.com/rizsotto/Bear/blob/f8d5c959ca0eb4afe512d710f89b35c7320fcc86/source/intercept/source/Reporter.cc#L178

**To Reproduce**
I perform a build using something similar to;

bear --libexec /xxx/xxx/libexec.so --interceptor /xxx/xxx/intercept --executor /xx/xx/er --citnames /xxx/xxx/citnames --output compile_commands.json -- perl build.pl

the build.pl script then creates several child processes which invoke make for various modules. For version 2.4 this worked fine. In version 3.0 I am getting excessive 'Received start event could not be merged into execution report. Ignored.' messages, but the compilation db is still getting created.

**Expected behavior**

Similar behaviour as version 2.4, without the excessive logging.

**Environment:**
 - OS name: Linux
 - OS version: Oracle Linux 7.5
 - OS architecture: x86_64
 - Bear version: 3.0.0
 - Bear install method: own build

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? No
 - What build tools this project is using? perl invoking make
 - What architecture you are trying to compile for? Linux
 - Could you attach build logs? - will try later

**Before you send...**
 - Have you read the `README.md` file or `man bear`? Y
 - Have you looked what other open issues Bear has? Y
 - Are you sure that the build works without Bear? Y

**Comment by rizsotto** [comment]
Could you check if this occurs if you set the file descriptor limit is higher? (`ulimit -a` will give you help how to change that.)

If that persists, could you send me the logs to have a bit more context?

**Comment by smhc** [comment]
I've tried setting 'ulimit -n 4096' but it didn't seem to help.
I will try and reproduce it. I assume it just needs bear wrapping a command which spawns a few child processes that in turn run make/gcc. I am only running with 4 parallel streams.

**Comment by rizsotto** [comment]
I see. Was not carefully read the error message you've described here... What happens here, that `intercept` listens for execution events (like process start or termination). It tries to merge the events by their PID. And received a new process start event, but it already has one with the same PID... Which is odd, because each execution has it's own supervisor process, which guarantees the PIDs are unique.

It would be interesting to read the `stderr` output if you pass the `--verbose` flag. I'm interested to see how this could happen. (My design was built on the presumption that this can't happen. :))

**Comment by smhc** [comment]
How long do the process ids need to be unique for? They are obviously
recycled over time and this build would generate thousands of child
processes during the half hour build that is all wrapped by a single bear
parent process.

If the problem is recycled process ids and using a parent process of
something other  than make you could build something large like llvm with:

"bear -- sh -c 'make -j10'"

And it would possibly recycle a pid during the build.

**Comment by smhc** [comment]
Also - when you talk about 'supervisor process' are you referring to the direct parent process of 'gcc' ?

When directly invoking make which in turn invokes gcc there clearly won't be many unique 'make' pids. However I am invoking a perl script which in turn creates child processes which in turn invoke make.. which in turn invoke gcc. There is a hierarchy of pids that are likely being recycled during the build.

I don't invoke bear around each individual 'make' call as it makes more sense to invoke it once around a wrapper script which in turn invokes make for many sub-modules.

**Comment by rizsotto** [comment]
The supervisor process I was refer to is `er` (execution reporter). When you start a build with Bear, it sets up the environment that `LD_PRELOAD` is points to `libexec.so`. That shared object contains the `exec*` functions which will be executed when `perl` or `make` executes a process. Those functions are not executing the process they were asked for, but executes `er` and pass the details of their arguments. So, now `er` can report the supervised process life cycle events. It uses its own PID to identify itself.

To recycle PID you really need to execute a lot of processes. But it can be controlled by the value of `/proc/sys/kernel/pid_max`.

To avoid this, I can choose another identifier. (UUID or PID+TIME) which would the id unique.

**Comment by smhc** [comment]
Ok thanks - I can see from the logs the pids are definitely wrapping during the build (pid max is 32k).

```
[20:15:09.688408, ic, 24476] Received event is merged into execution report. [pid: 14208, event: stop]
[20:15:09.707235, ic, 24476] Received event is merged into execution report. [pid: 14213, even: start] 
[20:15:09.727356, ic, 24476] Received event is merged into execution report. [pid: 14218, even: start] 
[20:15:09.746605, ic, 24476] Received event is merged into execution report. [pid: 14223, even: start]
[20:15:09.749949, ic, 24476] Received event is merged into execution report. [pid: 14223, event: stop]
[20:15:09.768160, ic, 24476] Received event is merged into execution report. [pid: 14228, even: start]
[20:15:09.789104, ic, 24476] Received event is merged into execution report. [pid: 14235, even: start]
...
(pids wrap around)
....
[20:17:24.723180, ic, 24476] Received event is merged into execution report. [pid: 14212, even: start]
[20:17:24.743425, ic, 24476] Received start event could not be merged into execution report. Ignored.
[20:17:24.744368, ic, 24476] Received event is merged into execution report. [pid: 14218, event: stop]
[20:17:24.747669, ic, 24476] Received event is merged into execution report. [pid: 14212, event: stop]
[20:17:24.765717, ic, 24476] Received start event could not be merged into execution report. Ignored. 
[20:17:24.786281, ic, 24476] Received start event could not be merged into execution report. Ignored.
[20:17:24.803498, ic, 24476] Received event is merged into execution report. [pid: 14233, even: start]
[20:17:24.874236, ic, 24476] Received event is merged into execution report. [pid: 14233, event: stop]
```

(note there is a small typo here as well, 'even:')

**Comment by rizsotto** [comment]
Thanks @smhc , this is a strong proof that PID recycling happens.

**Comment by rizsotto** [comment]
Replaced the PID to be not the identifier for the reporting process. (Now it's a 64 bit random id.) I'm expecting little identifier collisions and it's protected against PID recycling.

The only thing I could not do, is testing it more extensively. (It's not easy to test this in CI or in unit tests.)

@smhc could you confirm this is fixed for you?

**Comment by smhc** [comment]
Thanks, that seems to resolve the issue.
Rather than 64bit random id it could be the PID shifted with a high resolution timestamp or a 32bit random integer in low bits. There's little chance of a collision using a 64bit random number but incorporating the PID value might be cleaner.
