### ISSUE TITLE
Shell scripts not executed correctly without a hashbang in 3.0

### ISSUE THREAD

**Issue by smhc** [rizsotto/Bear#319]
**Describe the bug**
Script files without a '#!' are not executed by bear when spawned. Version 2.4.0 of bear did not have this issue.

**To Reproduce**

Create file 'run.sh' (note lack of #!)
```
echo check
```
Then attempt to execute (note no output):
```
>bear -- ./run.sh
```

It is also an issue when wrapped in a Makefile:
```
test:
   ./run.sh
```

Then attempt to execute:
```
> bear -- make test
./run.sh
make: *** [test] Error 127
```

It works fine when adding "#!/bin/ksh" to the file.

**Expected behavior**
Consistent with old version of bear and consistent with not wrapping the command with bear.

**Environment:**
 - OS name: Linux
 - OS version: Oracle Linux 7.5
 - OS architecture: [e.g. x86_64] run `uname -m`
 - Bear version: 3.0.0
 - Bear install method: Build

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? N
 - What build tools this project is using? GNU Make 3.80
 - What architecture you are trying to compile for? Linux

**Before you send...**
 - Have you read the `README.md` file or `man bear`? Y
 - Have you looked what other open issues Bear has? Y
 - Are you sure that the build works without Bear? Y

**Comment by rizsotto** [comment]
This is interesting. I'm not sure if this is a bug or a feature. :)

In 3.0 I did change how `exec` methods are overwritten and probably did not pay attention to this aspect. Will need to find out what makes a script executable by `execve`. (The obvious answer is to expect shebang at the beginning of the file. And I am not aware how else could it be done, but will learn.)

**Comment by smhc** [comment]
I agree the script isn't technically correct. However it worked with the old version of bear, but more significantly, it works without bear. I can fix the script easy enough - but it may be an indication of a more significant underlying issue. Adding bear as a wrapper ideally shouldn't break a build - and it may have this similar impact for others.

**Comment by rizsotto** [comment]
Making notes to myself:

```sh
echo $BASH_VERSION
echo $ZSH_VERSION
```

- Testing with this example.
It always prints the `bash` version (where the `/bin/sh` is a link to `bash`).
  - Independently from the current shell. (`zsh`, `bash`, `python`, `perl` is tested).
  - Independent what is the default shell of the user.
  - Independent from distributions? (Fedora and Arch is tested).
- It is claimed to be [different](https://www.unix.com/shell-programming-and-scripting/198781-scripts-without-shebang.html) on FreeBSD.
   - validate it!!!
- How does it work on MacOS?
- How does it work on Windows?

**Comment by rizsotto** [comment]
The fix for linux is on master branch.
