### ISSUE TITLE
Duplicate entries with wrapped toolchain

### ISSUE THREAD

**Issue by sl8vz** [rizsotto/Bear#321]
**Describe the bug**
Using a wrapped cross-compile toolchain (CC points to a wrapper which calls the gcc binary with additional options)  I get duplicate entries for each of my source files. I get one entry for the  *-gcc call in my application and additional one for the actual "real" compiler call with additional compiler options.

Tried using:
--use only --use-cc \<absolute path to real gcc\>

But I still get duplicate entries

Wrapped gcc: buildroot/output/host/bin/aarch64-none-linux-gnu-gcc
Real gcc: buildroot/output/host/opt/ext-toolchain/bin/aarch64-none-linux-gnu-gcc

**To Reproduce**
Steps to reproduce the behavior: Use a wrapped toolchain (e.g generated from buildroot)

**Expected behavior**
A possibility to only catch a single compilation unit.

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 20.04
 - OS architecture: x86_64
 - Bear version: 2.4.3
 - Bear install method: apt

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? close source... sorry
 - What build tools this project is using? make
 - What architecture you are trying to compile for? arm64
 - Could you attach build logs? Tell me if needed

**Comment by rizsotto** [comment]
Thanks @sl8vz 

So, when you call Bear with the `--use-cc` flag, which gcc do you specify? The wrapped or the real? (I presume you do give the wrapped gcc. Would it work if you give the real gcc to the flag?)

As a workaround I would suggest, to create a link to the "wrapped gcc" and give a unique name to it, which does not match the "real gcc" name. And use that wrapper in your build and with the `--use-cc` flag.

**Comment by sl8vz** [comment]
Hi @rizsotto ,
Thanks for your quick answer.
When I call bear with --use-cc, I specify the real one (as it's the "real" call to gcc with all options)

I understand that the issue is because both the wrapped and the real toolchain have the same name. I will try the workaround you suggest but it will require additional setup every time I generate a new toolchain.

Do you think there would be a possibility to tell bear to consider the full path of the toolchain provided in --use-cc ? Maybe an additional option ?

I come back to you after trying the workaround.

Thanks.

**Comment by sl8vz** [comment]
Unfortunately the wrapper use the name of the link that points to it to get the name of the real toolchain so it will not work even as a workaround.

**Comment by rizsotto** [comment]
Thanks for the update @sl8vz 

Sorry to hear that the workaround does not work. Then I'm out for quick fixes.

Unfortunately Bear was using not the full path (but only the "basename" of the process) to identify compilers. That needs to be fixed for your case... The bad news is that I rolled out a rewrite 3.0 which is on master branch now. I have not thought about how to continue with the 2.4 branch. (I might create a branch for you on the weekend.)

**Comment by sl8vz** [comment]
I have no problems building it from sources if that can save you some time.

**Comment by rizsotto** [comment]
I believe this is now fixed on the 3.x branch. With a config file like this:

```json
{
  "compilation": {
    "compilers_to_exclude": [
      "buildroot/output/host/bin/aarch64-none-linux-gnu-gcc"
    ]
  },
  "output": {
    "content": {
      "include_only_existing_source": false
    },
    "format": {
      "command_as_array": true,
      "drop_output_field": false
    }
  }
}
```
