### ISSUE TITLE
er: failed with: gRPC call failed: failed to connect to all addresses

### ISSUE THREAD

**Issue by tchiang-ml** [rizsotto/Bear#330]
**Describe the bug**
I was trying to build AOSP Android 10 codebase with Bear 3.02, and then it failed with the following error:
er: failed with: gRPC call failed: failed to connect to all addresses [pid: 25885]
17:10:56 ninja failed with: exit status 1

**To Reproduce**
git config --global user.name "name"
git config --global user.email "xxx@yyy.com"

repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47
repo sync -j8
source build/envsetup.sh
bear -- build/soong/soong_ui.bash --make-mode -j32

**Expected behavior**
Build should succeed.

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 16.04 
 - OS architecture: x86_64
 - Bear version: 3.0.2
 - Bear install method: from source

**Additional context**
 Please find the attached log file
[error.log](https://github.com/rizsotto/Bear/files/5578760/error.log)

**Before you send...**
 - Have you read the `README.md` file or `man bear`? YES
 - Have you looked what other open issues Bear has? YES
 - Are you sure that the build works without Bear? YES

**Comment by tchiang-ml** [comment]
I have used Bear 2.x before and it worked fine.

**Comment by tchiang-ml** [comment]
By the way, I have noticed memory usage is pretty high. My desktop has 64 GB RAM and 64 GB swap. Both have been used up to 80% by running Bear. I saw many processes like clang-9 and er.

**Comment by rizsotto** [comment]
Hi @tchiang-ml , thanks for the report.

First, congratulation to build this project on Ubuntu 16.04! :) The memory consumption problem is caused by the fact that now Bear stores everything in memory. Previously these events were many small files on the disk. I have a plan to use sqlight to replace the big memory allocations, but have all these information at one place.

But on the major topic. I don't know much about the android project and the tools used in it. Is it possible that the `/home/tchiang/and10/prebuilts/build-tools/linux-x86/bin/toybox` file is a statically linked executable? Is the build is using Bazel?

**Comment by tchiang-ml** [comment]
Android is built by a build system called 'Soong', https://android.googlesource.com/platform/build/soong/+/refs/heads/master/README.md

But I couldn't figure out if the toybox is statically lined or not. 

I will try your new release 3.0.3 and see if it fixes the issue. Thanks.

**Comment by rizsotto** [comment]
I doubt that 3.0.3 will fix this.

https://android.googlesource.com/platform/build/soong/+/refs/heads/master/docs/compdb.md could be an easy way to generate the JSON compilation database. (This is a link from the document you've sent.)

**Comment by tchiang-ml** [comment]
You are right. I still see the same issue with 3.0.3.

Thanks for the link. Yes, I am aware of the method. It works for Android 12 (the latest) codebase, but doesn't work for Android 10 which is the one I am working on.

**Comment by tchiang-ml** [comment]
I understand it's very time consuming to setup an Android build. However, if you are willing and have the bandwidth to spend the time to test it. Here is what I have done to setup on  Ubuntu 16.04 for building it:
sudo apt-get install -y bison g++-multilib git gperf libxml2-utils lib32z1 lib32ncurses5 zip bc curl build-essential ccache python-pil libssl-dev libgmp-dev pigz pbzip2 fuseext2 pigz python-setuptools libicu-dev
sudo apt-get install -y flex python-mako gettext libelf-dev genisoimage syslinux

sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install -y openjdk-8-jdk

Also, you want to have git and git-lfs (you probably know them more than I do). A big ccache also helps if you are going to repeatedly doing the build. I may miss some other things but I guess above should cover most of the setup. The first time building will take quite a few hours depending on the machine. Appreciate your help and devoted time for making Bear available for software engineers like me!

**Comment by tchiang-ml** [comment]
Hi, I tried to use Bear 3.x to build modules of Android 10 and it works fine. I am good enough for the result. Don't want to spend your time on this issue. I will close this ticket. However, if you like, I can help debug this issue if you let me know what information you need in order to debug it.

**Comment by rizsotto** [comment]
Thanks @tchiang-ml , I think the instruction you gave me will be enough to try to reproduce the error. (Sorry, but I am short on free time at the moment.)
