### ISSUE TITLE
[Question] How to generate static binary

### ISSUE THREAD

**Issue by srikanth007m** [rizsotto/Bear#333]
Hello @rizsotto ,

I am not familiar with `cmake`. Looking for information on how to generate a static lib + static bear from `cmake`. The current source is generating shared lib.

**Comment by rizsotto** [comment]
Hi @srikanth007m ,

Adding this line for each target would make it: `target_link_libraries(xxxx "-static")` <- where the `xxxx` is the name of the target.

But this simple change require that all dependent libraries (including the `libc`) is available as static library... (I've made a change in the abseil build to make that possible. Not sure if the gRPC is using that library.)

Can you tell what are the limitations you facing with dynamic binaries and libraries?

**Comment by srikanth007m** [comment]
@rizsotto Thank you for looking into the ask. 

Most of my work is based on cross compilation of kernels with modified tool chains. I see `ERROR: ld.so: object '/lib/x86_64-linux-gnu/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.` this issue more frequently while compiling the kernel in KDEV env. (Host is x86 and trying to cross compile the android kernel). So to rule out all such issues, i thought of using the static binary. Any thoughts?

**Comment by srikanth007m** [comment]
@rizsotto I got around 109 entries with `target_link_libraries` under bear source tree. Should I need to make an entry to all those make files to generate a static binary? Or any common parent flag available on top root that makes it.

**Comment by rizsotto** [comment]
Hi @srikanth007m ,

I think you don't need static binaries, but multilib support (where 32bit and 64bit binaries can run on the same OS). The error you've copied (`ld.so: object ... from LD_PRELOAD cannot be preloaded`) is when a 32 bit binary is trying to pre-load a 64 bit library.

#324 is a ticket for that. (I would close this ticket.)

As a quick workaround, the old version of this tool was supporting it. See the README file [relevant section](https://github.com/rizsotto/Bear/tree/2.4.4) how to use it.

**Comment by srikanth007m** [comment]
@rizsotto sure. i will try using the suggested method. For now i will close the ticket.

**Comment by srikanth007m** [comment]
@rizsotto I tried building with the instructions at 2.4.4 branch. But still the libraries are compiling with 64bit. Please suggest if i am making any mistake in below steps. My gcc supports `-m32`.

Steps fallowed
`git clone  https://github.com/rizsotto/Bear.git Bear_32
git checkout -b 2.4.4
cmake "$BEAR_SOURCE_DIR" -DCMAKE_C_COMPILER_ARG1="-m32"; VERBOSE=1 make all
file ./subprojects/Build/BearSource/intercept/libexec.so
./subprojects/Build/BearSource/intercept/libexec.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=47547536cd4cddcb51ad87874f16fa15a545e077, not stripped`

**Comment by rizsotto** [comment]
Are you trying the 2.4.4 instructions on the 3.0 sources? I don't think it will work just like that. :) That's why I've created a ticket to find out what needs to be done for supporting 32 bit compilers.

What I meant as a workaround is to use the 2.4.4 version of the tool, which supports multilib and it's documented.

If you want to work on the #324 ticket, I can help with that too.

**Comment by srikanth007m** [comment]
No, I am not trying the 2.4.4 instructions on 3.0 branch. In my above steps, i am switching to 2.4.4 branch after cloning.

**Comment by rizsotto** [comment]
The reason I've thought you are doing the 3.0, because 2.4.4 does not have `libexec.so` (neither `subprojects` directory).

So, maybe clean up source directory with `git clean -fdx`, remove the content of the build directory, and uninstall previously installed Bear artefacts.

2.4.4 shall have a `bear` python script and a `libear.so` shared object file. (Which you want to compiled to 64 and 32 bit.)

**Comment by srikanth007m** [comment]
Kernel Version: Linux 4.15.0-123-generic #126~16.04.1-Ubuntu SMP Wed Oct 21 13:48:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

@rizsotto Yes, i tried now with clean workspace. Now i am able to see the shared object file is a 32bit. 

`file ./libear/libear.so
./libear/libear.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=a283f4875d16cb5758e33c7506c0ba1eac01c642, not stripped
`
When i install using `make install`. It tried to install into below location. Which is using same even for 64bit. 
`sudo make install
[100%] Built target ear
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/doc/bear/COPYING
-- Up-to-date: /usr/local/share/doc/bear/README.md
-- Up-to-date: /usr/local/share/doc/bear/ChangeLog.md
-- Installing: /usr/local/lib/bear/libear.so
-- Installing: /usr/local/bin/bear
-- Up-to-date: /usr/local/share/man/man1/bear.1
-- Up-to-date: /usr/local/share/bash-completion/completions/bear
`
64bit compilation
`libear/libear.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=83330398ea244221fc7981e8c8d57dc02ea0c4fa, not stripped'

`sudo make install`
`sudo make install
[100%] Built target ear
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/doc/bear/COPYING
-- Up-to-date: /usr/local/share/doc/bear/README.md
-- Up-to-date: /usr/local/share/doc/bear/ChangeLog.md
-- Installing: /usr/local/lib/bear/libear.so
-- Installing: /usr/local/bin/bear
-- Up-to-date: /usr/local/share/man/man1/bear.1
-- Up-to-date: /usr/local/share/bash-completion/completions/bear'

Now when i tried to use bear command. I still see the same issue.
`ERROR: ld.so: object '/usr/local/lib/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

**Comment by rizsotto** [comment]
I would not use the `make install` command to install Bear in your case. As the README file suggest you build the project, but you install those manually. So, just follow the instructions, otherwise you end up overwriting the 32 library with the 64 bit version as you just did.

The end result should be something like this:

```shell
$ find /usr/local
/usr/local/bin/bear
/usr/local/lib/i386-linux-gnu/libear.so
/usr/local/lib/x86_64-linux-gnu/libear.so
```

Make sure that [`bear` line 617](https://github.com/rizsotto/Bear/blob/2.4.4/bear/bear.py#L617) has `/usr/local/$LIB/libear.so` as the README file says.

**Comment by srikanth007m** [comment]
@rizsotto Thank you. This worked out.
