### ISSUE TITLE
`make install` does not respect `DESTDIR`

### ISSUE THREAD

**Issue by nmeum** [rizsotto/Bear#337]
**Describe the bug**

Bear install the staging directory to `DESTDIR` on `make install`.

From the log:

```
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/bin/intercept
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/share/man/man1/intercept.1
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/libexec/bear/wrapper
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/libexec/bear/wrapper.d
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/libexec/bear/er
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/libexec/bear/libexec.so
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/bin/citnames
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/share/man/man1/citnames.1
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/bin/bear
-- Installing: /tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/share/man/man1/bear.1
make[3]: Leaving directory '/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/subprojects/Build/BearSource'
```

**To Reproduce**

Build bear as:

```
$ cmake -B build \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DBUILD_SHARED_LIBS=True \
  -DCMAKE_INSTALL_LIBEXECDIR=libexec/bear \
  -DCMAKE_BUILD_TYPE=None .
$ make -C build
$ make -C build DESTDIR=/tmp/bear/pkg install 
```

And then:

```
$ ls /tmp/bear/pkg/
home/
usr/
```

IMHO `/tmp/bear/pkg/home` should not be present. This directory includes the staging stuff (see above).

**Expected behavior**

Bear should not install the staging directory.

**Environment:**
 - OS name: Linux
 - OS version: Alpine Linux Edge
 - OS architecture: x86_64
 - Bear version: 3.0.3

**Comment by rizsotto** [comment]
Well, I don't know what to say... yes, it's using staging directory for the build. :)

Please either come up with a proposed solution (how else shall it be done, maybe send a PR) or explain what problem the current solution causes for you... So far, this is just an opinion of yours.

**Comment by nmeum** [comment]
Well, is there any reason why these files need to be installed to `DESTDIR`? I don't wont to ship `/home` in my bear Alpine package. As far as I am concerned, these files are only needed for the build and I don't see any reason why they need to be installed system-wide.

**Comment by rizsotto** [comment]
Bear is using external projects to build the 3rd party dependencies and itself (`BearSource` is an external project which contains the source for this project.) So, whey you run `make install` it calls all external projects' install targets, and runs the main project (`Bear`) install after that.

The stage directory is used as a destination directory of the `BearSource` project. The `Bear` project then it install all files from stage directory to the final destination. (So, these files are the ones you want to put into the package.)

The `DESTDIR` is usually used to relocate the location of the files for packaging. Unfortunately when `Bear` install the staging directory, it does not install the content of it, but with the full path. (Instead of copy the file `/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/bin/intercept` to `/tmp/bear/pkg/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage/bin/intercept`, it should copy to `/tmp/bear/pkg/bin/intercept`) I don't know how to tell CMake to install the content of `/home/soeren/src/aports/community/bear/src/Bear-3.0.3/build/stage` and not the directory itself.

I see two options here: One, find a way to install the content of the stage directory. Two, don't use external projects to build the project. (The first one might be quicker, the second one might be better, but harder to make.)

**Comment by rizsotto** [comment]
Hi @nmeum , I'm trying to reproduce this with the following commands.

```shell
$ cmake -B $build_dir -S $source_dir -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib 
$ cmake --build $build_dir --parallel 10
$ DESTDIR=/tmp cmake --build $build_dir --target install
```

But the install output looks as expected...

<details>

```
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /tmp/usr/.
-- Installing: /tmp/usr/./bin
-- Installing: /tmp/usr/./bin/citnames
-- Installing: /tmp/usr/./bin/bear
-- Installing: /tmp/usr/./bin/intercept
-- Installing: /tmp/usr/./share
-- Installing: /tmp/usr/./share/man
-- Installing: /tmp/usr/./share/man/man1
-- Installing: /tmp/usr/./share/man/man1/intercept.1
-- Installing: /tmp/usr/./share/man/man1/bear.1
-- Installing: /tmp/usr/./share/man/man1/citnames.1
-- Installing: /tmp/usr/./libexec
-- Installing: /tmp/usr/./libexec/wrapper
-- Installing: /tmp/usr/./libexec/wrapper.d
-- Installing: /tmp/usr/./libexec/wrapper.d/readelf
-- Installing: /tmp/usr/./libexec/wrapper.d/ld
-- Installing: /tmp/usr/./libexec/wrapper.d/cpp
-- Installing: /tmp/usr/./libexec/wrapper.d/objdump
-- Installing: /tmp/usr/./libexec/wrapper.d/g++
-- Installing: /tmp/usr/./libexec/wrapper.d/ranlib
-- Installing: /tmp/usr/./libexec/wrapper.d/weave
-- Installing: /tmp/usr/./libexec/wrapper.d/ctangle
-- Installing: /tmp/usr/./libexec/wrapper.d/tex2dvi
-- Installing: /tmp/usr/./libexec/wrapper.d/cc
-- Installing: /tmp/usr/./libexec/wrapper.d/nm
-- Installing: /tmp/usr/./libexec/wrapper.d/cweave
-- Installing: /tmp/usr/./libexec/wrapper.d/makeinfo
-- Installing: /tmp/usr/./libexec/wrapper.d/bison
-- Installing: /tmp/usr/./libexec/wrapper.d/m2c
-- Installing: /tmp/usr/./libexec/wrapper.d/f77
-- Installing: /tmp/usr/./libexec/wrapper.d/yacc
-- Installing: /tmp/usr/./libexec/wrapper.d/c++
-- Installing: /tmp/usr/./libexec/wrapper.d/as
-- Installing: /tmp/usr/./libexec/wrapper.d/strip
-- Installing: /tmp/usr/./libexec/wrapper.d/lint
-- Installing: /tmp/usr/./libexec/wrapper.d/pc
-- Installing: /tmp/usr/./libexec/wrapper.d/flex
-- Installing: /tmp/usr/./libexec/wrapper.d/tangle
-- Installing: /tmp/usr/./libexec/wrapper.d/lex
-- Installing: /tmp/usr/./libexec/wrapper.d/ar
-- Installing: /tmp/usr/./libexec/wrapper.d/tex
-- Installing: /tmp/usr/./libexec/wrapper.d/gcc
-- Installing: /tmp/usr/./libexec/wrapper.d/objcopy
-- Installing: /tmp/usr/./libexec/libexec.so
-- Installing: /tmp/usr/./libexec/er
-- Installing: /tmp/usr/share/doc/Bear/COPYING
-- Installing: /tmp/usr/share/doc/Bear/README.md
-- Installing: /tmp/usr/share/doc/Bear/INSTALL.md
-- Installing: /tmp/usr/share/doc/Bear/CONTRIBUTING.md
-- Installing: /tmp/usr/share/doc/Bear/CODE_OF_CONDUCT.md
```
</details>

**Comment by nmeum** [comment]
> But the install output looks as expected...

Does the target directory not contain your stage directory (check with `ls`)? Can you paste the entire build log?

For me, even using your commands, the staging directory is still installed to `DESTDIR`. And looking at other distribution packages, I also don't seem to be the only person with this issue: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bear#n35

**Comment by rizsotto** [comment]
I see, yes the `DESTDIR` has `home/...` directory.

**Comment by nmeum** [comment]
Yep, my best guess is that the files are installed once by `ExternalProject_Add` as invoked here:

https://github.com/rizsotto/Bear/blob/e05082cd95db54b8cdbb7974e5e4d1b9fcb8976c/CMakeLists.txt#L39-L67

And then a second time by the following `install(…)` invocation:

https://github.com/rizsotto/Bear/blob/e05082cd95db54b8cdbb7974e5e4d1b9fcb8976c/CMakeLists.txt#L89-L94

**Comment by rizsotto** [comment]
The `devel` branch now has a solution for it.

As [this ticket suggest](https://gitlab.kitware.com/cmake/cmake/-/issues/18165), the build and the install steps needs to be separated, and only the install step takes the `DESTIDR` environment.

Could you check if this works for you too? I'll make a new release if you confirm.

**Comment by nmeum** [comment]
> Could you check if this works for you too? I'll make a new release if you confirm.

Sorry, was busy with other things. Yes, I can confirm that your patch works. Thanks for looking into this! :tada:
