### ISSUE TITLE
bear make cannot be executed

### ISSUE THREAD

**Issue by strangerby** [rizsotto/Bear#340]
**Describe the bug**
When I execute bear make, unrecognized parameter appears: "make"
Usage: bear [--output <arg>] [--verbose] -- ..
**To Reproduce**

**Expected behavior**

**Environment:**
 - OS name: linux
 - OS version: manjaro 20.2
 - OS architecture:  x86_64 
 - Bear version: 3.0.3
 - Bear install method: [e.g. from package]

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? [e.g. No if it's a close source project, but in case of an open source project a link to the sources could be nice.]
 - What build tools this project is using? [e.g. GNU make]
 - What architecture you are trying to compile for? [e.g. cross compiling]
 - Could you attach build logs? If you can re-run the command which failed (e.g. `bear make`) with extra verbose log switches (e.g. `bear -vvvv make`) and send the output of it, that would help a lot.

**Before you send...**
 - Have you read the `README.md` file or `man bear`?
 - Have you looked what other open issues Bear has?
 - Are you sure that the build works without Bear?

**Comment by rizsotto** [comment]
Hey @strangerby , can you provide some details what is the problem you have? It's not clear from your description.

`bear -- make` does not work?
