### ISSUE TITLE
Intercept shall use SQLight instead of memory for the received events

### ISSUE THREAD

**Issue by rizsotto** [rizsotto/Bear#343]
Currently the process lifetime events are arriving to `intercept` via gRPC and those events gets processed and stored in the memory. This hurts when compiling big projects.

- intercept shall just append all received events into an SQLight database file.
- citnames can read that file to create the JSON compilation database.

Event table can have:

- event id, unique id generated when the event received.
- reporter id (is in the message), unique id of the reporter. (all events belongs to the same process will share this id. was introduced when the PID were not unique enough.)
- timestamp (is in the message), when the message was created
- event itself (as a JSON field)

**Comment by rizsotto** [comment]
The `intercept` command has nearly constant memory allocation. (Allocation fragmentation is still there, but the new memory allocation rate is significantly less.) Here are the before and after pictures

![intercept old](https://user-images.githubusercontent.com/1200425/104580991-1156ca00-56b2-11eb-92a9-d2952b30d492.png)
![intercept new](https://user-images.githubusercontent.com/1200425/104581007-174cab00-56b2-11eb-867c-e33e79fb6fad.png)

The `citnames` command still reads all command into memory before it starts the filtering, but the allocation is still smaller than the old version. It got significantly slower 15s from 1s in my measurement. That could be a subject to improve.

![citnames old](https://user-images.githubusercontent.com/1200425/104581491-c2f5fb00-56b2-11eb-80e2-1f70d60fc3c9.png)
![citnames new](https://user-images.githubusercontent.com/1200425/104581367-9510b680-56b2-11eb-86ef-e0cf12690262.png)

**Comment by rizsotto** [comment]
contributes to #350

**Comment by lddfg** [comment]
Oh no. This will greatly slow down the compilation speed.
