### ISSUE TITLE
Fedora 29 rpm

### ISSUE THREAD

**Issue by joaocortes** [rizsotto/Bear#346]
I want to install bear in a fedora 29 installation. I cannot find it in the official repositories, there are only packages for fedora 30, 31, 32.
Could someone release it for fedora 29?

**Comment by rizsotto** [comment]
Hi @joaocortes , you can try to install it from sources. (I would recommend the 2.4.4 version as a start.)

https://src.fedoraproject.org/rpms/bear would be the place to ask for packages. The rpm `.spec` file is also there, you can use that to build a package on fedora 29 I guess.

**Comment by joaocortes** [comment]
Thanks, version 2.4.4 builds with no issues
