### ISSUE TITLE
library not found for -labsl_dynamic_annotations

### ISSUE THREAD

**Issue by spachner** [rizsotto/Bear#347]
**Describe the bug**
Does not link: "ld: library not found for -labsl_dynamic_annotations"

**To Reproduce**
checkout master
cmake -DENABLE_UNIT_TESTS=OFF -DENABLE_FUNC_TESTS=OFF .. && make all

**Expected behavior**
should link

**Environment:**
 - OS name: MacOS 11.1
 - Bear version: master/3.0.6
 - Bear install method: from source

**Additional context**
brew does only install 2.4. Have problems to get bear work for cross compiler arm-none-eabi-gcc and would like to try an recent version, but does not link

**Comment by rizsotto** [comment]
See #344 

```c
#include <grpc/grpc.h>
int main() {
  grpc_init();
  grpc_shutdown();
  return GRPC_STATUS_OK;
}
```

If you can build ^ this source file, with the following build script, you can build Bear too.

```shell
PKG_CONFIG_PATH=$(brew --prefix)/opt/openssl@1.1/lib/pkgconfig
CFLAGS=$(pkg-config --cflags --libs protobuf grpc++)
cc test.cc -o test $CFLAGS
```

**Comment by spachner** [comment]
Hi,

thanks for quick answering. Yes, same with your test programm, so it seems to be a brew MacOS issue.

```
$ cc test.cc -o test $CFLAGS
ld: library not found for -labsl_dynamic_annotations
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
