### ISSUE TITLE
compile_commands.json is empty

### ISSUE THREAD

**Issue by Kurt-Shiwz** [rizsotto/Bear#351]
macos: 11.1 (20C69)
11.1 (20C69)

![image](https://user-images.githubusercontent.com/7554917/104332084-c65e7a80-552a-11eb-90b9-b5b83c1fa57c.png)
![image](https://user-images.githubusercontent.com/7554917/104332122-cd858880-552a-11eb-8014-71dace76cd1b.png)
![image](https://user-images.githubusercontent.com/7554917/104332062-c0689980-552a-11eb-8ac4-6acd48f1b49d.png)

**Comment by rizsotto** [comment]
Please fill out the [bug report](https://github.com/rizsotto/Bear/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) template.
