### ISSUE TITLE
Unrecognized parameter in version 3.x

### ISSUE THREAD

**Issue by BrushXue** [rizsotto/Bear#358]
**Describe the bug**
Something wrong with the recent version(3.x).
Rolled back to 2.4.4_1 and the code successfully compiled

Installation script:
```shell
export BEAR_COMPILE_PREFIX="bear --append --cdb=$(pwd)/compile_commands.json"
```
Result:
```shell
Unrecognized parameter: "--cdb=/Users/gux215/OpenFOAM/swak4Foam/compile_commands.json"
Usage: bear [--output <arg>] [--verbose] -- ...
```

**To Reproduce**
Update to the latest version.

**Expected behavior**

**Environment:**
 - OS name: macOS
 - OS version: 10.15.7
 - OS architecture: x86_64
 - Bear version: 3.0.8
 - Bear install method: brew

**Additional context**
Xcode 12.4
```shell
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by rizsotto** [comment]
Have you tried `bear --help` or `man bear`? Some Bear command line parameter has been changed.
