### ISSUE TITLE
Reduce grpc clone size with shallow clone

### ISSUE THREAD

**Issue by lyu** [rizsotto/Bear#361]
**Describe the bug**
Accessing GitHub is very slow at my location and so cloning the grpc submodule takes very very long.

**To Reproduce**
Build Bear and wait for 30+ minutes, because it clones the full commit history of a grpc release branch.

**Expected Behavior & Suggested Solution**
Only clone the last commit/HEAD of a branch of grpc, using `GIT_SHALLOW 1` as described [here](https://cmake.org/cmake/help/v3.6/module/ExternalProject.html). This reduces the clone size from 354M to 75M.

**Comment by rizsotto** [comment]
Thanks for the tip @lyu !

I've made the fix on latest `master` branch. Will be available for the next release.
