### ISSUE TITLE
Support for jobserver in submake (pass clean fds)

### ISSUE THREAD

**Issue by whitty** [rizsotto/Bear#365]
**Describe the bug**
When running bear under a `make`-rule the jobserver (parallel builds) is squashed probably because the jobserver fds are not passed intact:

Sorry the make docs aren't too clear here:  https://www.gnu.org/software/make/manual/make.html#Job-Slots

This is a more cromulent description:
https://stackoverflow.com/a/30001985/384507

`make` passes parallel control to sub-makes (when invoked either with `+` prefix or as `$(MAKE)`) by opening a socket on the next fds (usually 3, 4) to communicate with the parent make.  You can see them in `MAKEFLAGS= -j8 --jobserver-auth=3,4 -- ` - where `jobserver-auth` specifies which fds were used

If a wrapper (eg `bear`) doesn't pass them unmolested then make falls back to `-j1` and warns (see below).  I know this because my wrapper in that stackoverflow issue was the culprit last time (python subprocess `close_fds` options).

**To Reproduce**

Assuming you are in a make system for which `make -j8 all` works as expected:

```
.PHONY: bear_gen
bear_gen:
	$(MAKE) clean
	+bear $(MAKE) all
```

`make -j8 bear_gen` should first clean, then run make all under `bear` with the jobserver (ie parallel builds).  However instead the `all` step runs not in parallel and you see the following warning:

```
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

**Expected behavior**

`make -j8 bear_gen` should first clean, then run make all under `bear` with the jobserver (ie parallel builds).  No warning should be emitted (see above).

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 20.04 
 - OS architecture: x86_64
 - Bear version: 2.4.3 (focal/universe)
 - Bear install method: `apt install bear`
 
**Additional context**
 - Can you give us a reference to the project that you are running against this tool? - sorry no
 - What build tools this project is using? GNU make 4.2.1
 - What architecture you are trying to compile for? Reproducible natively - in fact I am trying to encapsulate some cross-compilation stuff, but it all works fine when invoked manually (not under make) - but for reusability, environment setup and consistency I'm trying to generate it under our make system.
 - Could you attach build logs? I'm hoping you won't need them - can provide if desired

**Before you send...**
 - Have you read the `README.md` file or `man bear`? - nothing apropos in the manual
 - Have you looked what other open issues Bear has? - searched for "jobserver" - nothing
 - Are you sure that the build works without Bear? - the build works _with_ bear, its just sub-optimal

**Comment by whitty** [comment]
I had a quick look if I could adjust the exec call - then saw the code is more "frameworky" than just posix `exec` calls.  If you have any pointers where to look I might be able to have a closer look myself.

**Comment by whitty** [comment]
ok that last comment may be garbage - I looked at `source/bear/main.cc` but the packaged version on 20.04 might be python,...  I'll shut up until someone with knowledge makes a comment.

**Comment by rizsotto** [comment]
Hey @whitty , thanks for this report.

I don't know much about the jobserver option in Make. I'll look into it. (If you could build a small project where I can reproduce that would be helpful. But will try to do it myself if not.) If I can fix this in Bear, that will be on the new 3.0 version. (As you noticed your package version is 2.4.3, but the latest is 3.0.9.)

**Comment by whitty** [comment]
Here's a simple reproduction

https://gist.github.com/whitty/6481730a142db5ae933037897da57587

```
make bear -j8
usr/bin/make clean
make[1]: Entering directory '/home/greg/home/bear/test'
rm -f done
make[1]: Leaving directory '/home/greg/home/bear/test'
bear /usr/bin/make all
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/greg/home/bear/test'
touch done
make[1]: Leaving directory '/home/greg/home/bear/test'
```

I realised now that i'm on the old (python branch) - and the fix from my other python wrapper works fine too:

[0001-bear.py-fix-GNU-make-jobserver-handing-of-fds.patch.gz](https://github.com/rizsotto/Bear/files/6135953/0001-bear.py-fix-GNU-make-jobserver-handing-of-fds.patch.gz)

I don't know if this issue reproduces against the newer non-python bear.

**Comment by whitty** [comment]
> I don't know if this issue reproduces against the newer non-python bear.

I'd contribute you a test-case but I can't parse out how I would craft one in your test language

This may be the least informative page I've seen for a testing framework: https://llvm.org/docs/CommandGuide/lit.html#local-configuration-files

**Comment by rizsotto** [comment]
Thanks @whitty for your effort.

The test can be any file (they are usually shell scripts in my project). Each file is a test case. The `RUN: ` lines in the comments are executed during the test. I usually put the verification there too (and have a tool or command which verifies the result). The file body can be anything. I use it to prepare the test itself (like create input files or build files).

This case to prepare and run the test is easy. But assert the correct behavior is hard (grepping the output might be very Linux specific). If you know a good validation for it, that would be already a big help.

**Comment by whitty** [comment]
This is what I tried to do

```
#!/usr/bin/env sh

# REQUIRES: shell
# RUN: cd %T; make -f %t.mk -j8 bear 2>&1 > %t.out
# XFAIL: grep "jobserver unavailable" %t.out

cat > make_jobserver_safety.mk <<EOF
.PHONY: all clean bear
all:
	touch done

clean:
	rm -f done

bear:
	$(MAKE) clean
	bear $(MAKE) all
EOF

```

* Firstly it doesn't work
* I assume invokation of `bear` in the make file needs to be changed to invoke the newly built bit
* I'm not sure of the relationship between the top half (comments) and the bottom half 
** I'm not sure any of this ever runs - the entire test-suite dies on a timeout
```
...
1: PASS: bear :: cases/compilation/output/assembly_sources.mk (16 of 89)
1/1 Test #1: bear::func_test ..................***Timeout  90.11 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  90.54 sec

The following tests FAILED:
          1 - bear::func_test (Timeout)
```
* I assume XFAIL is supposed to invert the sense of pass

> But assert the correct behavior is hard (grepping the output might be very Linux specific).

That might be the saving thing - assuming you have GNU make as a prerequisite you could expect at least a POSIX grep. perhaps the issue is detecting GNU make in the first place.

**Comment by whitty** [comment]
BTW - it _doesn't_ reproduce on bear 3.0.x - so maybe just close this as fixed by the migration from python - patch applies on 2.x branch

(I just thought adding a test might ensure it doesn't creep in)

**Comment by rizsotto** [comment]
Thanks @whitty , I've tried to reproduce it on the latest master, but end up the same conclusion as you. :) I'm closing it now.
