### ISSUE TITLE
Citnames OOM with make linux 

### ISSUE THREAD

**Issue by Theodoree** [rizsotto/Bear#366]
**Describe the bug**
l was use bear generate linux compile_commands.js.then oom

**To Reproduce**
git clone https://github.com/torvalds/linux.git
cd linux 
make oldconfig
bear -- make -j 12

**Expected behavior**
the program can use less mem. maybe use some sql can clear this 

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 7.5.0-3ubuntu1~18.04
 - OS architecture: x86_64
 - Bear version: bear 3.0.9
 - Bear install method: source build 
 - 40GB RAM, 16 cores

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? no
 - What build tools this project is using? GNU Make 4.1
 - What architecture you are trying to compile for? x86
 - Could you attach build logs? can provide if desired

**Comment by Theodoree** [comment]
l can provide sqlite3

**Comment by rizsotto** [comment]
Thanks for the report @Theodoree , I'm tracking this problem on #350 , which deals with the root cause of it.

**Comment by rizsotto** [comment]
Hey @Theodoree , I've just released 3.0.10, which has a few fixes on the memory consumption. Could you try if it fixes your problem?

I've been running Bear against the linux kernel sources, and it still allocates what it would be reasonable, but did not OOM to me.
