### ISSUE TITLE
[This is not an issue but a question] : How about gRPC

### ISSUE THREAD

**Issue by didier31** [rizsotto/Bear#368]
Hi  László !

I've just succeeded to build Bear on OpenBSD (Yes, that's easily possible) in order to document its kernel with clang-doc.

I've run it. It seems to work well until this :

_gRPC failed to connect to all addresses_

I guess a server should run in background.
But what am I supposed to do ?

Thanks a lot !

I can't wait for it to work :smiley: 

Have a nice day
Cheers

**Comment by rizsotto** [comment]
Hey @didier31 , thanks for the report. It's exciting to try out Bear on platform I've never tried. :) To help you I need a bit context. Which version did you installed? Did you have to make changes in the source in order to compile/install? What is the gRPC dependency version?

And it would be also helpful if you can put the exact log lines (a few lines before and after) when you run the tool in verbose mode. (So, I could picture where it fails.)

**Comment by didier31** [comment]
Thank you, László for your quick response.

I thought it was a bad usage of my own. This seems not from your message.

As a result, what I have to do the best is to make run tests. 
Indeed, googletest has been adapted for OpenBSD 6.7 10 months ago. The last release of googletest dates from 2019. Today, I have modified third_party/googletest/CMakeLists.txt to download googletest/head. And googletest builds on OpenBSD.

As this time, Bear tests fail to build. I will do the necessary, tomorrow.

Nice day to you

**Comment by didier31** [comment]
Here is mods on bear code :
[Bear-3.0.9-wd.diff.txt](https://github.com/rizsotto/Bear/files/6217795/Bear-3.0.9-wd.diff.txt)

Here is cmake output :
[cmake.log](https://github.com/rizsotto/Bear/files/6217801/cmake.log)

Here is '$ make' output :
[make.log](https://github.com/rizsotto/Bear/files/6217802/make.log)

Here is '$ make install' output :

Here is '$ bear -- make' output :
[bear_--_make.log](https://github.com/rizsotto/Bear/files/6217804/bear_--_make.log)

Here is '$ bear --verbose -- make' output:
[bear_--verbose_--make.log](https://github.com/rizsotto/Bear/files/6217805/bear_--verbose_--make.log)

Thank you for your help
Hoping it helps

**Comment by rizsotto** [comment]
Thanks @didier31 for the follow up!

Ok, it looks like a bug in Bear. I did not implemented the io redirects in the wrapper I am afraid. Will fix it in the next release.

**Comment by didier31** [comment]
Happy to contribute to improve Bear's reliability, László :-)

**Comment by rizsotto** [comment]
Hey @didier31 , I'm trying to reproduce this error on my linux machine, but could not get this error.

I am looking again at the logs you've sent, and noticed these lines.

```
[14:33:25.454419, el, 51111] lib.cc; execvp file: /bin/sh
[14:33:25.454905, el, 51111] lib.cc; execvp failed.
/bin/sh: Bad address
```

What would be the reason to not able to exec `/bin/sh`? Is it exists? Has executable rights? Is it statically linked?

**Comment by didier31** [comment]
I can't understand because all seems right :
```
[didier@nimbus /usr/home/didier]$ which sh
/bin/sh
[didier@nimbus /usr/home/didier]$ sh
$ ldd /bin/sh
/bin/sh:
        libedit.so.7 => /lib/libedit.so.7 (0x800272000)
        libc.so.7 => /lib/libc.so.7 (0x8002ad000)
        libncursesw.so.8 => /lib/libncursesw.so.8 (0x8006a3000)
$ file /bin/sh
/bin/sh: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 12.2, FreeBSD-style, stripped

```

**Comment by didier31** [comment]
I can't understand because all seems right :

```
ours# uname -a
OpenBSD ours.home 6.8 GENERIC#97 amd64
ours# which sh
/bin/sh
ours# ldd /bin/sh
/bin/sh:
	Start            End              Type  Open Ref GrpRef Name
	00000bbb6e31e000 00000bbb6e3c4000 dlib  1    0   0      /bin/sh
ours# file /bin/sh
/bin/sh: ELF 64-bit LSB shared object, x86-64, version 1
```

**Comment by rizsotto** [comment]
I was thinking more about this problem... Is there a way you can run Bear with the compiler wrappers?

`bear --verbose --force-wrapper -- make` would be the command. It works if the build of the project is respecting the `CC` and `CXX` environment variables. (Hardwired compiler path might not work.)

**Comment by didier31** [comment]
Sorry, I've given up to use Bear.
I've developed my own C crossref tool thanks to prolog DCG feature.
