### ISSUE TITLE
Empty compile_commands.json when using ccache

### ISSUE THREAD

**Issue by kdkasad** [rizsotto/Bear#372]
**Describe the bug**
When using `ccache` as a compiler wrapper, the resulting `compile_commands.json` file is empty. When I remove the `cc` override symlink from my path, it works fine.

**To Reproduce**
1. Add a symlink from `cc` -> `/usr/bin/ccache`
2. Add that symlink to the beginning of your `$PATH`

**Expected behavior**
The `compile_commands.json` file should contain the compile commands.

**Environment:**
 - OS name: Linux
 - OS version: Arch Linux
 - OS architecture: x86_64
 - Bear version: 3.0.11
 - Bear install method: from distro package

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? [gl01.zip](https://github.com/rizsotto/Bear/files/6394588/gl01.zip)

 - What build tools this project is using? GNU make
 - What architecture you are trying to compile for? x86_64
 - Could you attach build logs? [bear.log](https://files.kasad.com/files/bear.log)

**Various useful info:**
This is the value of `$PATH` that results in an empty `compile_commands.json` file:
```sh
$ echo $PATH
/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

The first directory in the `PATH` overrides `cc`, `c++`, etc. with symlinks to the `ccache` binary:
```sh
$ ls -lah /usr/lib/ccache/bin
total 8.0K
drwxr-xr-x 2 root root 4.0K Apr 27 11:39 .
drwxr-xr-x 3 root root 4.0K Aug  2  2020 ..
lrwxrwxrwx 1 root root   15 Apr 26 16:25 c++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 cc -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 clang -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 clang++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 g++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 gcc -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 x86_64-pc-linux-gnu-c++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 x86_64-pc-linux-gnu-g++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Apr 26 16:25 x86_64-pc-linux-gnu-gcc -> /usr/bin/ccache
```

When I remove that directory from the `PATH`, everything works fine. Here's the resulting `compile_commands.json` when **not** using `ccache`: [compile_commands.json.zip](https://github.com/rizsotto/Bear/files/6394655/compile_commands.json.zip)

**Comment by rizsotto** [comment]
@kdkasad could you try the new version on `fixes` branch? I have a fix that works with the test harness running with `ccache`.

**Comment by kdkasad** [comment]
> @kdkasad could you try the new version on `fixes` branch? I have a fix that works with the test harness running with `ccache`.

The problem doesn't happen when using the `fixes` branch

**Comment by rizsotto** [comment]
Thanks @kdkasad for the quick feedback. Will make a new release in this month.
