### ISSUE TITLE
Bear Incorrect Handling of Ccache v4.3

### ISSUE THREAD

**Issue by Jacobfaib** [rizsotto/Bear#377]
**Describe the bug**
Bear calls ccache v4.3 incorrectly by not telling ccache which compiler to use. From `ccache --help`:
```
$ ccache --help
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)
...
```
But Bear does the following:
```
[12:03:01.579423, wr, 78502, ppid: 78493] Process spawned. \
[pid: 78503, command: [/usr/local/Cellar/ccache/4.3/bin/ccache, bearTest.c,  -o, bearTest]]
```
resulting in
```
ccache: error: Could not find compiler "bearTest.c" in PATH
```

**To Reproduce**
bearTest.c:
```
int main(int argc, char **argv)
{                                                                                                   
  return 0;
}
```
Then setup system like so
```
// ccache was installed long before bear on my system, so do in this order to simulate this if it matters
brew install ccache
export PATH="/usr/local/opt/ccache/libexec:$PATH"
brew install bear
bear -- make bearTest
```

**Expected behavior**
Bear should invoke the compiler after "ccache":
```
/path/to/ccache clang [compiler options]
```

**Environment:**
 - OS name: Darwin
 - OS version: macOS Big Sur v 11.3.1
 - OS architecture: x86_64
 - Bear version: stable 3.0.11
 - Bear install method: homebrew

**Additional context**
- What build tools this project is using? 
 None
 - What architecture you are trying to compile for? 
 Native
 - Could you attach build logs? If you can re-run the command which failed (e.g. `bear make`) with extra verbose log switches (e.g. `bear -vvvv make`) and send the output of it, that would help a lot.
 
So you might not actually get the exact form of the output I show above, but I am almost certain this is what is happening under the hood. My real test case is compiling the [PETSc library](https://gitlab.com/petsc/petsc). Here you actually see the bad call:
```
[12:03:01.579423, wr, 78502, ppid: 78493] Process spawned. [pid: 78503, command: \
[/usr/local/Cellar/ccache/4.3/bin/ccache, -fPIC, -fstack-protector, -fno-stack-check, \
-Qunused-arguments, -g3, -Wno-implicit-function-declaration, -E, \
-I/Users/jacobfaibussowitsch/NoSync/petsc/include, \
-I/Users/jacobfaibussowitsch/NoSync/petsc/arch-darwin-c-debug/include, \
-I/Users/jacobfaibussowitsch/NoSync/petscpackages/include, \
/var/folders/9w/7dlszmmn6q1gd5yf3r9n79bc0000gn/T/petscmpi-XXXXXXXX.pf9kuOzY/mpitest.c, \
-I/Users/jacobfaibussowitsch/NoSync/petscpackages/include]]
```
which makes ccache produce the following complaint:
```
ccache: invalid option -- f
```
Since it thinks `-fPIC` is an option intended for it. However the above case is also more complex, as I use ccache to wrap mpi compiler wrappers. Not sure if this is more complicated to handle for bear or not. Note that disabling ccache (by removing `/usr/local/opt/ccache/libexec` from my `$PATH`) makes all of this work. 

This may possibly be related to #372

**Comment by Jacobfaib** [comment]
Let me know if you need me to provide you with any other info! I tried getting the full output of `bear --verbose` by doing
```
bear --verbose -- make bearTest > ./bearLog.txt
```
however this only put the compile command (i.e. `cc bearTest.c -o bearTest`) into the file while still printing bears logging output to stdout. Even redirecting via `2>&1` didn't change things. Is there another way it is supposed to be done? Worst case I can copy paste from terminal into a file but then this would include a bunch of bogus line-breaks.

**Comment by rizsotto** [comment]
@Jacobfaib  could you try the new version on fixes branch? I have a fix that works with the test harness running with ccache.

**Comment by rizsotto** [comment]
I believe this is fixed on latest master.

**Comment by Jacobfaib** [comment]
Sorry for late reply, yes I can confirm this is fixed! Thanks.
