### ISSUE TITLE
Empty compile_commands.json for building bitcoind

### ISSUE THREAD

**Issue by SwJay** [rizsotto/Bear#382]
**Describe the bug**
Bear produces empty json for bitcoind.
Actually, I've built it before using bear. Then I run `make clean` and build it again with bear, but it gives empty json again. Finally I start from git clone to get a clean workspace and build it with bear from beginning, but it still yields empty json file.

**To Reproduce**
1. `git clone git@github.com:bitcoin/bitcoin.git`
2. install dependencies for bitcoind according to its doc.
3. build with bear
```
bear ./autogen.sh
bear ./configure
bear make
```

**Expected behavior**
non-empty json file.

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 18.04
 - OS architecture: x86_64
 - Bear version: 2.3.11
 - Bear install method: apt install

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? 
https://github.com/bitcoin/bitcoin
 - What build tools this project is using?
 GNU make
 - What architecture you are trying to compile for?
 Compile on Linux
 - Could you attach build logs? If you can re-run the command which failed (e.g. `bear make`) with extra verbose log switches (e.g. `bear -vvvv make`) and send the output of it, that would help a lot.
 The project is large and the log is way too long to paste.

**Before you send...**
 - Have you read the `README.md` file or `man bear`?
 yes
 - Have you looked what other open issues Bear has?
 yes
 - Are you sure that the build works without Bear?
 yes

**Comment by rizsotto** [comment]
Thanks for the report @SwJay . Is there any way you could use the latest version of Bear? (The version you are using is about 4 years old.)

And either way (if you are using the new one or the old) I'll need some logs in order to help you. Could you attach the output of a verbose run? Or you can try to debug yourself, it's not that difficult. (It first intercepts the executed commands, then it try to recognize if it was a compiler call. Empty output means any of them is failing.)

**Comment by SwJay** [comment]
Thanks for your reply, and I'll try with the latest version first. If I failed to debug myself, I'll upload the log file and seek for help. Thanks!

**Comment by SwJay** [comment]
@rizsotto I've checked that the version 2.3.11 is the latest package on ubuntu 18.04. I built with bear [3.0.11] on macOS and it produces perfect json file.I reproduced the process and have log files [here](https://drive.google.com/drive/folders/1opEZP-KmFxDcgvP1eiw47bRwSDVpkHYE?usp=sharing) corresponding to three building steps.

**Comment by rizsotto** [comment]
I'm glad that you could use Bear to generate the desired JSON compilation database.

I'm closing this issue then. The newlocal errors are fixed since 2.3.11. :)
