### ISSUE TITLE
support for cross-compilers

### ISSUE THREAD

**Issue by BaoshanPang** [rizsotto/Bear#386]
It is documented there(https://github.com/rizsotto/Bear/wiki/Usage#cross-compilers):
_Cross compilers should work with Bear. If Bear works with a native compiler then it should work with a cross compiler too. The only catch is that Bear does not know the compiler name to recognize it, so you need to explicitly pass the compiler names. (See --use-cc, --use-c++ or --use-only flags in the help or in the manual page for more.)_

But I get this error:
bear --library libexec.so --use-cc xyz -- xyz
Unrecognized parameter: "--use-cc"
Usage: bear [--output <arg>] [--verbose] -- ...

What's the approach now to specify a cross-compiler?

Thanks,
Baoshan

**Comment by rizsotto** [comment]
Looks like the wiki is out of date. Sorry about that @BaoshanPang .

The wiki page talks about Bear 2.4 version. The 3.x you've been trying using environment variables and configuration file to detect the compiler... `CC=/path/to/cross/compiler bear -- make` should do the work. Or you can specify the compiler name in a configuration file (read `man citnames` about that).
