### ISSUE TITLE
add -lstdc++fs for gcc support

### ISSUE THREAD

**Issue by huixie90** [rizsotto/Bear#391]
**Describe the bug**
The project doesn't build  with gcc8.3 due to a linker error

/usr/bin/ld: Path.cc:(.text+0x119e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'

By default gcc doesn't link to <filesystem> standard library

**To Reproduce**
build the project with gcc 8.3

**Expected behavior**
The project should build

**Environment:**
 - OS name: Linux
 - OS version:  Debian 10
 - OS architecture: x86_64
 - Bear version: git clone
 - Bear install method: build from source

**Comment by rizsotto** [comment]
https://github.com/rizsotto/Bear/issues/305#issuecomment-749002592 has some hints how to compile with older gcc.
