### ISSUE TITLE
[Feature Request] Exclude flags

### ISSUE THREAD

**Issue by ofir753** [rizsotto/Bear#405]
Some gcc flags aren't supported by clang as far as I know it's only optimization flags which aren't important to compile commands.  There is an option to include extra flags but not to exclude flags.

**Comment by rizsotto** [comment]
He @ofir753 , thanks for your report. Not sure if I understand correctly, but in the latest version there is way to filter out specific compiler flags. (Read the [man page](https://github.com/rizsotto/Bear/blob/master/source/citnames/man/citnames.1.md) of `citnames` command for the configuration file.)
