### ISSUE TITLE
ld-elf.so.1: Cannot open "/usr/local/$LIB/bear/libexec.so" on FreeBSD

### ISSUE THREAD

**Issue by Jehops** [rizsotto/Bear#409]
**Describe the bug**
I'm working on upgrading the FreeBSD package to 3.0.15.  Run-time testing now gives the error in the subject.  It ran fine in version 3.0.14.  This happens regardless whether supplying a value for `DCMAKE_INSTALL_LIBDIR`.

**Environment:**
 FreeBSD 13.0

**Comment by wortiz** [comment]
Same thing happens on Ubuntu 20.04 (with latest cmake)

Seems it was introduced with e796080d as reverting that commit appears to fix the issue

**Comment by rizsotto** [comment]
@wortiz The `INSTALL.md` has instruction how to make that work on Debian derivative Linux distributions. Basically you need to expand the `$LIB` to `lib/x86_64-linux-gnu`. (So, when you install it to your home, you still need to check if the `libexec.so` file is in `/home/wortiz/.local/opt/bear-3.0.15/lib/x86_64-linux-gnu/bear/libexec.so`.)

**Comment by rizsotto** [comment]
@Jehops can you help me out, if `$LIB` is a known literal by the dynamic linker on FreeBSD? In linux it does expand to the right library name where the dynamic linker would search for files (see [this man page](https://manpages.ubuntu.com/manpages/cosmic/man8/ld.so.8.html)).

If that is not exists on FreeBSD, then I'll come up with a workaround for it.

**Comment by Jehops** [comment]
@rizsotto, unfortunately [it doesn't seem to have that particular token string](https://www.freebsd.org/cgi/man.cgi?query=ld.so).

**Comment by rizsotto** [comment]
@Jehops , `devel` branch has a version which does check the OS type and does the `$LIB` only on linux. Could you try that out? If that works, I'm making a release with this fix.

**Comment by Jehops** [comment]
@rizsotto, I tested g5fc0c86 and it works.  Thank you.

**Comment by rizsotto** [comment]
Fix released as `3.0.16`
