### ISSUE TITLE
Is there any way to extract the absolute path of the compiler used in the project compilation process?

### ISSUE THREAD

**Issue by tr4v3ler** [rizsotto/Bear#413]
Is there any way to extract the absolute path of the compiler used in the project compilation process instead of cc? The project I used to extract used multiple preset compilers during compilation and construction, but all the results I extracted were displayed as cc.
For example, I want the result like this:
`"arguments": [
    "/home/tr4v3ler/data/mtk_kernel/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc",
    "-c",
    "-Wp,-MD,lib/.ratelimit.o.d",`
but not this:
`"arguments": [
    "cc",
    "-c",
    "-Wp,-MD,lib/.ratelimit.o.d",`
My project environment is as follows:
Ubuntu 18.04.5 LTS
bear 2.3.11
[mtk_kernel](https://drive.google.com/open?id=0B4XwT5D6qkNmLXdNTk93MjU3SWM)

**Comment by rizsotto** [comment]
Version `3.0.x` has fix for it.

**Comment by tr4v3ler** [comment]
> Version `3.0.x` has fix for it.

Thank you for your reply. In addition, may I ask why there is no bear 3.0. X release on Ubuntu 18.04.5?

**Comment by rizsotto** [comment]
I am not doing the packaging, so don't know the answer... Check out the discussion #408 about to compile it on that distribution.
