### ISSUE TITLE
RFE: disable http proxy by gRPC channel parameter

### ISSUE THREAD

**Issue by ensc** [rizsotto/Bear#419]
**Describe the bug**

`bear` fails here with

`wrapper: failed with: gRPC call failed: failed to connect to all addresses
`

because `no_proxy` does not contain `127.0.0.1` (but only `localhost` because pure IP addresses are rarely used with HTTP).

Would it be possible to set the `GRPC_ARG_ENABLE_HTTP_PROXY` channel parameter which has been [added](https://github.com/grpc/grpc/pull/15699/commits/21dbaab4be595bc2f34890e92f3656a61694e522) to recent gPRC?

**Comment by tr4v3ler** [comment]
> Hey @ensc , thanks for this report. I've seen your other comment, which suggest too use `localhost`.
> 
> I've just pushed a fix for it on `devel` branch, which using the `dns:///localhost:0` for the gRPC bind. Could you try it out if this is a fix to your problem?

Last time I met this problem using bear 3.0.16 compiled on Ubuntu 20, and then solved it by setting `no_proxy=localhost,127.0.0.1`. But today I met this problem again when using bear 3.0.16 compiled on Ubuntu 18, and then setting `no_proxy=localhost,127.0.0.1` can not solve it.

**Comment by rizsotto** [comment]
Closing due inactivity. Fix for this is on `master` branch now. Will be released as `3.0.17` this month.

**Comment by tr4v3ler** [comment]
> Closing due inactivity. Fix for this is on `master` branch now. Will be released as `3.0.17` this month.

It seems that the problem has not been solved in 3.0.17:
```
┌──[tr4v3ler@ubuntu]-[~/data/tmp]
└─$ bear --version
bear 3.0.17
┌──[tr4v3ler@ubuntu]-[~/data/tmp]
└─$ g++ test.cc -std=c++17 -o test
┌──[tr4v3ler@ubuntu]-[~/data/tmp]
└─$ bear -- g++ test.cc -std=c++17 -o test
wrapper: failed with: gRPC call failed: failed to connect to all addresses
┌──[tr4v3ler@ubuntu]-[~/data/tmp]
└─$ unset http_proxy https_proxy                                                                                                                                                                                                       1 ↵
┌──[tr4v3ler@ubuntu]-[~/data/tmp]
└─$ bear -- g++ test.cc -std=c++17 -o test
E1115 21:09:42.449045364   35684 ev_epollex_linux.cc:515]    Error shutting down fd 11. errno: 9
E1115 21:09:44.455779580   35691 ev_epollex_linux.cc:515]    Error shutting down fd 11. errno: 9
E1115 21:09:46.456795170   35691 ev_epollex_linux.cc:515]    Error shutting down fd 12. errno: 9
E1115 21:09:48.466992123   35699 ev_epollex_linux.cc:515]    Error shutting down fd 11. errno: 9
E1115 21:09:50.467937098   35699 ev_epollex_linux.cc:515]    Error shutting down fd 12. errno: 9
E1115 21:09:52.473912816   35705 ev_epollex_linux.cc:515]    Error shutting down fd 11. errno: 9
E1115 21:09:54.474887079   35705 ev_epollex_linux.cc:515]    Error shutting down fd 12. errno: 9
E1115 21:09:55.471382782   35684 ev_epollex_linux.cc:515]    Error shutting down fd 14. errno: 9
E1115 21:10:05.512145709   35711 ev_epollex_linux.cc:515]    Error shutting down fd 13. errno: 9
E1115 21:10:07.493078909   35711 ev_epollex_linux.cc:515]    Error shutting down fd 12. errno: 9
```

**Comment by rizsotto** [comment]
@tr4v3ler what does this command prints to you `host localhost`?

**Comment by tr4v3ler** [comment]
> @tr4v3ler what does this command prints to you `host localhost`?

```
host localhost 
localhost.***.com has address 127.0.0.1
```
"*" indicates some sensitive information.

**Comment by rizsotto** [comment]
Ok, will try to reproduce it.. Could you tell me more about your setup? (What architecture your CPU has? What OS you run? What distribution you run? In case of linux can you show the `ip a` output section for the loopback device? What is your proxy config? And anything else which you might think can be relevant.)

**Comment by tr4v3ler** [comment]
> Ok, will try to reproduce it.. Could you tell me more about your setup? (What architecture your CPU has? What OS you run? What distribution you run? In case of linux can you show the `ip a` output section for the loopback device? What is your proxy config? And anything else which you might think can be relevant.)

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 18.04.6 LTS
 - OS architecture: x86_64
 - Bear version: 3.0.17
 - Bear install method: build from source
 - the output of `ip a`: 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e8:4d:d0:**:**:** brd ff:ff:ff:ff:ff:ff
    inet 10.176.**.***/** brd 10.176.**.255 scope global enp1s0f0
       valid_lft forever preferred_lft forever
    inet6 fe80::ea4d:d0ff:feb2:9e61/64 scope link 
       valid_lft forever preferred_lft forever
3: enp1s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether e8:4d:d0:**:**:** brd ff:ff:ff:ff:ff:ff
7: tap0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 9a:60:1c:fa:1e:e4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fe80::9860:1cff:fefa:1ee4/64 scope link 
       valid_lft forever preferred_lft forever
```
 - proxy infomation: Because I use the enterprise network, I can only access the external network through proxy, so I have configured http_proxy, https_proxy and no_proxy in the ~/.zshrc file.
