### ISSUE TITLE
How to set CMAKE_INSTALL_LIBDIR after manually compiling GCC?

### ISSUE THREAD

**Issue by tr4v3ler** [rizsotto/Bear#422]
**Describe the bug**
After manually compiling gcc 9.4.0, compile bear and report an error.

**To Reproduce**
Manually compile GCC and install it in the /usr/local/gcc-9 directory, and then use manually compiled GCC to compile bear:
```
# compile gcc 9.4.0
$ ../configure --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu --prefix=/usr/local/gcc-9 --enable-languages=c,c++ --program-suffix=-9
$ make && sudo make install

# compile bear
$ ~/data/tools/cmake-3.21.3/bin/cmake -DENABLE_UNIT_TESTS=OFF -DENABLE_FUNC_TESTS=OFF -DCMAKE_INSTALL_LIBDIR=gcc-9/lib64 ..
$ make all -j40
```
The exception log is as follows:
```
# /home/tr4v3ler/data/tools/Bear/build/subprojects/Stamp/grpc_dependency/grpc_dependency-build-err.log
/home/tr4v3ler/data/tools/Bear/build/subprojects/Build/grpc_dependency/third_party/protobuf/protoc-3.14.0.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/tr4v3ler/data/tools/Bear/build/subprojects/Build/grpc_dependency/third_party/protobuf/protoc-3.14.0.0)
/home/tr4v3ler/data/tools/Bear/build/subprojects/Build/grpc_dependency/third_party/protobuf/protoc-3.14.0.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/tr4v3ler/data/tools/Bear/build/subprojects/Build/grpc_dependency/third_party/protobuf/protoc-3.14.0.0)
make[5]: *** [gens/src/proto/grpc/channelz/channelz.grpc.pb.cc] Error 1
make[5]: *** [gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Error 1
make[4]: *** [CMakeFiles/grpcpp_channelz.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/grpc++_reflection.dir/all] Error 2
make[3]: *** [all] Error 2
```
You can see from the log that /usr/lib/x86_64-linux-gnu/libstdc++.so.6 is used instead of /usr/local/gcc-9/lib64/libstdc++.so.6

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 18.04.6 LTS
 - OS architecture: x86_64
 - cmake version: 3.21.3
 - gcc version: 9.4.0
 - Bear version: 3.0.16
 - Bear install method: build from source

**Comment by rizsotto** [comment]
I am trying to use the issues to track bugs and future works for this project. This is more like a question, or asking help, which I would prefer to do on the discussion (like [this one](https://github.com/rizsotto/Bear/discussions/408)) or I'm happy to chat on [Gitter](https://gitter.im/rizsotto/Bear).

I'm closing this ticket now. Feel free to stay on this ticket, I'll try to help you with this compilation.

**Comment by rizsotto** [comment]
Would you try to install compiler from package?

https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/

**Comment by tr4v3ler** [comment]
> Would you try to install compiler from package?
> 
> https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/

As a temporary solution, we can use:
```
export LD_LIBRARY_PATH=/usr/local/gcc-9/lib64/
```
This allows us to link to the newly compiled dynamic link library.

**Comment by tr4v3ler** [comment]
> Ok, is the filesystem example compiles and runs on your machine?

I set CMAKE_INSTALL_LIBDIR=gcc-9/lib64, `/usr/local/gcc-9/lib64/bear/libexec.so` is generated after compilation. Before that, I added `/usr/local/gcc-9/lib64` to the path of the dynamic linker by modifying the `/etc/ld.so.conf` file, so that GCC 9.4.0 can find the newly installed `libstdc++.so`. However, when I run bear, the following problems still arise. Why can't it find libexec.so?
```
$ bear -- /usr/local/gcc-9/bin/g++-9 ./test.cc -std=c++17 -o test
ERROR: ld.so: object '/usr/local/$LIB/bear/libexec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/$LIB/bear/libexec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/$LIB/bear/libexec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/$LIB/bear/libexec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/$LIB/bear/libexec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/$LIB/bear/libexec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

# it's ok
$ bear  --library /usr/local/gcc-9/lib64/bear/libexec.so -- /usr/local/gcc-9/bin/g++-9 ./test.cc -std=c++17 -o test
```

**Comment by rizsotto** [comment]
https://github.com/rizsotto/Bear/wiki/Troubleshooting#error-messages-which-appears-with-bear TLDR: you need to install the `libexec.so` to `lib/x86_64-linux-gnu` and not `lib64` as I recommended earlier.
