### ISSUE TITLE
Any documentation to use?

### ISSUE THREAD

**Issue by cakarmustactalone** [rizsotto/Bear#424]
Guyz sorry but I new to coding in linux , I have problem with my clang set-up. After some researches I came here and do not know what to do after then. So if I go bad sorry for it. My question is simple to explain maybe hard to solve ? Anyway , my opencv source directory is in /usr/include/opencv4/opencv2/ , my projects in ~/Projects/opencv++/. So which command I need to use with bear? The thing in "bear --<your-build-tool>" gives me anxiety about it I have tried some things like bear make, bear cmake but there is no solution etc. Can any one help me with the command notation and directories on it ? I could not found a good notation about commands and directory interactions. The only thing  I see " bear <your build tool>" etc. Any example or any solution to my problem. 
Yeah you can say that why you did not read man pages of it. I did "read" but is not working for me.

Regards.

**Comment by rizsotto** [comment]
Was the [wiki example](https://github.com/rizsotto/Bear/wiki/Usage#example) not helpful?

I've replied to you on gitter, I'm closing this issue.
