### ISSUE TITLE
not all user specified arguments are passed to source subproject

### ISSUE THREAD

**Issue by leleliu008** [rizsotto/Bear#426]
relavent code : https://github.com/rizsotto/Bear/blob/master/CMakeLists.txt#L38-L62

`CMAKE_FIND_ROOT_PATH` and `CMAKE_IGNORE_PATH` are very useful when cross compiling. and these variables are not passed to the source subproject.

I find only pass `CMAKE_PREFIX_PATH` not enought when cross compiling.

**Comment by rizsotto** [comment]
Thanks @leleliu008 , I've made a change which I think will work for you. It's on the `devel` branch. Could you check it out and tell if it works for you?

**Comment by leleliu008** [comment]
@rizsotto I have confirmed that it works for me, thanks.

**Comment by rizsotto** [comment]
Thank you @leleliu008 !

It will be released as `3.0.17` in this month.
