### ISSUE TITLE
Bear 3 hangs after compilation and does not generate a compile_commands.json

### ISSUE THREAD

**Issue by lvaroqui-gpfw** [rizsotto/Bear#432]
**Describe the bug**
Bear 3 hangs after compilation and does not generate a compile_commands.json. This worked fine in Bear 2.

**To Reproduce**
This is on a private repo using a cross compile toolchain.

**Expected behavior**
Bear generates a compile_commands.json, like in bear 2.

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 21.10
 - OS architecture: x86_64
 - Bear version: 3.0.8-1
 - Bear install method: from package

**Additional context**
We seem to be stuck in citnames process which uses 100% of 1 CPU.

**Before you send...**
 - Have you read the `README.md` file or `man bear`?  :heavy_check_mark: 
 - Have you looked what other open issues Bear has? :heavy_check_mark: 
 - Are you sure that the build works without Bear?  :heavy_check_mark:

**Comment by rizsotto** [comment]
Can you try with the latest version? https://launchpad.net/ubuntu/+source/bear

**Comment by lvaroqui-gpfw** [comment]
I compiled from source version 3.0.17 and everything seems to be fine now, thanks!
It seems that 3.0.8 on Ubuntu 21.10 is broken.
