### ISSUE TITLE
Bear 3 is very slow

### ISSUE THREAD

**Issue by delamonpansie** [rizsotto/Bear#436]
Bear 3 is very slow.

It takes about 1 minute to run bear2 on my linux kernel.
I killed bear3 after 15 minutes of waiting.

**How To Reproduce**
```
$ wget -q -O - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.11.tar.xz | tar Jxf -
$ cd linux-5.15.11
$ make defconfig >/dev/null
$ /usr/local/bin/bear --version
bear 2.3.13
$ time /usr/local/bin/bear make -j32 >/dev/null

real	0m44,190s
user	17m0,864s
sys	1m54,277s
$ make clean >/dev/null
$ /usr/bin/bear --version                                                                                                                        
bear 3.0.8
$ time /usr/bin/bear -- make -j32 >/dev/null                                                                                                     
^C
real	29m36,101s
user	29m39,070s
sys	9m17,201s                                                                                          

```
bear2 is built from source, bear3 is default bear in Debian bullseye.

**Comment by rizsotto** [comment]
The performance issue you have with 3.0.8 is solved. Can you try the latest version?

**Comment by delamonpansie** [comment]
```
$ /usr/local/bin/bear --version
bear 3.0.18
$ time /usr/local/bin/bear -- make -j32 >/dev/null

real	1m44,806s
user	21m29,944s
sys	3m21,450s
```
It works, thanks. Perhaps you could give a hint for a Debian package maintainer.
Unfortunately,  it is still twice as slow compared to bear2.

**Comment by rizsotto** [comment]
That's a good news @delamonpansie ! See this [thread](https://github.com/rizsotto/Bear/discussions/399) about packaging.

Yes, the new version is slower, but has more features. Working on to improve it.
