### ISSUE TITLE
source build Bear failed on REL7/GCC8.1 -- SessionLibrary.cc:(.text+0x91e): undefined reference to `std::filesystem::path::_M_split_cmpts()'

### ISSUE THREAD

**Issue by qluo1** [rizsotto/Bear#449]
**Describe the bug**
build from master branch failed with error: 
SessionLibrary.cc:(.text+0x91e): undefined reference to `std::filesystem::path::_M_split_cmpts()'

issue seems related to link c++ filesystem ?!

**To Reproduce**
git clone https://github.com/rizsotto/Bear.git

cd Bear 
mkdir build ; cd build
cmake ../
...
16:13 $ make
[ 19%] Built target grpc_dependency
[ 19%] Built target googletest_dependency
[ 39%] Built target nlohmann_json_dependency
[ 58%] Built target fmt_dependency
[ 78%] Built target spdlog_dependency
[ 80%] Performing build step for 'BearSource'
[  1%] Built target flags_a
[  3%] Built target shell_a
[ 13%] Built target sys_a
[ 16%] Built target main_a
[ 26%] Built target rpc_a
[ 29%] Built target domain_a
[ 32%] Built target events_db_a
[ 45%] Built target exec_a
[ 55%] Built target intercept_a
[ 57%] Linking CXX executable intercept
CMakeFiles/intercept_a.dir/source/collect/SessionLibrary.cc.o: In function `ic::LibraryPreloadSession::supervise(domain::Execution const&) const':
SessionLibrary.cc:(.text+0x91e): undefined reference to `std::filesystem::path::_M_split_cmpts()'

**Environment:**
 - OS name: 
16:18 $ uname -a
Linux d119407-xxx 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Aug 31 20:15:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - Bear version: [e.g. `3.15.0`]
   git master/HEAD
2022-02-05 11:10 +1100 Laszlo Nagy           o [master] {origin/master} {origin/HEAD} {origin/next} test: #443 empty environment still works for gcc
 
 - Bear install method: [e.g. from package]
source build

**Additional context**
 - What build tools this project is using? [e.g. GNU make wtih `configure` script]
16:22 $ cmake -version
cmake version 3.22.1

16:23 $ gcc --version
gcc (GCC) 8.3.1 20190311

**Comment by rizsotto** [comment]
See https://github.com/rizsotto/Bear/issues/305#issuecomment-749002592
