### ISSUE TITLE
Empty Output when cross compiling with docker container

### ISSUE THREAD

**Issue by ReggieMarr** [rizsotto/Bear#452]
'm having trouble cross compiling with a docker container and I can't make sense of the config.

I build using docker so it looks like this
```
docker exec -it bob /bin/bash -c "cd /shared/myrepo && make -f MyMakefile -j -B" 
```

And the output is something like this
```
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -x assembler-with-cpp  -c k60-reset.s -o build/objs/k60-reset.o

But the compile_commands.json is empty

**Comment by rizsotto** [comment]
https://github.com/rizsotto/Bear/blob/master/source/citnames/man/citnames.1.md#config-file

The `compilation.compilers_to_recognize` needs an entry, with the absolute path of `arm-none-eabi-gcc`.
