### ISSUE TITLE
Bear fails to build in red hat 7

### ISSUE THREAD

**Issue by arturo-salinas** [rizsotto/Bear#461]
**Describe the bug**
Dependence fails to build.

**To Reproduce**
export LD_LIBRARY_PATH=/usr/local/lib64                            
CXX_COMPILER=/usr/local/bin/g++                                    
C_COMPILER=/usr/local/bin/gcc                                      
                                                                                 
cmake -DCMAKE_INSTALL_LIBDIR=$LD_LIBRARY_PATH -DENABLE_UNIT_TESTS=OFF \        
       -DENABLE_FUNC_TESTS=OFF -DCMAKE_CXX_COMPILER=$CXX_COMPILER \              
       -DCMAKE_MAKE_PROGRAM=$make \                                              
       -DCMAKE_C_COMPILER=$C_COMPILER ..                                         
                                                                                 
make

**Comment by arturo-salinas** [comment]
[error_build.log](https://github.com/rizsotto/Bear/files/8634594/error_build.log)

**Comment by rizsotto** [comment]
Please check out the compiler version you are using. (And make sure it supports C++17, as the `INSTALL.md` suggests. Maybe try to compile some basic C++17 code to make sure you got that right.)

**Comment by rizsotto** [comment]
Thanks @arturo-salinas , that might be the reason... Could you make a PR when it passing the `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` to the 3rd party dependencies?

**Comment by arturo-salinas** [comment]
yes it is the reason. I tested myself. I create a PR. When can this fix be merged and tagged with a release tag? Thank you     @rizsotto

**Comment by rizsotto** [comment]
Thanks for the PR @arturo-salinas , it's merged to master now. Release will come later (not sure about the date yet).
