### ISSUE TITLE
[enhancements] add support for "-include foo.h" flag

### ISSUE THREAD

**Issue by afm0901x** [rizsotto/Bear#466]
**Describe the bug**
GCC and Clang have a flag to include header file before the parsing step.

**To Reproduce**
Clangd already aware of this flag, I got it working by manually injecting "-include foo.h" to arguments block in compile_commands.json:

```
...
"arguments": [
    "/usr/bin/gcc",
    "-I../include",
    "-I/usr/include/bar/bar-2",
    "-include../foo.h",
...
```

**Expected behavior**
Bear to add -include flag to compile_commands.json.

**Environment:**
 - OS name: Linux
 - OS version: Arch Linux, Kernel 5.18.1
 - OS architecture: x86_64
 - Bear version: 3.0.19
 - Bear install method: Arch Linux Official repo

**Comment by rizsotto** [comment]
Hey @afm0901x , this functionality is already implemented. You can remove or add flags to the compilation database entries.

Read the `man citnames` [config file section](https://github.com/rizsotto/Bear/blob/master/source/citnames/man/citnames.1.md#config-file) to see how to set it up. This config can be passed to Bear as `--config ...`.
