### ISSUE TITLE
Bear reports an error when using scons

### ISSUE THREAD

**Issue by assslove** [rizsotto/Bear#473]
There is no error when I use scons alone, but bear:
bear -- scons -Q -j30 reports the following error:

/usr/local/lib64/bear/wrapper: /tmp/_MEI91yPgm/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/lib64/bear/wrapper)
/usr/local/lib64/bear/wrapper: /tmp/_MEI91yPgm/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/lib64/bear/wrapper)
/usr/local/lib64/bear/wrapper: /tmp/_MEI91yPgm/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib64/bear/wrapper)
/usr/local/lib64/bear/wrapper: /tmp/_MEI91yPgm/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/lib64/bear/wrapper)
/usr/local/lib64/bear/wrapper: /tmp/_MEI91yPgm/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/lib64/bear/wrapper)

ldd /usr/local/lib64/bear/wrapper shows the following:

linux-vdso.so.1 (0x00007fff13466000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efd7f7fd000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007efd7f5f9000)
libz.so.1 => /lib64/libz.so.1 (0x00007efd7f3e2000)
librt.so.1 => /lib64/librt.so.1 (0x00007efd7f1da000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007efd7faa7000)
libm.so.6 => /lib64/libm.so.6 (0x00007efd7ee58000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007efd7fa8a000)
libc.so.6 => /lib64/libc.so.6 (0x00007efd7ea93000)
/lib64/ld-linux-x86-64.so.2 (0x00007efd7fa1d000)

strings /lib64/libstdc++.so.6 |grep GLIBC show following:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.4
GLIBC_2.18
GLIBC_2.16
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
GA+GLIBCXX_ASSERTIONS

**Comment by rizsotto** [comment]
Could you please fill out the issue template? From this information I'm not able to help you.
