### ISSUE TITLE
-DCMAKE_PROJECT_INCLUDE argument is not passed to source subproject

### ISSUE THREAD

**Issue by leleliu008** [rizsotto/Bear#479]
Hi there, I wanna build a statically linked bear execuable, I wanna use `-DCMAKE_PROJECT_INCLUDE=xx.cmake` to inject follwoing code:
```
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
```

but I find that `-DCMAKE_PROJECT_INCLUDE` argument is not passed to source subproject. Although I can edit code directly, but I think it would be better if you could support this argument. maybe someone else want this feature too.

Reference: https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_INCLUDE.html

**Comment by leleliu008** [comment]
temporary solution:

```
sed -i '/-DPKG_CONFIG_EXECUTABLE/a -DCMAKE_PROJECT_INCLUDE=${CMAKE_PROJECT_INCLUDE}' CMakeLists.txt
```

**Comment by rizsotto** [comment]
Hey @leleliu008 could you please raise a PR for this?
