### ISSUE TITLE
Bear fails with Argument list too long

### ISSUE THREAD

**Issue by sambitesh** [rizsotto/Bear#483]
**Describe the bug**
I am trying to run bear with [Brazil](https://gist.github.com/terabyte/15a2d3d407285b8b5a0a7964dd6283b0). It fails with the below error. It won't be possible to reproduce it on your side. 

I should add that eventually the built is passed to [Scons](https://scons.org/)

Does Bear support Scons?
```
bear: Running intercept failed: System call "posix_spawnp" failed for /bin/sh: Argument list too long
bear: failed with: System call "posix_spawnp" failed for /bin/sh: Argument list too long
```

**Expected behavior**
Bear should succeed with a compile_commands.json file

**Environment:**
 - OS name: Linux
 - OS version: Amazon Linux2
 - OS architecture: x86_64
 - Bear version: bear 3.0.20
 - Bear install method: compiled from source code

**Before you send...**
 - Have you read the `README.md` file or `man bear`? Yes
 - Have you looked what other open issues Bear has? Yes
 - Are you sure that the build works without Bear? Yes

**Comment by rizsotto** [comment]
Hey @sambitesh , thanks for the report.

I've not heard about Brazil, so I don't know how it works. Was the quoted error message from Brazil build? (Or Scons?)

Scons I know of, and it should work with Bear.

**Comment by rizsotto** [comment]
Hey @sambitesh , do you have update on this? Was it working with Scons?

**Comment by rizsotto** [comment]
Can't reproduce it, since I have no access to `brazil`.

Scons known to be working with Bear.
