### ISSUE TITLE
Unrecognized parameter: "make"

### ISSUE THREAD

**Issue by lenghonglin** [rizsotto/Bear#489]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4686802/201045518-add07498-d8a8-43e1-ad2d-15ce950bb7fb.png)

**To Reproduce**

**Expected behavior**
100%

**Environment:**
 - OS name: arch linux
 - Bear version: 3.0.20
 - Bear install method: pacman

**Comment by rizsotto** [comment]
Have you tried `bear -- make`?

I can improve the error message if you tell me what would be better way to do it. Also, have you tried to read the `man bear` page?
