### ISSUE TITLE
Can it support self-defined build command?

### ISSUE THREAD

**Issue by GreenAsFuck** [rizsotto/Bear#494]
I want to use `bear` with self defined build command like `m` `mm` in `android`, but it doesn't seem to work.
```cpp
function m()
(
    call_hook ${FUNCNAME[0]} $@
    if [ $? -ne 0 ]; then
        return 1
    fi
    _trigger_build "all-modules" "$@"
)
```
```
bear: Internal error.
Traceback (most recent call last):
  File "/usr/bin/bear", line 225, in wrapper
    return function(*args, **kwargs)
  File "/usr/bin/bear", line 250, in intercept_build
    exit_code, current = capture(args)
  File "/usr/bin/bear", line 274, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/bin/bear", line 149, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mm': 'mm'
bear: Please run this command again and turn on verbose mode (add '-vvvv' as argument).
```

**Comment by jbmaillet** [comment]
My 2 cents: I've been routinely using bear with full Android build for 3 years.

As you know, `m` `mm` `croot` etc are shell functions defined once you `source buildenvsetup`, intended for the developer to type less on the shell. It never came to my mind to use such commands in my builds / CI. I use plain `make` invocation, which is a file in the path (very different from GNU make of course) and bear works fine.

Of course, I understand that this is a severe case of "ask us what you need, I'll explain you how to do without it" pattern.
¯\_(ツ)_/¯

**Comment by GreenAsFuck** [comment]
> My 2 cents: I've been routinely using bear with full Android build for 3 years.
> 
> As you know, `m` `mm` `croot` etc are shell functions defined once you `source buildenvsetup`, intended for the developer to type less on the shell. It never came to my mind to use such commands in my builds / CI. I use plain `make` invocation, which is a file in the path (very different from GNU make of course) and bear works fine.
> 
> Of course, I understand that this is a severe case of "ask us what you need, I'll explain you how to do without it" pattern. ¯_(ツ)_/¯
I understand what you're saying, and I directly use `make` too.
But sometimes we use `build.sh` to build. And if I use something like ` bear make surfaceflinger 
`  I get this error:
```
build/make/core/main.mk:2: Calling make directly is no longer supported.
build/make/core/main.mk:3: Either use 'envsetup.sh; m' or 'build/soong/soong_ui.bash --make-mode'
build/make/core/main.mk:4: *** done.  Stop.
```
Maybe I'll have to modify many `mk` files to make it work.
Strangely enough though, if I directly use `make surfaceflinger`,  it will build successfully.

**Comment by rizsotto** [comment]
@GreenAsFuck if you could provide some context on your environment, that could help to help you. The issue template has some questions, which are addressing the relevant aspects of the context.

https://github.com/rizsotto/Bear/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by GreenAsFuck** [comment]
Sorry to bother, but I found a way to make `soong` generate json file now, don't need `bear` anymore. I'm closing this.
FYI:
**Environment:**
 - OS name: linux
 - OS version: Ubuntu 18.04
 - OS architecture: x86_64
 - Bear version: 2.3.11
 - Bear install method: from package

build command `m` `mm` are just typical android build command.

**Comment by jbmaillet** [comment]
> Sorry to bother, but I found a way to make `soong` generate json file now, don't need `bear` anymore. I'm closing this.

Personally, I'd be interested if you could document that (maybe privately / by mail?)
Android build is... er... let's say "big and special" for our "also special" usecases.

**Comment by rizsotto** [comment]
I am also happy to host that recipe on Bear's wiki. (Similar to [Sarcasm's notebook](https://sarcasm.github.io/notes/dev/compilation-database.html))
