### ISSUE TITLE
Empty compile_commands.json on MacOS with avr-gcc

### ISSUE THREAD

**Issue by derek-mcblane** [rizsotto/Bear#505]
**Describe the bug**

**To Reproduce**
Tried all 4 combinations of setting CC environment variable and using --config with path to avr-gcc.
[bear.json](https://github.com/rizsotto/Bear/files/10543637/bear.json.txt)

bear -- make all
[build-output-1.txt](https://github.com/rizsotto/Bear/files/10543620/build-output-1.txt)

bear --config bear.json -- make all
[build-output-2.txt](https://github.com/rizsotto/Bear/files/10543622/build-output-2.txt)

CC=/opt/homebrew/bin/avr-gcc bear --force-wrapper -- make all
[build-output-3.txt](https://github.com/rizsotto/Bear/files/10543623/build-output-3.txt)

CC=/opt/homebrew/bin/avr-gcc bear --force-wrapper --config bear.json -- make all
[build-output-4.txt](https://github.com/rizsotto/Bear/files/10543624/build-output-4.txt)

**Expected behavior**
The usual behavior where I get a compile_commands.json output.

**Environment:**
 - OS name: Darwin
 - OS version: macOS Ventura 13.2
 - OS architecture: arm64
 - Bear version: 3.0.20
 - Bear install method: homebrew

**Additional context**
 - Can you give us a reference to the project that you are running against this tool?
 https://gitlab.com/jcarrete5/rb3-midi-adapter
 - What build tools this project is using?
 GNU Make (Using [DMBS](https://github.com/abcminiuser/dmbs) for LUFA)
 - What architecture you are trying to compile for?
 AVR8
 - Could you attach build logs?
 See above

**Before you send...**
 - Have you read the `README.md` file or `man bear`? Yes
 - Have you looked what other open issues Bear has? Yes
 - Are you sure that the build works without Bear? Yes

**Comment by rizsotto** [comment]
Thanks @derek-mcblane for the report. Could you re-run this command for me to have a better understanding of the project setup. (The `--force-wrapper` is not necessary on MacOS. And the `--verbose` will print relevant details how Bear plans to intercept the compiler calls.)

```
CC=/opt/homebrew/bin/avr-gcc bear --verbose -- make all
```

**Comment by derek-mcblane** [comment]
I think I actually did run with --verbose, but didn't put it in my report.

Regardless, here is the output from
`CC=/opt/homebrew/bin/avr-gcc bear --verbose -- make all`
[build-output.txt](https://github.com/rizsotto/Bear/files/10548867/build-output.txt)

**Comment by rizsotto** [comment]
Thanks @derek-mcblane to come back with this. The problem that Bear could not interpose the compiler wrapper in the build process. Could you try this:

There is a directory on your machine `/opt/homebrew/Cellar/bear/3.0.21/lib/bear/wrapper.d` which is full of soft links to `/opt/homebrew/Cellar/bear/3.0.21/lib/bear/wrapper`. Go to this directory and create another soft link to the same wrapper executable with the name of your compiler: `avr-gcc`. And just run the same command as before.

**Comment by derek-mcblane** [comment]
That worked! Thanks for your quick replies.
