### ISSUE TITLE
Patch provided for intercept to trucate output

### ISSUE THREAD

**Issue by asierllano** [rizsotto/Bear#511]
If the output of intercept is a file that already exists, the file was not trucated.
Then if the output length is smaller than previous output, the content is corrupt.

The provided patch truncates the output so the corruption is avoided.

[Bear-3.0.21-intercept-trunc.patch](https://github.com/rizsotto/Bear/files/10733229/Bear-3.0.21-intercept-trunc.patch)

**Comment by rizsotto** [comment]
Thanks @asierllano , this is merged now. Will be released as `3.1.1`.
