### ISSUE TITLE
Patch for intercept to support write returning short lengths

### ISSUE THREAD

**Issue by asierllano** [rizsotto/Bear#512]
EventDatabaseWriter calls write expecting to write the complete message or fail.
Write does not work that way, it may happen to write part of the message and return just the number of bytes written. It has been fixed in order to continue the write process as it was left.

This prevents generating random corrupted outputs in a system with many intercept processes and heavy loads.

[Bear-3.0.21-intercept-write.patch](https://github.com/rizsotto/Bear/files/10733247/Bear-3.0.21-intercept-write.patch)

**Comment by rizsotto** [comment]
Thanks @asierllano , this is merged now. Will be released as `3.1.1`.
