### ISSUE TITLE
Patch in order citnames make atomic write

### ISSUE THREAD

**Issue by asierllano** [rizsotto/Bear#513]
If the citnames process is stopped during the serialization, the output can be corrupted. Rename-overwrite operation makes the process atomic.

[Bear-3.0.21-citnames-atomic-write.patch](https://github.com/rizsotto/Bear/files/10733251/Bear-3.0.21-citnames-atomic-write.patch)

**Comment by rizsotto** [comment]
Thanks @asierllano , I moved this logic into the `citnames` application instead, but does the same as your solution was doing. Will be released as `3.1.1`.
