### ISSUE TITLE
Spurious error message when using Bear

### ISSUE THREAD

**Issue by rojer** [rizsotto/Bear#523]
**Describe the bug**

An error message is emitted on stderr that appears to be benign but is definitely annoying.
Example:
```
E0503 22:40:03.188611344    6316 server_chttp2.cc:40]        {"created":"@1683153603.188569087","description":"Only 1 addresses added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":406,"referenced_errors":[{"created":"@1683153603.188565173","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":403,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::1]:46813"}]}
```

**To Reproduce**

My use is pretty simple, in my Makefile i have:
```
CC = bear --output $(BUILD_DIR)/compile_commands.json --append -- clang-15
CXX = bear --output $(BUILD_DIR)/compile_commands.json --append -- clang++-15
```
It works - that is, `compile_commands.json` is created, but every compiler invocation is accompanied by an error message.

**Expected behavior**

No error messages emitted.

**Environment:**
 - OS name: `Linux`
 - OS version: `Ubuntu 22.04`
 - OS architecture: `x86_64`
 - Bear version: `3.0.18`
 - Bear install method: from package, `3.0.18-1`

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? `No, unfortunately`
 - What build tools this project is using? `make, no autotools`
 - What architecture you are trying to compile for? `x86_64, no x-compilation`
 - Could you attach build logs? `I'd rather not`

**Before you send...**
 - Have you read the `README.md` file or `man bear`? :heavy_check_mark: 
 - Have you looked what other open issues Bear has? :heavy_check_mark: 
 - Are you sure that the build works without Bear? :heavy_check_mark:

**Comment by rizsotto** [comment]
From a short google, this error message means that gRPC might try to bind to every address it got back by resolving localhost, and the IPv6 address binding failed.
