### ISSUE TITLE
Add linking database

### ISSUE THREAD

**Issue by mamaria-k** [rizsotto/Bear#528]
**Describe**
This issue was created to suggest improvements. Adding the ability to create a linking database.
You can contact me on Telegram mamaria_k.

Changes:
- linking database is created when calling *bear* or *citnames* with flag --with-link. 
- output jsons contains fields: arguments, directory, file, files, output (optional). "Arguments" contain full command. In compile database "files" contains all libs and dependencies. In link database "file" is empty, "files" contains all linking files and dependencies.
- in the linking database correct order of entries
- processing case of compilation and linking in one command
- processing case of ar and ranlib
- add filtering events (so that calls to subcommands do not create a partial duplication of already recorded commands)
- add unit tests and functional tests
- manually test on some big open-source projects
- update documentation

Now the filtering works considering that the events are sorted. However, I saw that with a small probability they are unsorted. Therefore, handling of the case of unsorted events will be added soon.

**Environment:**
 - OS name: ubuntu
 - OS version: 20.04
 - OS architecture: x86_64
 - Bear version: https://github.com/rizsotto/Bear/commit/3be8c91daad3e7df33f25996fa37abb8802f74b6
 - Bear install method: from source

**Comment by rizsotto** [comment]
#276 is the issue to track this.
