### ISSUE TITLE
Linking executable wrapper error

### ISSUE THREAD

**Issue by voki-cherniavskyi-p** [rizsotto/Bear#548]
**Describe the bug**
Linking executable wrapper error on make all stage.

**To Reproduce**
Clone repo, configure cmake, run make all.

**Expected behavior**
make all command successfully finished 

**Environment:**
 - OS name: Darwin (MacOS M1 Pro)
 - OS version: Ventura 13.5.2 
 - OS architecture: arm64
 - Bear version: latest repo copy on 24.09.2023
 - Bear install method: building from source

**Additional context**
Linking CXX executable wrapper
Undefined symbols for architecture arm64:
  "_CFRelease", referenced from:
      absl::lts_20220623::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetCString", referenced from:
      absl::lts_20220623::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetLength", referenced from:
      absl::lts_20220623::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetMaximumSizeForEncoding", referenced from:
      absl::lts_20220623::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneCopyDefault", referenced from:
      absl::lts_20220623::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneGetName", referenced from:
      absl::lts_20220623::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_res_9_getservers", referenced from:
      _ares_init_options in libcares.a(ares_init.c.o)
  "_res_9_ndestroy", referenced from:
      _ares_init_options in libcares.a(ares_init.c.o)
  "_res_9_ninit", referenced from:
      _ares_init_options in libcares.a(ares_init.c.o)
ld: symbol(s) not found for architecture arm64

**Comment by rizsotto** [comment]
Hey @voki-cherniavskyi-p , could you tell how did you install the dependencies? And what are the version of those? (The dependencies are listed [here](https://github.com/rizsotto/Bear/blob/master/INSTALL.md).)

**Comment by rizsotto** [comment]
Closing it, because lack of input.
