### ISSUE TITLE
bear not work

### ISSUE THREAD

**Issue by zxx1234** [rizsotto/Bear#552]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment:**
 - OS name: [e.g. linux] run `uname -s`
 - OS version: [e.g. CentOS 7.6] 
 - OS architecture: [e.g. `x86_64`] run `uname -m`
 - Bear version: [e.g. `3.15.0`]
 - Bear install method: [e.g. from package]

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? [e.g. No if it's a close source project, but in case of an open source project a link to the sources could be nice.]
 - What build tools this project is using? [e.g. GNU make wtih `configure` script]
 - What architecture you are trying to compile for? [e.g. cross compiling]
 - Could you attach build logs? If you can re-run the command which failed (e.g. `bear -- make`) with extra verbose log switches (e.g. `bear --verbose -- make`) and send the output of it, that would help a lot.

**Before you send...**
 - Have you read the `README.md` file or `man bear`?
 - Have you looked what other open issues Bear has?
 - Are you sure that the build works without Bear?

**Comment by zxx1234** [comment]
1.get bear source and compile.
cmake ../Bear-2.4.3/ -DCMAKE_C_COMPILER_ARG1="-m32"; VERBOSE=1 make all;
cmake ../Bear-2.4.3/ -DCMAKE_C_COMPILER_ARG1="-m64"; VERBOSE=1 make all;

2.compile ok and check the libear.so. (dir 64-- 64bit , dir 32--32bit)
xxxx@ubuntu:~/workspace/tools/64/libear$ file libear.so 
libear.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=60bcee5e81fab27ba1e7c08abad2cf8550a54d4f, not stripped

xxxx@ubuntu:~/workspace/tools/32/libear$ file libear.so 
libear.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=e8db844222fb7ac596c657af5fec11f1f44696dc, not stripped

3.use bear to make,but fail
xxxx@ubuntu:~/workspace$ bear --libear /home/workspace/tools/32/libear/libear.so make
ERROR: ld.so: object '/home/workspace/tools/32/libear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

xxxx@ubuntu:~/workspace$ bear --libear /home/workspace/tools/64/libear/libear.so make
ERROR: ld.so: object '/home/workspace/tools/64/libear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

how to fix it .thanks.

**Comment by rizsotto** [comment]
Hey @zxx1234 ,

The [multilib issue](https://github.com/rizsotto/Bear/wiki/Usage#multilib-issues) is documented on the wiki. You probably want to have a look at it. And I would also recommend to read `man ld.so` page, "Dynamic string token" section.

But since the multilib is not tested in CI, it might be broken. Sorry for that!
