### ISSUE TITLE
Compile option "--include <path>" generates incorrect database entry

### ISSUE THREAD

**Issue by HclX** [rizsotto/Bear#562]
**Describe the bug**
Both clang and gcc support "--include <path>" to include a header file when compiling a C files. It seems the right format should be either "--include=<path>" or "--include<path>" according to man page, but separated by space also works in practice. However, when separated by space, bear doesn't generate correct result database.

**To Reproduce**

Here are the test files:
```
~/Source/test$ cat foo.c
#ifdef BAR_AVAILABLE
int bar(int x) { return x + 5; }
#endif

int foo(int x) {
    return bar(x) * 5;
}
:~/Source/test$ cat bar.h
#define BAR_AVAILABLE
```
Running command `bear -- clang --includebar.h -c foo.c -o foo.o` or `bear -- clang --include=bar.h -c foo.c -o foo.o` will generate expected database.
```
[
  {
    "arguments": [
      "/usr/bin/clang",
      "--include=bar.h",
      "-c",
      "-o",
      "foo.o",
      "foo.c"
    ],
    "directory": "/usr/home/test/Source/test",
    "file": "/usr/home/test/Source/test/foo.c",
    "output": "/usr/home/test/Source/test/foo.o"
  }
]

```

However, `bear -- clang --include bar.h -c foo.c -o foo.o` will not:
```
[
  {
    "arguments": [
      "/usr/bin/gcc",
      "--include",
      "-c",
      "-o",
      "foo.o",
      "bar.h"
    ],
    "directory": "/usr/home/test/Source/test",
    "file": "/usr/home/test/Source/test/bar.h",
    "output": "/usr/home/test/Source/test/foo.o"
  },
  {
    "arguments": [
      "/usr/bin/gcc",
      "--include",
      "-c",
      "-o",
      "foo.o",
      "foo.c"
    ],
    "directory": "/usr/home/test/Source/test",
    "file": "/usr/home/test/Source/test/foo.c",
    "output": "/usr/home/test/Source/test/foo.o"
  }
]
```

All three commands build fine when not using bear.

**Expected behavior**
I'd expect bear generates same, correct json file when using "--include <path>" just like the other two ways.

**Environment:**
 - OS name: Linux
 - OS version: Debian
 - OS architecture: x86_64
 - Bear version: 3.1.3
 - Bear install method: apt install

**Additional context**

I'm using both clang and gcc and the behavior is same. Here are the clang/gcc versions I'm using:

~/Source/test$ clang --version
Debian clang version 16.0.6 (19)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

~/Source/test$ gcc --version
gcc (Debian 13.2.0-10) 13.2.0

**Comment by rizsotto** [comment]
Thanks @HclX for this report. Looks like the compiler flag parsing logic needs to be fixed.
