### ISSUE TITLE
makeopts ignored

### ISSUE THREAD

**Issue by toralf** [rizsotto/Bear#564]
The make system should respect e.g. "-j 4" instead using all available cpus.
origin: https://bugs.gentoo.org/922199

**Comment by rizsotto** [comment]
Hey @toralf , thanks for the report... not sure I can do anything about that. The project is using CMake. The Makefiles are generated, and to my best knowledge there is nothing special goes into that.

Have you try to see if other packages with CMake has the same problem? Or is the MAKE_OPTS is actually used during the package creation?

**Comment by toralf** [comment]
Hi, the _MAKE_OPTS_ is a Gentoo internal variable, which usually is expanded to e.g. "-j4" or something like that.
Worked fine for thousands of packages but well, maybe it is really Gentoo specific.

**Comment by rizsotto** [comment]
Thanks for your quick response!

Let me close this ticket then. I have a feeling that the packaging has some problems, because if pass the `-jX` flag to the `make` command, it has effect on the parallelism. (I mean `-j2` is doing less parallel than `-j4`.)
