### ISSUE TITLE
can't install bear without sudo

### ISSUE THREAD

**Issue by LacueyDavid** [rizsotto/Bear#565]
Hello! I'm currently in an environment without sudo privilege, and I wonder if there is a way to install bear without sudo privilege?

thanks for reading.

**Comment by rizsotto** [comment]
Hey @LacueyDavid , sure you can do that.

```
export VERBOSE=1
mkdir -p $build_dir
cmake -B $build_dir -S $source_dir -DCMAKE_INSTALL_PREFIX:PATH="$install_dir" -DCMAKE_INSTALL_LIBDIR=lib64
cmake --build $build_dir --target clean;
cmake --build $build_dir --parallel 18;
mkdir -p $install_dir;
cmake --build $build_dir --target install;
```

you will need to define `source_dir` (where Bear sources are), `build_dir` and `install_dir`. For the `CMAKE_INSTALL_LIBDIR` value, read the `INSTALL.md` file.

**Comment by LacueyDavid** [comment]
Work perfectly, thank you!
