### ISSUE TITLE
Question - how to capture built in compiler options

### ISSUE THREAD

**Issue by wonk-andy** [rizsotto/Bear#579]
I am trying to use Bear 3.1.4 to generate the compile_commands.json file from a Makefile based project which cross compiles for QNX on a Linux host.  The compile command line for one of the source files is:

`aarch64-unknown-nto-qnx7.0.0-gcc -std=gnu99 -MMD -MP -Iinclude -o build/1.01.00/src/iMX8.o -c src/iMX8.c`

The output for this file that is captured says:

```
  {
    "arguments": [
      "/opt/tools/qnx700/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-gcc",
      "-std=gnu99",
      "-Iinclude",
      "-c",
      "-o",
      "build/1.01.00/src/iMX8.o",
      "src/iMX8.c"
    ],
    "directory": "/opt/samba/customers/xxxx/GetMacAddr",
    "file": "/opt/samba/customers/xxxx/GetMacAddr/src/iMX8.c",
    "output": "/opt/samba/customers/xxxx/GetMacAddr/build/1.01.00/src/iMX8.o"
  }
```

There are other built-in compiler options that it isn't capturing, for example the compiler defines `__QNX__` which is used for conditional compilation within the source files.  How do I capture this, and any other, built in variable?

-Andy.

**Comment by rizsotto** [comment]
Hey Andy, 

The compilation database is capturing the compiler calls only. Compiler internals are not presented in the output.

Compiler specific variables are not easy to mimic with other compilers. OS specific defines can be placed into a common header, but might interfere with the host header files.

**Comment by rizsotto** [comment]
Hi @wonk-andy -- two parts to this.

First, on recognition: your `...-qnx7.0.0-gcc` cross-compiler was already recognized (it is a gcc). The upcoming Bear 4.1.6 additionally recognizes QNX's own `qcc` and `q++` drivers automatically, in case any of your build steps use those.

On the built-in defines (`__QNX__` and friends): Bear deliberately records each compilation exactly as your build invoked it and does not expand the compiler's built-in macros or default include paths into the arguments -- those are properties of the compiler, not of the command line. The right place to resolve them is the language server: clangd's `--query-driver` pointed at your QNX compiler will query it for its built-in defines and system headers. That keeps `compile_commands.json` a faithful record of the build while still giving your editor the full picture.
