### ISSUE TITLE
Couldn't applying Bear to Android build system

### ISSUE THREAD

**Issue by minhyuk** [rizsotto/Bear#58]
Hello,
I am not sure about this is right place for question. If I am rude, sorry about that.

I want to use Bear to generating compilation db from build of Google's Android Platform.
But, Bear seems not working with Android Platform's build system.

What am I missing?

**Comment by minhyuk** [comment]
Finally, I could captured android build commands with bear. It's long journey.

Above strange things happened when build system use both x64 and x86 compiler for cross compile.
In Ubuntu 12.04 LTS x64 version, Each shared library(x86, x64) placed in different location(/lib, /lib/x86_64-linux-gnu) for each architecture.

Some Unix OS provided LD_PRELOAD_32, LD_PRELOAD_64, but ubuntu did not provide.
So, when applying bear to android, must considered this situation.

**Comment by rizsotto** [comment]
Thanks @minhyuk !
It's good to hear that you managed to work Bear for Android. Is there any change you've made on the Bear source in order to make it work? If yes, would be glad to see your findings.
