### ISSUE TITLE
How to support emcc compiler?

### ISSUE THREAD

**Issue by Virus-V** [rizsotto/Bear#580]
I have a C project that uses the emscripten SDK to compile wasm. 

During the build, emcc is used to compile the c files, but bear generates an empty compile_commands.json.

I tried to manually create a soft link from emcc to ../wrapper in the wrapper.d directory, like other tools, and used the `bear --force-wrapper -- make` command to force wrapper mode, but bear still doesn't work.

How can I do this? Thank you!

**Comment by rizsotto** [comment]
Hi @Virus-V -- coming back to this with good news. The upcoming Bear 4.1.6 recognizes `emcc` and `em++` (including the `emcc.py` / `em++.py` forms) out of the box, so no wrapper trick or config hint is needed anymore. `bear -- emmake make` should now produce a populated `compile_commands.json`.

If you can, it would help a lot to test the release candidate before it ships. Check out the `4.1.6-rc` branch and install from source following [INSTALL.md](https://github.com/rizsotto/Bear/blob/4.1.6-rc/INSTALL.md), then run your usual build under it and let me know whether `compile_commands.json` now looks right.

The emcc invocation is recorded exactly as your build calls it; if clangd needs Emscripten's baked-in include paths, point its `--query-driver` at the `emcc` binary.
