### ISSUE TITLE
Bear doesn't seem to detect MinGW calls on macOS

### ISSUE THREAD

**Issue by giomasce** [rizsotto/Bear#593]
**Describe the bug**
When cross-compiling a program with MinGW on macOS Bear doesn't seem to be able to intercept the MinGW compiler calls, leading to an empty `compile_commands.json` file.

**To Reproduce**
I am trying to use bear to build a compilation database for [vkd3d](https://gitlab.winehq.org/wine/vkd3d/), but I can show how to reproduce with a minimal example:
```
% cat test.c 
int main() { return 0; }
% cat compile.sh 
#!/bin/sh

x86_64-w64-mingw32-gcc -o test.exe test.c
% bear -- ./compile.sh          
% cat compile_commands.json 
[]
```

**Expected behavior**
The compilation commands database should contain an entry for file `test.c`.

The expected behavior happens on Linux and happens on macOS too if I use plain `gcc` instead of the MinGW cross compiler.

My understanding is that on macOS Bear is forced to use the wrapper intercept method, which is only able to intercept a specific list of programs, and that list doesn't include the MinGW cross compiler. Adding the compiler to the `compilers_to_recognize` list doesn't seem to help, probably because that configuration is only meaningful for the citnames phase. I would propose to implement the possibility to add other wrappers at runtime, so that this limitation of the wrapper intercept method can be worked around. I guess this means that the `wrapper.d` directory is generated at runtime.

**Environment:**
 - OS name: Darwin
 - OS version: macOS Sonoma 14.5
 - OS architecture: arm64
 - Bear version: 3.1.4
 - Bear install method: from homebrew

**Additional context**
 - Can you give us a reference to the project that you are running against this tool? As mentioned above, I am trying to build a compilation database for vkd3d, but since I submitted a self-contained example I don't think that adding details about that is going to be useful. If it is, though, I'll add the details.

**Before you send...**
 - Have you read the `README.md` file or `man bear`? Yes.
 - Have you looked what other open issues Bear has? Yes, but none seemed identical.
 - Are you sure that the build works without Bear? The build works both with and without Bear, but when using Bear the compilation database is empty.

**Comment by giomasce** [comment]
For the record, with this patch it seems that Bear works for my use case:
```diff
diff --git a/source/intercept/CMakeLists.txt b/source/intercept/CMakeLists.txt
index 368ca73..c5f3dc9 100644
--- a/source/intercept/CMakeLists.txt
+++ b/source/intercept/CMakeLists.txt
@@ -131,6 +131,10 @@ install(CODE "
         COMMAND ln -sf ../wrapper objdump
         COMMAND ln -sf ../wrapper ranlib
         COMMAND ln -sf ../wrapper readelf
+        COMMAND ln -sf ../wrapper x86_64-w64-mingw32-gcc
+        COMMAND ln -sf ../wrapper x86_64-w64-mingw32-g++
+        COMMAND ln -sf ../wrapper i686-w64-mingw32-gcc
+        COMMAND ln -sf ../wrapper i686-w64-mingw32-g++
         WORKING_DIRECTORY ${DESTDIR}${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/bear/wrapper.d
     )
 ")
```

**Comment by rizsotto** [comment]
Yes, creating those soft links will solve your problem.

Will not take the offered patch, because there are way too many compilers out there to support.
