### ISSUE TITLE
LSP: Unsupported option '-m68000' for target x86_64-pc-linux-gnu

### ISSUE THREAD

**Issue by rubin55** [rizsotto/Bear#594]
**Describe the bug**
After creating a `compile_commands.json` using `bear -- make`, `clangd` is upset and tells me that certain compiler options are unsupported for the target of the host platform; this is correct, however, `bear` or `clangd` seem to not be aware of the fact that the `make` command invokes a cross-compiler.

**To Reproduce**
```sh
git clone https://github.com/rubin55/genesis.git
cd genesis/background
# use editor that does lsp with clangd
vim src/main.c
# observe error from LSP:
# LSP: Unsupported option '-m68000' for target 'x86_64-pc-linux-gnu'
```

**Expected behavior**
A `compile_commands.json` that makes `clangd` work with my cross compiler.

**Environment:**
 - OS name: `Linux 6.10.4`
 - OS version: `Arch Linux`
 - OS architecture: `x86_64`
 - Bear version: `3.1.4`
 - Bear install method: `pacman -S bear`

**Additional context**
 - Project: https://github.com/rubin55/genesis
 - Tools: `make`, `marsdev`
 - Cross Compiler: `yes`, `m68k-elf-gcc`

**Before you send...**
 - Have you read the README.md: `yes`
 - Have you looked at other open issues: `yes`
 - Are you sure that the build works without Bear: `yes`

**Comment by rubin55** [comment]
In the FAQ, with regards to cross compilers, you mention `citnames`; I've read that manpage, but I'm not sure what that could do to help me in this case (if this is super straight forward, my apologies, example much appreciated).

**Comment by rubin55** [comment]
Update: I figured out this is due to `query-driver` missing from `clangd` flags. This setting is essentially a whitelist of compiler binaries that `clangd` is allowed to execute. When it can execute the (cross) compiler, it can obtain default include settings, and relevant in this case, the correct target triple.

You can add `--query-driver` options to `clangd` through your editor/lsp settings, but, since it's just a whitelist of binaries that `clangd` is allowed to execute, you can also opt to set it globally/system-wide. In my case, on Arch Linux, that means a script in `/etc/profile.d/marsdev.sh` (I'm doing this specifically for the marsdev toolchain, it will be similar for things like cuda or other compilers):

```sh
#!/bin/bash

if [[ -x /opt/marsdev/m68k-elf/bin/m68k-elf-gcc && -z "$CLANGD_FLAGS" ]]; then
    # See: https://clangd.llvm.org/guides/system-headers#query-driver
    export CLANGD_FLAGS='--query-driver="/opt/marsdev/*-elf/bin/*"'
fi
```

After reboot, check your `env` and you should see the `CLANGD_FLAGS` environment variable. Then start your editor/lsp environment, and `clangd` should operate normally.

**Comment by rizsotto** [comment]
As a workaround I would suggest to create [a config file](https://github.com/rizsotto/Bear/blob/master/source/citnames/man/bear-citnames.1.md#config-file), and in the `compilers_to_recognize` section, add the `-m68000` flag to be removed.
