### ISSUE TITLE
Bear truncates output.json on resuming compilation

### ISSUE THREAD

**Issue by p0rnfl4k3s** [rizsotto/Bear#63]
Hi Bear-team, firstoff: great software, thanks a lot for your efforts! One minor issue anyway: I would really love being able to interrupt and resume compilation, especially on big projects this could be a major improvement. I had the problem just yesterday that the compilation crashed at some point, after fixing the problem and resuming the compilation, Bear truncated the compile_commands.json-file.
If I find the time, I may do the patch myself, for now I first wanted to leave this "feature-request" here, thanks again for your awesome piece of work!

**Comment by rizsotto** [comment]
this is fixed in version 2.0
