### ISSUE TITLE
bear generate redundant database when using wllvm

### ISSUE THREAD

**Issue by HongxuChen** [rizsotto/Bear#66]
This is a rare use-case: when using [wllvm](https://github.com/travitch/whole-program-llvm) Bear always generates more compilation database entries than expected. 

As the [README.md](https://github.com/travitch/whole-program-llvm/blob/master/README.md) mentioned, that project does 2 things when `CC=wllvm` and `CXX=wllvm++` during compilation:

- invoke regular compiler to build a real object
- Do bitcode compilation with the corresponding compiler commands specified.

In this sense, I was hoping 

```makefile
min.out: main.o min.o
        $(CC) main.o min.o -o $@
main.o:
        $(CC) main.c -c -o $@ 
min.o:
        $(CC) min.c -c -o $@
```

Will generate compile commands like:
```shell
clang main.c -c -o main.o
clang min.c -c -o min.o
clang -emit-llvm main.c -c -o .main.o.bc
clang -emit-llvm main.c -c -o .min.o.bc
```

But the inside compiler_commands.json there are 9 entries for the same compilation commands for each build target. Also I notice that wllvm seems correct here since when set `WLLVM_OUTPUT=debug` it only prints each compilation once. So this may be an issue for Bear.  
But as my case is not the regular compilation practice, I guess this should be of low priority.

**Comment by rizsotto** [comment]
there is a new version of the tool, which filters the compiler wrappers now. please give it a try and reopen this issue if that's still a case.

**Comment by HongxuChen** [comment]
Works like a charm, many thanks!
