### ISSUE TITLE
Incorrect escaping 

### ISSUE THREAD

**Issue by stepthom** [rizsotto/Bear#70]
I'm using Bear to create a compilation database for PostgreSQL. One of the commands executed by the the PostgreSQL build system is:

```
/usr/local/bin/clang -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-    strict-aliasing -fwrapv -g -I../../../../src/include -D_GNU_SOURCE  -DDLSUFFIX=\".so\"  -c -o dfmgr.o dfmgr.c
```

Notice the `-DDLSUFFIX=\".so\"` flag.

The compilation database entry created by bear is:

```
{
    "command": "/usr/local/bin/clang -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -../../../../src/include -D_GNU_SOURCE -DDLSUFFIX=\".so\" -c -o dfmgr.o dfmgr.c",
    "directory": "/dataware/postgres/src/backend/utils/fmgr",
    "file": "/dataware/postgres/src/backend/utils/fmgr/dfmgr.c"
}
```

Notice the `-DDLSUFFIX=\".so\"` flag. This is incorrect, because CMake is interpreting this flag after escaping, i.e., as `-DDLSUFFIX=".so"`, which is causing that file to compile incorrectly. (I can't tell if the `\`character is being dropped altogether but the `"` character is being escaped correctly, or if no escaping is happening at all.) Instead, the compilation database entry created by bear should have `-DDLSUFFIX=\\\".so\\\"`, which will then be interpreted by CMake as  `-DDLSUFFIX=\".so\"`, as desired.

**Comment by rizsotto** [comment]
Thanks Stephen for the report! I checked the branch `master` has this bug, but on the branch `devel` this is fixed. Could you confirm it?

**Comment by stepthom** [comment]
@rizsotto That worked perfectly! The DLSUFFIX flag is now correctly escaped as  `DDLSUFFIX=\\\".so\\\"` Thanks for the help.
