### ISSUE TITLE
Error while building Mono

### ISSUE THREAD

**Issue by tritao** [rizsotto/Bear#71]
First of all thanks for your work on this tool.

I am seeing a problem when using Bear to build the Mono runtime.

```
cd /Users/joao/Dev/mono/mcs && /Library/Developer/CommandLineTools/usr/bin/make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='net_4_0 net_4_5 xbuild_12 xbuild_14   ' CC='gcc' all-profiles
dyld: could not load inserted library '/usr/local/lib/libear.dylib' because no suitable image found.  Did find:
    /usr/local/lib/libear.dylib: mach-o, but wrong architecture

make[6]: *** [build/deps/basic-profile-check.exe] Trace/BPT trap: 5
*** The compiler 'mcs' doesn't appear to be usable.
*** You need Mono version 3.2 or better installed to build MCS
*** Check mono README for information on how to bootstrap a Mono installation.
dyld: could not load inserted library '/usr/local/lib/libear.dylib' because no suitable image found.  Did find:
    /usr/local/lib/libear.dylib: mach-o, but wrong architecture
```

You can reproduce by cloning Mono and then doing something like:

```
./autogen.sh --prefix=`pwd`/build
bear -- make
```

**Comment by rizsotto** [comment]
hi João, i am new in the Mac world, but for me it looks like a problem of different architectures. similar error messages pops up on the net when people try to run a i386 code against X86_64 code. (might be a case if the libear.dylib is a X86_64 only, and one of the build tool is a i386 executable.) could you dig some more to validate this theory?

**Comment by alexanderkyte** [comment]
@tritao You want to use 

```
cmake "-DCMAKE_OSX_ARCHITECTURES=x86_64;i386" /path/to/build/dir
```

to make a binary that can use both 32 and 64 bit osx libraries.

**Comment by rizsotto** [comment]
@alexanderkyte Thanks for this! Have you had the same issue and was this line solved for you?
@tritao Can you confirm what @alexanderkyte wrote is solve the issue you have?

**Comment by tritao** [comment]
I'll give this a try and report.

**Comment by alexanderkyte** [comment]
@rizsotto I had the same issue, and setting both architectures fixed it for me. It's a frequent mistake with cmake on osx to only build for one architecture, since many things link to libs from both architectures.

**Comment by rizsotto** [comment]
Closing this, because nobody reported anything related to this since. Thanks @alexanderkyte !

**Comment by ManSoSec** [comment]
I have the same problem when use "bear make" for Qemu. I tried different target archs, but I still get the error. Please find the error here:

dyld: could not load inserted library '/usr/local/lib/bear/libear.dylib' because no suitable image found.  Did find:
	/usr/local/lib/bear/libear.dylib: mach-o, but wrong architecture
	/usr/local/lib/bear/libear.dylib: stat() failed with errno=1

/bin/sh: line 1: 71301 Abort trap: 6           Rez -append /.../qemu/pc-bios/qemu.rsrc -o qemu-system-x86_64
make[1]: *** [qemu-system-x86_64] Error 134
make[1]: *** Deleting file `qemu-system-x86_64'
make: *** [subdir-x86_64-softmmu] Error 2


[NOTE] I can use "bear make" for compiling other projects without any problem.

Thanks!

**Comment by rizsotto** [comment]
The reports does not give me enough information to fix it. Closing now. Would re-open it if somebody who has this issue can help to pair with me to debug. :)
