### ISSUE TITLE
All tests failed - anyof({'-c'}, take_action(Action.Compile)) syntax error

### ISSUE THREAD

**Issue by kwkelly** [rizsotto/Bear#73]
Everything appears to build fine, but all the tests fail.

Using Scientific Linux 6 (based on RHEL), Linux kernel 2.6.32-504.el6.x86_64

~/Bear $ cmake --version
cmake version 2.8.12.2

~/Bear $ mkdir build
~/Bear $ cd build/
~/Bear/build $ cmake -DCMAKE_INSTALL_PREFIX:PATH=/workspace/local/ ..
-- The C compiler identification is GNU 4.8.0
-- Check for working C compiler: /opt/apps/ossw/applications/gcc/gcc-4.8/sl6/bin/gcc
-- Check for working C compiler: /opt/apps/ossw/applications/gcc/gcc-4.8/sl6/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test C99_SUPPORTED
-- Performing Test C99_SUPPORTED - Success
-- Looking for execve
-- Looking for execve - found
-- Looking for execv
-- Looking for execv - found
-- Looking for execvpe
-- Looking for execvpe - found
-- Looking for execvp
-- Looking for execvp - found
-- Looking for execvP
-- Looking for execvP - not found
-- Looking for execl
-- Looking for execl - found
-- Looking for execlp
-- Looking for execlp - found
-- Looking for execle
-- Looking for execle - found
-- Looking for posix_spawn
-- Looking for posix_spawn - found
-- Looking for posix_spawnp
-- Looking for posix_spawnp - found
-- Looking for _NSGetEnviron
-- Looking for _NSGetEnviron - not found
-- Looking for scons
-- Looking for scons -- found
-- Looking for qmake
-- Looking for qmake -- found
-- Found PythonInterp: /usr/bin/python (found version "2.6.6")
-- Configuring done
-- Generating done
-- Build files have been written to: /h1/keith/Bear/build

~/Bear/build $ make all
Scanning dependencies of target ear
[100%] Building C object libear/CMakeFiles/ear.dir/ear.c.o
Linking C shared library libear.so
[100%] Built target ear

~/Bear/build $ make install
[100%] Built target ear
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /workspace/local/share/doc/bear/COPYING
-- Up-to-date: /workspace/local/share/doc/bear/README.md
-- Up-to-date: /workspace/local/share/doc/bear/ChangeLog.md
-- Installing: /workspace/local/lib64/libear.so
-- Installing: /workspace/local/bin/bear
-- Installing: /workspace/local/share/man/man1/bear.1

~/Bear/build $ make check
[ 50%] Built target ear
Scanning dependencies of target exec_anatomy
[100%] Building C object test/exec_anatomy/CMakeFiles/exec_anatomy.dir/main.c.o
Linking C executable exec_anatomy
[100%] Built target exec_anatomy
Scanning dependencies of target check
UpdateCTestConfiguration  from :/h1/keith/Bear/build/test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/h1/keith/Bear/build/test/DartConfiguration.tcl
Test project /h1/keith/Bear/build/test
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: run_shell_test

1: Test command: /usr/bin/make "run_shell_test"
1: Test timeout computed to be: 9.99988e+06
1: [ 50%] Built target ear
1: Scanning dependencies of target run_shell_test
1: [100%] Running module tests with shell
1:   File "/h1/keith/Bear/build/test/end-to-end/../../bear/bear", line 351
1:     anyof({'-c'}, take_action(Action.Compile)),
1:                ^
1: SyntaxError: invalid syntax
1: make[7]: *** [test/end-to-end/CMakeFiles/run_shell_test] Error 1
1: make[6]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/all] Error 2
1: make[5]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
1: make[4]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
1/5 Test #1: run_shell_test ...................***Failed    0.21 sec
test 2
    Start 2: run_scons_test

2: Test command: /usr/bin/make "run_scons_test"
2: Test timeout computed to be: 9.99988e+06
2: [ 50%] Built target ear
2: Scanning dependencies of target run_scons_test
2: [100%] Running module tests with scons
2:   File "/h1/keith/Bear/build/test/end-to-end/../../bear/bear", line 351
2:     anyof({'-c'}, take_action(Action.Compile)),
2:                ^
2: SyntaxError: invalid syntax
2: make[7]: *** [test/end-to-end/CMakeFiles/run_scons_test] Error 1
2: make[6]: *** [test/end-to-end/CMakeFiles/run_scons_test.dir/all] Error 2
2: make[5]: *** [test/end-to-end/CMakeFiles/run_scons_test.dir/rule] Error 2
2: make[4]: *** [test/end-to-end/CMakeFiles/run_scons_test.dir/rule] Error 2
2/5 Test #2: run_scons_test ...................***Failed    0.19 sec
test 3
    Start 3: run_qmake_test

3: Test command: /usr/bin/make "run_qmake_test"
3: Test timeout computed to be: 9.99988e+06
3: [ 50%] Built target ear
3: Scanning dependencies of target run_qmake_test
3: [100%] Running module tests with qmake
3:   File "/h1/keith/Bear/build/test/end-to-end/../../bear/bear", line 351
3:     anyof({'-c'}, take_action(Action.Compile)),
3:                ^
3: SyntaxError: invalid syntax
3: make[7]: *** [test/end-to-end/CMakeFiles/run_qmake_test] Error 1
3: make[6]: *** [test/end-to-end/CMakeFiles/run_qmake_test.dir/all] Error 2
3: make[5]: *** [test/end-to-end/CMakeFiles/run_qmake_test.dir/rule] Error 2
3: make[4]: *** [test/end-to-end/CMakeFiles/run_qmake_test.dir/rule] Error 2
3/5 Test #3: run_qmake_test ...................***Failed    0.91 sec
test 4
    Start 4: run_exec_anatomy

4: Test command: /h1/keith/Bear/build/test/exec_anatomy/run.sh
4: Test timeout computed to be: 9.99988e+06
4:   File "/h1/keith/Bear/build/test/exec_anatomy/../../bear/bear", line 351
4:     anyof({'-c'}, take_action(Action.Compile)),
4:                ^
4: SyntaxError: invalid syntax
4/5 Test #4: run_exec_anatomy .................***Failed    0.04 sec
test 5
    Start 5: result_code_check

5: Test command: /h1/keith/Bear/build/test/result_code/run.sh
5: Test timeout computed to be: 9.99988e+06
5:   File "/h1/keith/Bear/build/test/result_code/../../bear/bear", line 351
5:     anyof({'-c'}, take_action(Action.Compile)),
5:                ^
5: SyntaxError: invalid syntax
5:   File "/h1/keith/Bear/build/test/result_code/../../bear/bear", line 351
5:     anyof({'-c'}, take_action(Action.Compile)),
5:                ^
5: SyntaxError: invalid syntax
5/5 Test #5: result_code_check ................***Failed    0.04 sec

0% tests passed, 5 tests failed out of 5

Total Test time (real) =   1.41 sec

The following tests FAILED:
	  1 - run_shell_test (Failed)
	  2 - run_scons_test (Failed)
	  3 - run_qmake_test (Failed)
	  4 - run_exec_anatomy (Failed)
	  5 - result_code_check (Failed)
Errors while running CTest
make[3]: *** [test/CMakeFiles/check] Error 8
make[2]: *** [test/CMakeFiles/check.dir/all] Error 2
make[1]: *** [test/CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2

**Comment by rizsotto** [comment]
hi Keith, thanks for the report. Could you confirm that the python version is equal or greater than 2.7?

**Comment by kwkelly** [comment]
It wasn't. Loading python 2.7+ and rebuilding then running make check again has resolved the issue.  Can cmake not check for an appropriate version of python? Thanks.

**Comment by rizsotto** [comment]
Good news! :) Will do version check at cmake step. Thanks again for the report!
