### ISSUE TITLE
Empty output JSON

### ISSUE THREAD

**Issue by QuaziRandom** [rizsotto/Bear#80]
I've been facing problems with one of the latest versions of Bear. I'm trying to form a compilation database for a sample project (described below), and I'm unable to successfully populate the compile commands except in `--disable-filter` mode.

Here's the Makefile of the sample project:
```
all: test
test: test.cpp
        c++ -o test test.cpp
```
With `bear make`, the generated _compile_commands.json_ is only `[]`.
With `bear --disable-filter make`, however, all execs are captured, like so:
```
[
    {
        "command": [
            "c++", 
            "-o", 
            "test", 
            "test.cpp"
        ], 
        "directory": "/home/aravind/scratch/macroTest", 
        "function": "execvp", 
        "pid": "15944", 
        "ppid": "15943"
    }, 
    {
        "command": [
            "/usr/lib64/gcc/x86_64-suse-linux/4.8/cc1plus", 
            "-quiet", 
            "-D_GNU_SOURCE", 
     ----------- And so on; truncated due to too many details --------------
     }
]
```

Interestingly, using an old version of Bear, I'm able to get the right compilation database. I checked out commit `29546e6060cb...` and built it. With this version, executing a `bear -- make`, I get the output:
```
[
{
  "directory": "/home/aravind/scratch/macroTest",
  "command": "c++ -o test test.cpp",
  "file": "/home/aravind/scratch/macroTest/test.cpp"
}
]
```
Also, cmake with the latest commit (`3e0e1ad5...`), fails to find the dependency `execvP` (but `execvp` is found), and it builds just fine. Could there be a problem with any _configuration_?

**Comment by rizsotto** [comment]
thanks for the report. the configuration does not seem to be the problem. (`execvP` is not on linux, that's on FreeBSD.) i'm travelling at the moment, can't working on it now.

**Comment by rizsotto** [comment]
made a new release where i did fix this issue. please reopen if it still failing for you. (although made a test which passing on travis-ci.)

**Comment by QuaziRandom** [comment]
The latest commit works perfectly. Thanks!
