### ISSUE TITLE
Bad escape of strings in compilation database.

### ISSUE THREAD

**Issue by jumapico** [rizsotto/Bear#81]
With the following command in make:
    $(CXX) -DEXPORT="extern \"C\"" -o hello hello.cxx
Bear create the following command that fail when using with clang lib tooling:
    "command": "g++ \"-DEXPORT=extern \"C\"\" -o hello hello.cxx",
CMake generates the following command:
    "command": "/usr/bin/clang++-3.6   -DEXPORT=\"extern \\\"C\\\"\"   -o CMakeFiles/hello.dir/hello.cxx.o -c /home/jmpc/jumapico/bug-bear/hello.cxx",

The full example is in this gist: https://gist.github.com/jumapico/64e1fb1e0493960701bc
Here is a proposed patch: https://gist.githubusercontent.com/jumapico/64e1fb1e0493960701bc/raw/60ed6bb9fd20319ef4d9d82a023c75a24fa2032e/0001-Fix-json-escape-string.patch

Greetings,
Juan Picca

**Comment by rizsotto** [comment]
thanks for your report. which version of Bear are you using? the latest version does not suffer from this problem (and it is written in Python). please check it out and if the problem still exists let me know that.

**Comment by rizsotto** [comment]
sorry i was wrong, the new version is even worst. it generates the following entry
```json
"command": "cc -c -DEXPORT=extern \"C\" -o hello hello.cxx"
```
will look at it when i'm back from my vacation.

**Comment by jumapico** [comment]
Thanks for your fast response László. The patch is for the 1.4.3 tag, sorry for omiting the tag in the previous post.
The version in master give me an empty compile_commands.json file.
Greetings,
Juan Picca

**Comment by rizsotto** [comment]
made a new release (2.0.3) which address the escaping issue. (the empty file also shall be fixed.) your test case is added to the source. please reopen this ticket if the escaping is still failing for you.
