### ISSUE TITLE
Latest bear creates 0 byte compile_commands.json

### ISSUE THREAD

**Issue by RobertBuhren** [rizsotto/Bear#82]
I'm trying to use the latest bear (3e0e1ad535078032316d860846ebcf1a314c3d61) to generate a comile_commands.json for the linux kernel but the the created compile_commands.json is always empty. I tried the same with ver 1.4.3 and it worked fine.

Regards,

Robert

**Comment by rizsotto** [comment]
thanks for the report Robert. i also noticed some issues like this, trying to fix it (when i finished my travelling).

**Comment by rizsotto** [comment]
made a new release (2.0.3) which tries to fix this issue. could you run this version against the linux kernel and tell me is it still an issue? (still travelling, can't run it by myself.) thanks

**Comment by RobertBuhren** [comment]
Thanks, that worked fine! 

Regards,

Robert
