### ISSUE TITLE
bear not work correct for some cross compile name

### ISSUE THREAD

**Issue by sunlin7** [rizsotto/Bear#83]
Hi,

I try bear with a cross-compiler which name is "armv7_neno-linux-gnueabi-g++", but bear didn't collection  the compile database correctly.  
I modify the compiler pattern to match "armv7_neno-linux-gnueabi-g++", and bear work correctly, 
        re.compile(r'^([^/]*/)*c(c|\+\+)$'),
\+        re.compile(r'^([^/]*/)*([^/]*-)*c(c|\+\+)$'),
\-        re.compile(r'^([^/]*/)*([^-]*-)*g(cc|\+\+)(-\d+(\.\d+){0,2})?$'),
\+        re.compile(r'^([^/]*/)*([^-/]*-)*g(cc|\+\+)(-\d+(\.\d+){0,2})?$'),
        re.compile(r'^([^/]*/)*([^-]*-)*clang(\+\+)?(-\d+(\.\d+){0,2})?$'),
        re.compile(r'^([^/]*/)*llvm-g(cc|\+\+)$'),
Could you review these changes and add this to your official release? 
Or could you provide an option which allow user custom the compiler set?
Thank you.

**Comment by rizsotto** [comment]
@sunlin7 thanks for the report. I did test the 'armv7_neno-linux-gnueabi-g++' name, but it considered as a valid compiler name by the current regex. Maybe I got it wrong, so could you please send a pull request with your modification? Thanks!
