### ISSUE TITLE
duplicate entries generated

### ISSUE THREAD

**Issue by rwst** [rizsotto/Bear#86]
The github project `pynac/pynac` generates two entries per cpp file that differ by the flags `-fPIC -DPIC`.

**Comment by rizsotto** [comment]
@rwst thanks for the report. could you provide what version of Bear do you use? on what OS? and also, could you copy of the current output snippet (which cause the problem) and the desired output. and also a bit more explanation why do you think that different commands shall be one?

**Comment by rwst** [comment]
This is Bear git head on OpenSuSE 13.2. The output contains for every cpp file these two entries (example `archive.cpp`):
```
    {
        "command": "g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/include/python2.7 -g -O2 -std=gnu++11 -MT libpynac_la-archive.lo -MD -MP -MF .deps/libpynac_la-archive.Tpo -c archive.cpp -o libpynac_la-archive.o", 
        "directory": "/home/ralf/sage/pynac/ginac", 
        "file": "/home/ralf/sage/pynac/ginac/archive.cpp"
    }, 
    {
        "command": "g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/include/python2.7 -g -O2 -std=gnu++11 -fPIC -DPIC -MT libpynac_la-archive.lo -MD -MP -MF .deps/libpynac_la-archive.Tpo -c archive.cpp -o libpynac_la-archive.o", 
        "directory": "/home/ralf/sage/pynac/ginac", 
        "file": "/home/ralf/sage/pynac/ginac/archive.cpp"
    }, 
```
Using the output will make `clang-modernize` visit each file twice.

**Comment by rizsotto** [comment]
thanks, now i understand. unfortunately Bear can not merge these two entries into one. what is acceptable for `clang-modernize` might not be for other programs, since the `-DPIC` can modify the preprocessing step.
