### ISSUE TITLE
quotes not escaped

### ISSUE THREAD

**Issue by zauguin** [rizsotto/Bear#88]
When the compile command is like `-DABC=\"abc\""`, bear uses this literally in the compile_commands.json, which results in missing quotes at compile-time. It should escape the '\"' to'\\\"'.

**Comment by rizsotto** [comment]
thanks Marcel the report. i don't think your expectation is correct. when you say `-DABC=\"abc\"` to the shell it unescape it and call the `exec` call with `-DABC="abc"`. that is what bear captures and json escaping kicks in and it became `-DABC=\"abc\"` again.

**Comment by zauguin** [comment]
That sounds correct, but in practice to get the behaviour of `-DABC=\"abc\"` from the shell, the compile_commands.json must contain `-DABC=\\\"abc\\\"`. I don't really now why, maybe clang passes this to the shell again?

**Comment by rizsotto** [comment]
what is the program/tool that you are trying to use?

**Comment by zauguin** [comment]
The error occurs for example with `clang-check`.

**Comment by zauguin** [comment]
According to http://clang.llvm.org/docs/JSONCompilationDatabase.html, "After JSON unescaping" "Parameters use shell quoting and shell escaping of quotes".
