### ISSUE TITLE
CMake warning: policy CMP0042 (MACOSX_RPATH)

### ISSUE THREAD

**Issue by emlai** [rizsotto/Bear#90]
I ran `cmake $BEAR_SOURCE_DIR` with CMake 3.2.2 on OS X 10.11 beta and received the following `-Wdev` warning:

    CMake Warning (dev):
      Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
      --help-policy CMP0042" for policy details.  Use the cmake_policy command to
      set the policy and suppress this warning.

      MACOSX_RPATH is not specified for the following targets:

       ear

    This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by rizsotto** [comment]
thanks Emil the report.
