### ISSUE TITLE
run_shell_test, run_bug80, and run_bug81 failed

### ISSUE THREAD

**Issue by emlai** [rizsotto/Bear#91]
I ran `make check` and tests 1, 4, and 5 failed with the following output:

__Test 1__

    1: Test command: /usr/bin/make "run_shell_test"
    1: Test timeout computed to be: 9.99988e+06
    1: [ 50%] Built target ear
    1: Scanning dependencies of target run_shell_test
    1: [100%] Running module tests with shell
    1: bear: Namespace(append=False, build=['/Users/emlai/Documents/code/Bear/test/end-to-end/compile.sh', '/Users/emlai/Documents/code/Bear/test/end-to-end'], cdb='shell.json', libear='/Users/emlai/Documents/code/Bear/build/test/end-to-end/../../libear/libear.dylib', raw_entries=False, verbose=3)
    1: + c++ -c -fPIC -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
    1: + c++ -c -fPIC -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/bar.cc -o /dev/null
    1: + c++ -M -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
    1: + c++ -MM -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
    1: + c++ -MM -MG -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/bar.cc -o /dev/null
    1: + c++ -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/bar.cc -M -o /dev/null
    1: + true
    1: + echo 'gcc -invocation -look -like this.c'
    1: gcc -invocation -look -like this.c
    1: + c++ -c -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib -I/Users/emlai/Documents/code/Bear/test/end-to-end/bin /Users/emlai/Documents/code/Bear/test/end-to-end/bin/./boo.c++ -o /dev/null
    1: + c++ -c -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib -I/Users/emlai/Documents/code/Bear/test/end-to-end/bin /Users/emlai/Documents/code/Bear/test/end-to-end/bin/../bin/far.cxx -o /dev/null
    1: c++ -c bin/boo.cpp -o /dev/null
    1: + echo 'c++ -c bin/boo.cpp -o /dev/null'
    1: bear: build finished with exit code: 0
    1: make[7]: *** [test/end-to-end/CMakeFiles/run_shell_test] Error 1
    1: make[6]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/all] Error 2
    1: make[5]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
    1: make[4]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
    1/5 Test #1: run_shell_test ...................***Failed    0.51 sec
    test 2
        Start 2: run_exec_anatomy

__Test 4__

    4: Test command: /Users/emlai/Documents/code/Bear/build/test/bug80/run.sh
    4: Test timeout computed to be: 9.99988e+06
    4: clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
    4/5 Test #4: run_bug80 ........................***Failed    0.09 sec

__Test 5__

    5: Test command: /Users/emlai/Documents/code/Bear/build/test/bug81/run.sh
    5: Test timeout computed to be: 9.99988e+06
    5/5 Test #5: run_bug81 ........................***Failed    0.09 sec

I'm using python 2.7.6 and cmake 3.2.2. Output of `cmake $BEAR_SOURCE_DIR`:

    -- The C compiler identification is AppleClang 6.1.0.6020053
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Performing Test C99_SUPPORTED
    -- Performing Test C99_SUPPORTED - Success
    -- Looking for execve
    -- Looking for execve - found
    -- Looking for execv
    -- Looking for execv - found
    -- Looking for execvpe
    -- Looking for execvpe - not found
    -- Looking for execvp
    -- Looking for execvp - found
    -- Looking for execvP
    -- Looking for execvP - found
    -- Looking for execl
    -- Looking for execl - found
    -- Looking for execlp
    -- Looking for execlp - found
    -- Looking for execle
    -- Looking for execle - found
    -- Looking for posix_spawn
    -- Looking for posix_spawn - found
    -- Looking for posix_spawnp
    -- Looking for posix_spawnp - found
    -- Looking for _NSGetEnviron
    -- Looking for _NSGetEnviron - found
    -- Looking for scons
    -- Looking for qmake
    -- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
    -- Configuring done
    CMake Warning (dev):
      Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
      --help-policy CMP0042" for policy details.  Use the cmake_policy command to
      set the policy and suppress this warning.

      MACOSX_RPATH is not specified for the following targets:

       ear

    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Generating done
    -- Build files have been written to: /Users/emlai/Documents/code/Bear/build

Hope this helps.

**Comment by rizsotto** [comment]
can't reproduce it. might help if you tell me more about your setup. (which OS? what version of Bear?) maybe run `make check VERBOSE=1` or more advanced read these tests and run it from shell. that would help me a lot. thanks!

**Comment by emlai** [comment]
I'm using OS X 10.11 beta and Bear 2.0.4. Output with `make check VERBOSE=1`:

	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H/Users/emlai/Documents/code/Bear -B/Users/emlai/Documents/code/Bear/build --check-build-system CMakeFiles/Makefile.cmake 0
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 check
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H/Users/emlai/Documents/code/Bear -B/Users/emlai/Documents/code/Bear/build --check-build-system CMakeFiles/Makefile.cmake 0
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_start /Users/emlai/Documents/code/Bear/build/CMakeFiles 2
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 test/CMakeFiles/check.dir/all
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libear/CMakeFiles/ear.dir/build.make libear/CMakeFiles/ear.dir/depend
	cd /Users/emlai/Documents/code/Bear/build && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/emlai/Documents/code/Bear /Users/emlai/Documents/code/Bear/libear /Users/emlai/Documents/code/Bear/build /Users/emlai/Documents/code/Bear/build/libear /Users/emlai/Documents/code/Bear/build/libear/CMakeFiles/ear.dir/DependInfo.cmake --color=
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libear/CMakeFiles/ear.dir/build.make libear/CMakeFiles/ear.dir/build
	make[3]: Nothing to be done for `libear/CMakeFiles/ear.dir/build'.
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /Users/emlai/Documents/code/Bear/build/CMakeFiles  1
	[ 50%] Built target ear
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/exec_anatomy/CMakeFiles/exec_anatomy.dir/build.make test/exec_anatomy/CMakeFiles/exec_anatomy.dir/depend
	cd /Users/emlai/Documents/code/Bear/build && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/emlai/Documents/code/Bear /Users/emlai/Documents/code/Bear/test/exec_anatomy /Users/emlai/Documents/code/Bear/build /Users/emlai/Documents/code/Bear/build/test/exec_anatomy /Users/emlai/Documents/code/Bear/build/test/exec_anatomy/CMakeFiles/exec_anatomy.dir/DependInfo.cmake --color=
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/exec_anatomy/CMakeFiles/exec_anatomy.dir/build.make test/exec_anatomy/CMakeFiles/exec_anatomy.dir/build
	make[3]: Nothing to be done for `test/exec_anatomy/CMakeFiles/exec_anatomy.dir/build'.
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /Users/emlai/Documents/code/Bear/build/CMakeFiles  2
	[100%] Built target exec_anatomy
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/CMakeFiles/check.dir/build.make test/CMakeFiles/check.dir/depend
	cd /Users/emlai/Documents/code/Bear/build && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/emlai/Documents/code/Bear /Users/emlai/Documents/code/Bear/test /Users/emlai/Documents/code/Bear/build /Users/emlai/Documents/code/Bear/build/test /Users/emlai/Documents/code/Bear/build/test/CMakeFiles/check.dir/DependInfo.cmake --color=
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/CMakeFiles/check.dir/build.make test/CMakeFiles/check.dir/build
	cd /Users/emlai/Documents/code/Bear/build/test && ctest -V
	UpdateCTestConfiguration  from :/Users/emlai/Documents/code/Bear/build/test/DartConfiguration.tcl
	UpdateCTestConfiguration  from :/Users/emlai/Documents/code/Bear/build/test/DartConfiguration.tcl
	Test project /Users/emlai/Documents/code/Bear/build/test
	Constructing a list of tests
	Done constructing a list of tests
	Checking test dependency graph...
	Checking test dependency graph end
	test 1
	    Start 1: run_shell_test

	1: Test command: /usr/bin/make "run_shell_test"
	1: Test timeout computed to be: 9.99988e+06
	1: cd /Users/emlai/Documents/code/Bear/build && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 test/end-to-end/CMakeFiles/run_shell_test.dir/rule
	1: /usr/local/Cellar/cmake/3.2.2/bin/cmake -H/Users/emlai/Documents/code/Bear -B/Users/emlai/Documents/code/Bear/build --check-build-system CMakeFiles/Makefile.cmake 0
	1: /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_start /Users/emlai/Documents/code/Bear/build/CMakeFiles 2
	1: /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 test/end-to-end/CMakeFiles/run_shell_test.dir/all
	1: /Applications/Xcode.app/Contents/Developer/usr/bin/make -f libear/CMakeFiles/ear.dir/build.make libear/CMakeFiles/ear.dir/depend
	1: cd /Users/emlai/Documents/code/Bear/build && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/emlai/Documents/code/Bear /Users/emlai/Documents/code/Bear/libear /Users/emlai/Documents/code/Bear/build /Users/emlai/Documents/code/Bear/build/libear /Users/emlai/Documents/code/Bear/build/libear/CMakeFiles/ear.dir/DependInfo.cmake --color=
	1: /Applications/Xcode.app/Contents/Developer/usr/bin/make -f libear/CMakeFiles/ear.dir/build.make libear/CMakeFiles/ear.dir/build
	1: make[7]: Nothing to be done for `libear/CMakeFiles/ear.dir/build'.
	1: /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /Users/emlai/Documents/code/Bear/build/CMakeFiles  1
	1: [ 50%] Built target ear
	1: /Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/end-to-end/CMakeFiles/run_shell_test.dir/build.make test/end-to-end/CMakeFiles/run_shell_test.dir/depend
	1: cd /Users/emlai/Documents/code/Bear/build && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/emlai/Documents/code/Bear /Users/emlai/Documents/code/Bear/test/end-to-end /Users/emlai/Documents/code/Bear/build /Users/emlai/Documents/code/Bear/build/test/end-to-end /Users/emlai/Documents/code/Bear/build/test/end-to-end/CMakeFiles/run_shell_test.dir/DependInfo.cmake --color=
	1: /Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/end-to-end/CMakeFiles/run_shell_test.dir/build.make test/end-to-end/CMakeFiles/run_shell_test.dir/build
	1: /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /Users/emlai/Documents/code/Bear/build/CMakeFiles 3
	1: [100%] Running module tests with shell
	1: cd /Users/emlai/Documents/code/Bear/build/test/end-to-end && python /Users/emlai/Documents/code/Bear/build/test/end-to-end/../../bear/bear -vvv -l /Users/emlai/Documents/code/Bear/build/test/end-to-end/../../libear/libear.dylib -o shell.json /Users/emlai/Documents/code/Bear/test/end-to-end/compile.sh /Users/emlai/Documents/code/Bear/test/end-to-end
	1: bear: Namespace(append=False, build=['/Users/emlai/Documents/code/Bear/test/end-to-end/compile.sh', '/Users/emlai/Documents/code/Bear/test/end-to-end'], cdb='shell.json', libear='/Users/emlai/Documents/code/Bear/build/test/end-to-end/../../libear/libear.dylib', raw_entries=False, verbose=3)
	1: + c++ -c -fPIC -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
	1: + c++ -c -fPIC -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/bar.cc -o /dev/null
	1: + c++ -M -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
	1: + c++ -MM -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
	1: + c++ -MM -MG -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/bar.cc -o /dev/null
	1: + c++ -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib /Users/emlai/Documents/code/Bear/test/end-to-end/lib/bar.cc -M -o /dev/null
	1: + true
	1: + echo 'gcc -invocation -look -like this.c'
	1: gcc -invocation -look -like this.c
	1: + c++ -c -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib -I/Users/emlai/Documents/code/Bear/test/end-to-end/bin /Users/emlai/Documents/code/Bear/test/end-to-end/bin/./boo.c++ -o /dev/null
	1: + c++ -c -I/Users/emlai/Documents/code/Bear/test/end-to-end/lib -I/Users/emlai/Documents/code/Bear/test/end-to-end/bin /Users/emlai/Documents/code/Bear/test/end-to-end/bin/../bin/far.cxx -o /dev/null
	1: c++ -c bin/boo.cpp -o /dev/null
	1: + echo 'c++ -c bin/boo.cpp -o /dev/null'
	1: bear: build finished with exit code: 0
	1: cd /Users/emlai/Documents/code/Bear/build/test/end-to-end && test `python /Users/emlai/Documents/code/Bear/test/end-to-end/validate_and_count.py < shell.json` -eq 4
	1: make[7]: *** [test/end-to-end/CMakeFiles/run_shell_test] Error 1
	1: make[6]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/all] Error 2
	1: make[5]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
	1: make[4]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
	1/5 Test #1: run_shell_test ...................***Failed    0.25 sec
	test 2
	    Start 2: run_exec_anatomy

	2: Test command: /Users/emlai/Documents/code/Bear/build/test/exec_anatomy/run.sh
	2: Test timeout computed to be: 9.99988e+06
	2/5 Test #2: run_exec_anatomy .................   Passed    0.20 sec
	test 3
	    Start 3: result_code_check

	3: Test command: /Users/emlai/Documents/code/Bear/build/test/result_code/run.sh
	3: Test timeout computed to be: 9.99988e+06
	3/5 Test #3: result_code_check ................   Passed    0.10 sec
	test 4
	    Start 4: run_bug80

	4: Test command: /Users/emlai/Documents/code/Bear/build/test/bug80/run.sh
	4: Test timeout computed to be: 9.99988e+06
	4: c++ -o empty empty.c
	4: clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
	4/5 Test #4: run_bug80 ........................***Failed    0.08 sec
	test 5
	    Start 5: run_bug81

	5: Test command: /Users/emlai/Documents/code/Bear/build/test/bug81/run.sh
	5: Test timeout computed to be: 9.99988e+06
	5: c++ -DEXPORT="extern \"C\"" -o hello hello.cxx
	5/5 Test #5: run_bug81 ........................***Failed    0.09 sec

	40% tests passed, 3 tests failed out of 5

	Total Test time (real) =   0.73 sec

	The following tests FAILED:
		  1 - run_shell_test (Failed)
		  4 - run_bug80 (Failed)
		  5 - run_bug81 (Failed)

**Comment by zhongweiy** [comment]
Hi, there, On Mac OS 10.11.1, I've similar issue here (Bear is from master branch):
```
~/project/Bear/build $ make run_shell_test VERBOSE=1
/usr/local/Cellar/cmake/3.0.2/bin/cmake -H/Users/xxxx/project/Bear -B/Users/xxxx/project/Bear/build --check-build-system CMakeFiles/Makefile.cmake 0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 run_shell_test
/usr/local/Cellar/cmake/3.0.2/bin/cmake -H/Users/xxxx/project/Bear -B/Users/xxxx/project/Bear/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_progress_start /Users/xxxx/project/Bear/build/CMakeFiles 2
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 test/end-to-end/CMakeFiles/run_shell_test.dir/all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libear/CMakeFiles/ear.dir/build.make libear/CMakeFiles/ear.dir/depend
cd /Users/xxxx/project/Bear/build && /usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/xxxx/project/Bear /Users/xxxx/project/Bear/libear /Users/xxxx/project/Bear/build /Users/xxxx/pro\
ject/Bear/build/libear /Users/xxxx/project/Bear/build/libear/CMakeFiles/ear.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libear/CMakeFiles/ear.dir/build.make libear/CMakeFiles/ear.dir/build
make[3]: Nothing to be done for `libear/CMakeFiles/ear.dir/build'.
/usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_progress_report /Users/xxxx/project/Bear/build/CMakeFiles  1
[ 50%] Built target ear
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/end-to-end/CMakeFiles/run_shell_test.dir/build.make test/end-to-end/CMakeFiles/run_shell_test.dir/depend
cd /Users/xxxx/project/Bear/build && /usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/xxxx/project/Bear /Users/xxxx/project/Bear/test/end-to-end /Users/xxxx/project/Bear/build /Users\
/xxxx/project/Bear/build/test/end-to-end /Users/xxxx/project/Bear/build/test/end-to-end/CMakeFiles/run_shell_test.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f test/end-to-end/CMakeFiles/run_shell_test.dir/build.make test/end-to-end/CMakeFiles/run_shell_test.dir/build
/usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_progress_report /Users/xxxx/project/Bear/build/CMakeFiles 4
[100%] Running module tests with shell
cd /Users/xxxx/project/Bear/build/test/end-to-end && python /Users/xxxx/project/Bear/build/test/end-to-end/../../bear/bear -vvv -l /Users/xxxx/project/Bear/build/test/end-to-end/../../libear/libear.dylib -o shell.j\
son /Users/xxxx/project/Bear/test/end-to-end/compile.sh /Users/xxxx/project/Bear/test/end-to-end
bear: Namespace(append=False, build=['/Users/xxxx/project/Bear/test/end-to-end/compile.sh', '/Users/xxxx/project/Bear/test/end-to-end'], cdb='shell.json', libear='/Users/xxxx/project/Bear/build/test/end-to-end/../.\
./libear/libear.dylib', raw_entries=False, verbose=3)
bear: run build in environment: {'ALTERNATE_EDITOR': '', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'LINES': '63', 'LC_CTYPE': 'UTF-8', 'DYLD_INSERT_LIBRARIES': '/Users/xxxx/project/Bear/build/test/end-to-end/../../li\
bear/libear.dylib', 'LOGNAME': 'xxxx', 'USER': 'xxxx', 'HOME': '/Users/xxxx', 'PATH': '/Users/xxxx/project/clang/bin:/usr/local/smlnj-110.75/bin:/usr/local/share/python:/usr/local/bin:/usr/local/sbin:/Users/xxxx/bi\
n/depot_tools:/Applications/Android Studio.app/sdk/platform-tools:/usr/local/smlnj/bin:/Users/xxxx/bin/gcc-arm-none-eabi-4_9-2014q4/bin:/Users/xxxx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr\
/texbin:/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9:/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9', 'DISPLAY': '/private/tmp/com.apple.launchd.G3gyTiIfRr/org.macosforge.xquartz:0', 'MAKEFLAG\
S': 'VERBOSE=1', 'TERM_PROGRAM': 'iTerm.app', 'TERM': 'dumb', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.BiJTjrjZIp/Render', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '3', 'SECURITYSESSIONID': \
'186a9', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w0t0p0', '_': '/usr/bin/python', 'MFLAGS': '', 'DYLD_FORCE_FLAT_NAMESPACE': '1', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.lEorLjhfSt/Listeners', 'XPC_SERVIC\
E_NAME': '0', 'BEAR_OUTPUT': '/var/folders/vm/2p9vwrrs6vqdx6rwdkrbkcl80000gn/T/bear-OAISXI', 'SHELL': '/bin/bash', 'COLUMNS': '215', 'ITERM_PROFILE': 'Default', 'MAKEOVERRIDES': '${-*-command-variables-*-}', 'TMPDI\
R': '/var/folders/vm/2p9vwrrs6vqdx6rwdkrbkcl80000gn/T/', 'VERBOSE': '1', 'OLDPWD': '/Users/xxxx/project/Bear/build', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'MAKELEVEL': '4', 'PWD': '/Users/xxxx/project/Bear/bu\
ild/test/end-to-end', 'COMMAND_MODE': 'unix2003'}
+ c++ -c -fPIC -I/Users/xxxx/project/Bear/test/end-to-end/lib /Users/xxxx/project/Bear/test/end-to-end/lib/foo.cpp -o /dev/null
+ c++ -c -fPIC -I/Users/xxxx/project/Bear/test/end-to-end/lib /Users/xxxx/project/Bear/test/end-to-end/lib/bar.cc -o /dev/null
+ c++ -c -I/Users/xxxx/project/Bear/test/end-to-end/lib -I/Users/xxxx/project/Bear/test/end-to-end/bin /Users/xxxx/project/Bear/test/end-to-end/bin/./boo.c++ -o /dev/null
+ c++ -c -I/Users/xxxx/project/Bear/test/end-to-end/lib -I/Users/xxxx/project/Bear/test/end-to-end/bin /Users/xxxx/project/Bear/test/end-to-end/bin/../bin/far.cxx -o /dev/null
+ true
+ echo 'gcc -invocation -look -like this.c'
gcc -invocation -look -like this.c
+ echo 'c++ -c bin/boo.cpp -o /dev/null'
c++ -c bin/boo.cpp -o /dev/null
bear: build finished with exit code: 0
cd /Users/xxxx/project/Bear/build/test/end-to-end && test `python /Users/xxxx/project/Bear/test/end-to-end/validate_and_count.py < shell.json` -eq 4
make[3]: *** [test/end-to-end/CMakeFiles/run_shell_test] Error 1
make[2]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/all] Error 2
make[1]: *** [test/end-to-end/CMakeFiles/run_shell_test.dir/rule] Error 2
make: *** [run_shell_test] Error 2
```

**Comment by rizsotto** [comment]
@zhongweiy could you .tar.gz the source and build directory and send me over email? since i don't have this OS, would do some post mortal analysis.

**Comment by xiedingbao** [comment]
I also ran into the same issue on osx 10.11.1

**Comment by rizsotto** [comment]
@xiedingbao, thanks for your confirmation. i'm still lacking this machine and OS... and as i said earlier .tar.gz of the source and build directory in email would be more usefull. thanks in advance if you can do that!

**Comment by zhongweiy** [comment]
Hi, László,
Sorry for my late reply. The whole build of Bear on OS X 10.11.1 is
attached. Please take a look, Thanks!
--
Zhongwei

**Comment by zhongweiy** [comment]
@rizsotto reply with attachment seems be ignored in above comment. And I have also tried to sent your `rizsotto at google dot com`, but gmail tells me `550-5.1.1 The email account that you tried to reach does not exist.` Is there any other way to send you this?

**Comment by rizsotto** [comment]
thanks, will look at it on the weekend. might gonna find something!

**Comment by rizsotto** [comment]
sorry for the late reply, the issue you have reported looks very similar to #108 can you verify and reopen the ticket if i am mistaken?
