### ISSUE TITLE
Q: Tips on debugging a complex scons build resulting in blank database?

### ISSUE THREAD

**Issue by KarateSnowMachine** [rizsotto/Bear#98]
Hello, 

I'm trying to generate a compilation database for gem5 (https://github.com/uart/gem5-mirror) which uses a very complicated scons build process. I have built Bear from master and am running `bear -vv scons build/ARM/gem5.debug`. I get the initial print from Bear with the environment variables and I see scons invoking g++ and then I see some ending prints: 

```
scons: done building targets.
bear: build finished with exit code: 0
bear: parse exec trace file: /tmp/bear-Qc0HlX/14479.cmd
bear: parse exec trace file: /tmp/bear-Qc0HlX/14481.cmd
bear: parse exec trace file: /tmp/bear-Qc0HlX/14482.cmd
bear: format this command: ['gcc', '--version']
<<<<snip>>>> 
```

but the resulting compilation database is simply `[]`. 

Do you have any tips for what I can try to debug the problem to see what is happening?

**Comment by KarateSnowMachine** [comment]
I took a closer look at my environment and it turns out that I had `CXX=g++48` which was a symlink to a custom g++4.8 installation. When I removed the symlink so that `CXX=g++` and `$PATH` simply pointed to g++4.8 install then I got a compilation database. I'm not too familiar with how Bear works, but does this sound like having `CXX=g++48` could cause such a failure?

**Comment by rizsotto** [comment]
yes, it might be the problem. the regex for gcc compilers is `^([^/]*/)*([^-]*-)*[mg](cc|\+\+)(-\d+(\.\d+){0,2})?$`. it gets compiler names like `g++-4.8`, but `g++48` will not pass. (it's not really a common compiler name for multiple compiler setup.)

**Comment by KarateSnowMachine** [comment]
Ah OK, thanks.
