### ISSUE TITLE
Is possible to append ?

### ISSUE THREAD

**Issue by MaikoID** [rizsotto/Bear#99]
Hi, nice work so far. I'm wondering if it is possible to append new compiling output to the compile_commands.json file;
In this way the file could be constantly updated when one add/change code.

thx

**Comment by rizsotto** [comment]
thanks Maiko. there is a `-a` option which does append new entries to the existing compilation database. it also removes the entries for those files which are not acccessible. the intended use case scenario that you can run your build command with Bear multiple times and it always the compilation database up to date. (it breaks if you change the build flags or compiler.) is that what you meant?

**Comment by MaikoID** [comment]
Yes, it is. I totally missed it from the help menu.
